//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0111D0013TBLEARCHIVEHISTORY
    {
        public int IND { get; set; }
        public Nullable<int> EVRAKNO { get; set; }
        public Nullable<bool> IPTAL { get; set; }
        public string ETTN { get; set; }
        public string BELGENO { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string STATUSSTR { get; set; }
        public string COMMENT { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<int> IZAHAT { get; set; }
    }
}
