//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0111D0013TBLBASITSTOKDUSBELGEBASLIK
    {
        public int IND { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public Nullable<int> HAMMADDEDEPONO { get; set; }
        public Nullable<int> MAMULDEPONO { get; set; }
        public Nullable<int> USERNO { get; set; }
        public Nullable<int> BIRIMIND { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string BELGENOTU { get; set; }
        public string STOKKODU { get; set; }
        public string MALINCINSI { get; set; }
        public string OZELKOD4 { get; set; }
        public string OZELKOD5 { get; set; }
        public string OZELKOD6 { get; set; }
        public string OZELKOD7 { get; set; }
        public string OZELKOD8 { get; set; }
        public string OZELKOD1 { get; set; }
        public string OZELKOD2 { get; set; }
        public string OZELKOD3 { get; set; }
    }
}
