//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0112TBLTEKARZURNKAYIT
    {
        public int IND { get; set; }
        public Nullable<int> URUNNO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<System.DateTime> TESLIMTARIH { get; set; }
        public Nullable<System.DateTime> TESLIMSAAT { get; set; }
        public Nullable<System.DateTime> KAPANISTARIHI { get; set; }
        public Nullable<bool> KAPALI { get; set; }
        public string KABULKODU { get; set; }
        public string FISNO { get; set; }
        public string ACIKLAMA { get; set; }
        public string POZISYON { get; set; }
        public string MUSTERIADI { get; set; }
    }
}
