//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0114TBLBEYODEME
    {
        public int IND { get; set; }
        public Nullable<int> ODEMEIND { get; set; }
        public string ADSOYAD { get; set; }
        public string ADRES { get; set; }
        public string VDHESAPNO { get; set; }
        public string TURU { get; set; }
        public Nullable<decimal> GAYTUTAR { get; set; }
        public Nullable<decimal> KESVERGITUTARI { get; set; }
        public string TCKIMLIKNO { get; set; }
        public Nullable<System.DateTime> ODEMETARIHI { get; set; }
        public string ODEMESERISIRANO { get; set; }
        public string ODEMETURKODU { get; set; }
        public string KDVTEVKIFATI { get; set; }
        public string ADRESNO { get; set; }
    }
}
