//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0112TBLPERAILEDURUM1
    {
        public int IND { get; set; }
        public Nullable<int> SUBEIND { get; set; }
        public Nullable<int> PERSONELIND { get; set; }
        public Nullable<int> YIL { get; set; }
        public Nullable<int> AY { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<bool> ESICALISIYOR { get; set; }
        public Nullable<bool> ESGELIRIVAR { get; set; }
        public string ACIKLAMA { get; set; }
        public string TCKIMLIKNO { get; set; }
        public string ESSOYADI { get; set; }
        public string ESGELIRACIKLAMA { get; set; }
        public string DUZENLEYENADI { get; set; }
        public string DUZENLEYENSOYADI { get; set; }
        public string GOREVI { get; set; }
        public string ADI { get; set; }
        public string SOYADI { get; set; }
        public string MEDENIHALI { get; set; }
        public string SSKSICILNO { get; set; }
        public string ESADI { get; set; }
    }
}
