//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0111TBLTURECETEBASLIK
    {
        public int IND { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public Nullable<int> STOKTIPI { get; set; }
        public Nullable<int> ANARECETEIND { get; set; }
        public Nullable<System.DateTime> OLUSTURMATARIHI { get; set; }
        public string STOKKODU { get; set; }
        public string MALINCINSI { get; set; }
        public string KOD1 { get; set; }
        public string ACIKLAMA { get; set; }
        public string EVRAKNO { get; set; }
        public string ALTKARTADI { get; set; }
    }
}
