//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0114TBLKIDEM
    {
        public int IND { get; set; }
        public Nullable<int> SUBEIND { get; set; }
        public Nullable<int> PERSONELIND { get; set; }
        public Nullable<int> MUHASEBEIND { get; set; }
        public Nullable<int> CGUN { get; set; }
        public Nullable<int> DAMGAVERGISI { get; set; }
        public Nullable<int> YIL { get; set; }
        public Nullable<int> AY { get; set; }
        public Nullable<int> CYIL { get; set; }
        public Nullable<int> CAY { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<System.DateTime> ISEGIRISTARIHI { get; set; }
        public Nullable<System.DateTime> ISTENCIKISTARIHI { get; set; }
        public Nullable<bool> YAZDIRILDI { get; set; }
        public Nullable<bool> SECIM { get; set; }
        public Nullable<decimal> BRUTMAAS { get; set; }
        public Nullable<decimal> TOPLAMTUTAR { get; set; }
        public Nullable<decimal> KIDEMTAZ { get; set; }
        public Nullable<decimal> DAMGAVBINDE { get; set; }
        public string ACIKLAMA { get; set; }
    }
}
