//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0111TBLBEYEKBSATIS
    {
        public int IND { get; set; }
        public Nullable<int> EKBIND { get; set; }
        public Nullable<int> SIRANO { get; set; }
        public Nullable<int> BELGESAYISI { get; set; }
        public Nullable<decimal> TOPLAMBEDEL { get; set; }
        public string UNVAN { get; set; }
        public string ULKE { get; set; }
        public string TCKIMLIKNO { get; set; }
        public string VERGINO { get; set; }
    }
}
