//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0114D0011TBLICRAVUKATTAHSILHAREKET
    {
        public int IND { get; set; }
        public Nullable<int> BASLIKNO { get; set; }
        public Nullable<int> FIRMANO { get; set; }
        public Nullable<int> BELGENO { get; set; }
        public Nullable<int> GHNO { get; set; }
        public Nullable<int> BELGEIZAHAT { get; set; }
        public Nullable<int> ISLEMIZAHAT { get; set; }
        public Nullable<int> AVUKATNO { get; set; }
        public Nullable<System.DateTime> EVRAKTARIHI { get; set; }
        public Nullable<System.DateTime> AVUKATTARIH { get; set; }
        public Nullable<bool> KAPANDI { get; set; }
        public Nullable<decimal> TAHSILTUTARI { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public string FIRMAKODU { get; set; }
        public string FIRMAADI { get; set; }
        public string EVRAKNO { get; set; }
        public string BELGELER { get; set; }
    }
}
