//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0111D0015TBLMUHBELGEISLEM
    {
        public int IND { get; set; }
        public Nullable<int> BIND { get; set; }
        public Nullable<int> DIND { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<decimal> TUTARM { get; set; }
        public Nullable<decimal> TUTARD { get; set; }
        public string ACIKLAMA { get; set; }
        public string ACIKLAMAM { get; set; }
        public string ACIKLAMAD { get; set; }
    }
}
