//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0111D0008TBLMUHENFISLEM
    {
        public int IND { get; set; }
        public Nullable<int> HIND { get; set; }
        public Nullable<int> AMORTISMANHESABI { get; set; }
        public Nullable<int> FISTURU { get; set; }
        public Nullable<int> YONTEM { get; set; }
        public Nullable<int> DONEM { get; set; }
        public Nullable<int> FIND { get; set; }
        public Nullable<int> IIND { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<System.DateTime> FKAPANMATARIHI { get; set; }
        public Nullable<bool> FTEVSIK { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<decimal> YDA { get; set; }
        public Nullable<decimal> BIRIKMISAMORTISMAN { get; set; }
        public Nullable<decimal> KATSAYI { get; set; }
        public Nullable<decimal> TEFE { get; set; }
        public Nullable<decimal> SDHDONEMBASI { get; set; }
        public Nullable<decimal> SDHKULLANIM { get; set; }
        public Nullable<decimal> ROFM { get; set; }
        public Nullable<decimal> DTUTAR { get; set; }
        public Nullable<decimal> FMALIYETTUTARI { get; set; }
        public string HESAPKODU { get; set; }
        public string HESAPADI { get; set; }
        public string ACIKLAMA { get; set; }
    }
}
