//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0114D0011TBLMUHBELGEHESAPKODUEX
    {
        public int IND { get; set; }
        public Nullable<int> BELGELINEIND { get; set; }
        public string HESAPKODU { get; set; }
        public string BORC { get; set; }
        public string ACIKLAMA { get; set; }
        public string MIKTARBILGISI { get; set; }
        public string DOVIZBILGISI { get; set; }
    }
}
