//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0112D0003TBLMOBTOPLUISEMRIHAREKET
    {
        public int IND { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public Nullable<int> SIPARISCARINO { get; set; }
        public Nullable<int> STOKSABLONNO { get; set; }
        public Nullable<int> BASLIKNO { get; set; }
        public Nullable<int> RECETENO { get; set; }
        public Nullable<System.DateTime> ISEMRITARIHI { get; set; }
        public Nullable<bool> EDT { get; set; }
        public Nullable<bool> KATLOGMALIYET { get; set; }
        public Nullable<bool> KATALOG { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<decimal> BIRIMGUC { get; set; }
        public Nullable<decimal> URETILENMIKTAR { get; set; }
        public Nullable<decimal> URETILECEKMIKTAR { get; set; }
        public Nullable<decimal> HACIM { get; set; }
        public Nullable<decimal> AGIRLIK { get; set; }
        public string ISEMRINO { get; set; }
        public string OZELKOD { get; set; }
        public string ACIKLAMA { get; set; }
        public string SIPARISCARIKODU { get; set; }
        public string SIPARISCARIADI { get; set; }
        public string SABLONADI { get; set; }
        public string GUIDNO { get; set; }
        public string MODELKODU { get; set; }
        public string MODELADI { get; set; }
    }
}
