//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0112TBLOPTKURUMLAR
    {
        public int IND { get; set; }
        public Nullable<int> CARIIND { get; set; }
        public string ADRES { get; set; }
        public Nullable<decimal> CERCEVE { get; set; }
        public Nullable<decimal> CAMINDYUZDE { get; set; }
        public Nullable<decimal> KATILIMPAYIYUZDE { get; set; }
        public Nullable<decimal> CALISANKATKIPAYI { get; set; }
        public Nullable<decimal> EMEKLIKATKIPAYI { get; set; }
        public string KURUMAD { get; set; }
        public string YETKILI { get; set; }
        public string KURUMKODU { get; set; }
    }
}
