//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0114D0011TBLISLEM
    {
        public Nullable<short> SEL { get; set; }
        public int IND { get; set; }
        public int FIND { get; set; }
        public Nullable<int> YEVMIYE { get; set; }
        public Nullable<int> YEVMIYENO { get; set; }
        public Nullable<int> LINENUMBER { get; set; }
        public Nullable<int> SEVIYE { get; set; }
        public Nullable<int> SIND { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<System.DateTime> EVRAKTARIHI { get; set; }
        public Nullable<bool> DETAY { get; set; }
        public Nullable<bool> DETAYLANDIRILDI { get; set; }
        public Nullable<decimal> BIRIMFIYAT { get; set; }
        public Nullable<decimal> BAKIYE { get; set; }
        public Nullable<decimal> ALACAK { get; set; }
        public Nullable<decimal> DALACAK { get; set; }
        public Nullable<decimal> BMIKTAR { get; set; }
        public Nullable<decimal> BORC { get; set; }
        public Nullable<decimal> DBORC { get; set; }
        public Nullable<decimal> KUR { get; set; }
        public Nullable<decimal> AMIKTAR { get; set; }
        public string HESAPKODU { get; set; }
        public string EVRAKNO { get; set; }
        public string BELGETURU { get; set; }
        public string ODEMETURU { get; set; }
        public string FISTIPI { get; set; }
        public string EVRAKTIPI { get; set; }
        public string HESAPADI { get; set; }
        public string ACIKLAMA { get; set; }
        public string TCVERGINO { get; set; }
    }
}
