//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0111D0013TBLFIYATTEKLIFIODEMEPLANIHAREKET
    {
        public int IND { get; set; }
        public Nullable<int> BASLIKIND { get; set; }
        public Nullable<int> PLANLANANISLEMTIPI { get; set; }
        public Nullable<int> GERCEKLESENISLEMTIPI { get; set; }
        public Nullable<System.DateTime> PLANLANANVADE { get; set; }
        public Nullable<System.DateTime> GERCEKLESENVADE { get; set; }
        public Nullable<decimal> PLANLANANFIYAT { get; set; }
        public Nullable<decimal> GERCEKLESENFIYAT { get; set; }
    }
}
