//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0114TBLMOBRECETESTOKSABLONU
    {
        public int IND { get; set; }
        public Nullable<int> BASLIKNO { get; set; }
        public string SABLONDETAY { get; set; }
        public Nullable<bool> TIP { get; set; }
        public string SABLONADI { get; set; }
    }
}
