//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0114D0011TBLBANKODEMEHAREKET
    {
        public int IND { get; set; }
        public Nullable<int> IZAHAT { get; set; }
        public Nullable<int> PORTNO { get; set; }
        public Nullable<int> EVRAKNO { get; set; }
        public Nullable<int> BELGELINK { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<System.DateTime> VADE { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<decimal> KUR { get; set; }
        public Nullable<decimal> KOMISYON { get; set; }
        public string MUHHESAPKODU { get; set; }
        public string PARABIRIMI { get; set; }
        public string BELGENO { get; set; }
    }
}
