//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0112TBLBEYMUHTASAR
    {
        public byte[] DATA { get; set; }
        public int IND { get; set; }
        public Nullable<int> BEYANIMYOK { get; set; }
        public Nullable<int> SUBE_IND { get; set; }
        public string GVK4691TERKIN { get; set; }
        public string GVK4691ISYERI { get; set; }
        public string MUKELLEFBILGISI { get; set; }
        public string YERALTIYERUSTU { get; set; }
        public string SERBESTTUTARIADE { get; set; }
        public string GELIRVERGISI { get; set; }
        public string GVKGECICI80ISYERI { get; set; }
        public string GVKGECICI80TERKIN { get; set; }
        public string GVKGECICI80UCRETLI { get; set; }
        public string ARGEISTISNA { get; set; }
        public string KULTURYATIRIMI { get; set; }
        public string KULTURGIRISIMI { get; set; }
        public string SERBESTISYERI { get; set; }
        public string SERBESTTUTAR { get; set; }
        public string SERBESTISYERIIADE { get; set; }
        public string ODEMELER { get; set; }
        public string DOKTORALIASGARI { get; set; }
        public string DOKTORALIDIGER { get; set; }
        public string DIGERLERIASGARI { get; set; }
        public string DIGERLERIDIGER { get; set; }
        public string ARGEISYERI { get; set; }
        public Nullable<bool> OCAK { get; set; }
        public Nullable<bool> SUB { get; set; }
        public Nullable<bool> MART { get; set; }
        public Nullable<bool> NIS { get; set; }
        public Nullable<bool> KAS { get; set; }
        public Nullable<bool> ARA { get; set; }
        public Nullable<bool> SEC { get; set; }
        public Nullable<bool> YAZDIR { get; set; }
        public Nullable<bool> MAY { get; set; }
        public Nullable<bool> HAZ { get; set; }
        public Nullable<bool> TEM { get; set; }
        public Nullable<bool> AGU { get; set; }
        public Nullable<bool> EYL { get; set; }
        public Nullable<bool> EKI { get; set; }
        public string ACIKLAMA { get; set; }
        public string YILI { get; set; }
        public string ISYERIBILGILERI { get; set; }
        public string ISCIBILGILERI { get; set; }
        public string ISTIHDAMTESVIK { get; set; }
        public string ISTIHDAMTERKIN { get; set; }
        public string GVTEVKIFAT { get; set; }
    }
}
