//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0114TBLATTACHEDDOCUMENTS
    {
        public int IND { get; set; }
        public Nullable<int> IZAHAT { get; set; }
        public string EXT { get; set; }
        public string EVRAKNAME { get; set; }
        public string PATH { get; set; }
        public Nullable<int> REFNO { get; set; }
        public Nullable<System.DateTime> EKLEMETARIHI { get; set; }
        public Nullable<int> EVRAKIZAHAT { get; set; }
        public Nullable<int> EVRAKIND { get; set; }
    }
}
