//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0111TBLPRIM4A2
    {
        public int IND { get; set; }
        public Nullable<int> PRIMIND { get; set; }
        public Nullable<int> PERSONELIND { get; set; }
        public Nullable<System.DateTime> ISEGIRISTARIHI { get; set; }
        public Nullable<System.DateTime> ISTENCIKISTARIHI { get; set; }
        public Nullable<decimal> A2KAZANC { get; set; }
        public Nullable<decimal> A3GUN { get; set; }
        public Nullable<decimal> A3KAZANC { get; set; }
        public Nullable<decimal> A4GUN { get; set; }
        public Nullable<decimal> A4KAZANC { get; set; }
        public Nullable<decimal> GUN { get; set; }
        public Nullable<decimal> SSKMATRAHI { get; set; }
        public Nullable<decimal> A1GUN { get; set; }
        public Nullable<decimal> A1KAZANC { get; set; }
        public Nullable<decimal> A2GUN { get; set; }
        public string SSKSICILNO { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
    }
}
