//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0111D0015TBLUREPLAN
    {
        public int IND { get; set; }
        public Nullable<int> DETAY { get; set; }
        public Nullable<int> EVRAKNO { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public Nullable<int> SIPARISNO { get; set; }
        public Nullable<int> ISEMRIIND { get; set; }
        public Nullable<int> KULLANICI { get; set; }
        public Nullable<int> TUR { get; set; }
        public Nullable<int> YERNO { get; set; }
        public Nullable<System.DateTime> TERMIN { get; set; }
        public Nullable<System.DateTime> URETIMEBASLAMATARIHI { get; set; }
        public Nullable<System.DateTime> ISLEMTARIHI { get; set; }
        public Nullable<System.DateTime> SONERISIMTARIHI { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<decimal> ORAN { get; set; }
        public Nullable<decimal> EKMIKTAR { get; set; }
        public Nullable<decimal> BIRIMMIKTAR { get; set; }
        public Nullable<decimal> KDV { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
        public string STOKKODU { get; set; }
        public string MALINCINSI { get; set; }
        public string ACIKLAMA { get; set; }
        public string ISEMRINO { get; set; }
        public string BIRIM { get; set; }
        public string BARCODE { get; set; }
    }
}
