//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0114D0011TBLSUBEHEDEFCIROTANIMLARI
    {
        public int IND { get; set; }
        public Nullable<int> SUBEIND { get; set; }
        public Nullable<decimal> HEDEFCIRO { get; set; }
        public Nullable<decimal> AY1 { get; set; }
        public Nullable<decimal> AY2 { get; set; }
        public Nullable<decimal> AY3 { get; set; }
        public Nullable<decimal> AY4 { get; set; }
        public Nullable<decimal> AY11 { get; set; }
        public Nullable<decimal> AY12 { get; set; }
        public Nullable<decimal> AY5 { get; set; }
        public Nullable<decimal> AY6 { get; set; }
        public Nullable<decimal> AY7 { get; set; }
        public Nullable<decimal> AY8 { get; set; }
        public Nullable<decimal> AY9 { get; set; }
        public Nullable<decimal> AY10 { get; set; }
    }
}
