//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0111D0008TBLMOBPLANHAMMADDE
    {
        public int IND { get; set; }
        public Nullable<int> BASLIKIND { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public Nullable<System.DateTime> VERILENSIPARISINTESLIMALINACAGITARIH { get; set; }
        public Nullable<decimal> ENVANTER { get; set; }
        public Nullable<decimal> IHTIYACMIKTARI { get; set; }
        public Nullable<decimal> VERILENSIPARISMIKTARI { get; set; }
        public string STOKKODU { get; set; }
        public string MALINCINSI { get; set; }
        public string BIRIM { get; set; }
    }
}
