//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0114TBLOTSARACLIST
    {
        public byte[] RESIM { get; set; }
        public int IND { get; set; }
        public Nullable<int> TBLOTSARACTANIMREF { get; set; }
        public Nullable<int> IKINCIELREF { get; set; }
        public Nullable<int> TBLOTSGRSMEMUSTERILISTESIREF { get; set; }
        public Nullable<int> ABSOLUTEINDEX { get; set; }
        public Nullable<int> HAREKETREF { get; set; }
        public Nullable<int> TBLSTOKHAREKETLERIREF { get; set; }
        public Nullable<int> CIKHAREKETREF { get; set; }
        public Nullable<int> GIRTBLBASLIKREF { get; set; }
        public Nullable<int> CIKTBLBASLIKREF { get; set; }
        public Nullable<System.DateTime> SONREZERVTARIHI { get; set; }
        public Nullable<bool> ISKONSINYE { get; set; }
        public Nullable<bool> SIPARISMI { get; set; }
        public Nullable<bool> ISIKINCIEL { get; set; }
        public Nullable<bool> METALIK { get; set; }
        public Nullable<bool> STOKTA { get; set; }
        public Nullable<decimal> OTV { get; set; }
        public string SASINO { get; set; }
        public string MOTORNO { get; set; }
        public string KODU { get; set; }
        public string PLAKA { get; set; }
        public string STOKADI { get; set; }
        public string PARKYERINUMARASI { get; set; }
        public string MODELYIL { get; set; }
        public string SIPARISDURUMU { get; set; }
        public string RENK { get; set; }
    }
}
