//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0111D0013TBLUREPLANSIPARIS
    {
        public int IND { get; set; }
        public Nullable<int> PLANNO { get; set; }
        public Nullable<int> PLANSATIRNO { get; set; }
        public Nullable<int> SIPARISNO { get; set; }
        public Nullable<int> SIPARISSATIRNO { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
    }
}
