//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0111D0008TBLOTOSRVKAYITBASLIK
    {
        public int IND { get; set; }
        public Nullable<int> ARACNO { get; set; }
        public Nullable<int> SERVISDANISMANIIND { get; set; }
        public Nullable<int> STOKIND { get; set; }
        public Nullable<int> IZAHAT { get; set; }
        public Nullable<int> BELGENO { get; set; }
        public Nullable<int> KLEIMBELGENO { get; set; }
        public Nullable<int> FIRMANO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<System.DateTime> TTESLIMTARIH { get; set; }
        public Nullable<System.DateTime> TTESLIMSAAT { get; set; }
        public Nullable<System.DateTime> CRDATE { get; set; }
        public Nullable<System.DateTime> TESLIMTARIHI { get; set; }
        public string ADRES { get; set; }
        public Nullable<bool> KDV { get; set; }
        public Nullable<bool> IPTAL { get; set; }
        public Nullable<bool> RESERV10 { get; set; }
        public Nullable<bool> RESERV4 { get; set; }
        public Nullable<bool> RESERV5 { get; set; }
        public Nullable<bool> RESERV6 { get; set; }
        public Nullable<bool> RESERV7 { get; set; }
        public Nullable<bool> RESERV8 { get; set; }
        public Nullable<bool> RESERV9 { get; set; }
        public Nullable<bool> RESERV3 { get; set; }
        public Nullable<decimal> ALTISKTUTAR { get; set; }
        public string KABULNO { get; set; }
        public string FISNO { get; set; }
        public string ISEMRITIPI { get; set; }
        public string ISEMRIDURUMU { get; set; }
        public string SERVISDANISMANI { get; set; }
        public string RESERV12 { get; set; }
        public string OZELKOD1 { get; set; }
        public string OZELKOD2 { get; set; }
        public string OZELKOD3 { get; set; }
        public string OZELKOD4 { get; set; }
        public string KAMPANYAKODU { get; set; }
        public string RESERV13 { get; set; }
        public string RESERV14 { get; set; }
        public string RESERV11 { get; set; }
        public string SASINO { get; set; }
        public string MOTORNO { get; set; }
        public string IRTIBATSAHIS { get; set; }
        public string IRTIBATTELEFON { get; set; }
        public string DIGER { get; set; }
        public string PLAKA { get; set; }
        public string VERGINO { get; set; }
        public string KM { get; set; }
        public string RESERV1 { get; set; }
        public string RESERV2 { get; set; }
        public string FIRMAKODU { get; set; }
        public string FIRMAADI { get; set; }
        public string TELEFON { get; set; }
        public string VERGIDAIRESI { get; set; }
        public string OZELKOD5 { get; set; }
        public string OZELKOD6 { get; set; }
        public string OZELKOD7 { get; set; }
        public string OZELKOD8 { get; set; }
        public string OZELKOD9 { get; set; }
        public string TCKIMLIKNO { get; set; }
        public string UID { get; set; }
    }
}
