//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0111TBLBEYVERGIDILIMLERI
    {
        public int IND { get; set; }
        public string FIRMA_KODU { get; set; }
        public Nullable<decimal> DILIM_1 { get; set; }
        public Nullable<decimal> DILIM_2 { get; set; }
        public Nullable<decimal> DILIM_3 { get; set; }
        public Nullable<decimal> DILIM_4 { get; set; }
        public Nullable<decimal> DILIM_5 { get; set; }
        public Nullable<decimal> DILIM_6 { get; set; }
        public Nullable<decimal> ORAN_1 { get; set; }
        public Nullable<decimal> ORAN_2 { get; set; }
        public Nullable<decimal> ORAN_3 { get; set; }
        public Nullable<decimal> ORAN_4 { get; set; }
        public Nullable<decimal> ORAN_5 { get; set; }
        public Nullable<decimal> ORAN_6 { get; set; }
        public Nullable<decimal> ORANKDV1 { get; set; }
        public Nullable<decimal> ORANKDV2 { get; set; }
        public Nullable<decimal> ORANKDV3 { get; set; }
        public Nullable<decimal> ORANKDV4 { get; set; }
        public Nullable<decimal> ORANKDV5 { get; set; }
        public Nullable<decimal> ORANKDV6 { get; set; }
        public Nullable<int> YIL { get; set; }
        public Nullable<decimal> KURUMORAN { get; set; }
    }
}
