//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0111TBLPERISYERIBILDIRGESI2
    {
        public int IND { get; set; }
        public Nullable<int> ISYERIIND { get; set; }
        public string ISVUNVANI { get; set; }
        public string ISVADSOYAD { get; set; }
        public string ISVADRES { get; set; }
        public string ISVVERGIDAINO { get; set; }
        public string ISVBASLAMATARIHI { get; set; }
        public string ISVHISSEORANI { get; set; }
        public string ISVTICSICILNO { get; set; }
        public string ISVTELEFON1 { get; set; }
        public string ISVTELEFON2 { get; set; }
        public string ISVBABAADI { get; set; }
        public string ISVDOGUMTARIHI { get; set; }
        public string ISVDOGUMYERI { get; set; }
        public string ISVNUFUSSERISIRANO { get; set; }
        public string ISVARACPLAKA { get; set; }
        public string ISVNUFUSKAYIT { get; set; }
        public string ISVDIGERSICILNO { get; set; }
        public string IS2UNVANI { get; set; }
        public string IS2ADSOYAD { get; set; }
        public string IS2ADRES { get; set; }
        public string IS2VERGIDAINO { get; set; }
        public string IS2BASLAMATARIHI { get; set; }
        public string IS2HISSEORANI { get; set; }
        public string IS2TICSICILNO { get; set; }
        public string IS2TELEFON1 { get; set; }
        public string IS2TELEFON2 { get; set; }
        public string IS2BABAADI { get; set; }
        public string IS2DOGUMTARIHI { get; set; }
        public string IS2DOGUMYERI { get; set; }
        public string IS2NUFUSSERISIRANO { get; set; }
        public string IS2ARACPLAKA { get; set; }
        public string IS2NUFUSKAYIT { get; set; }
        public string IS2DIGERSICILNO { get; set; }
        public string ORTUNVANI { get; set; }
        public string ORTADSOYAD { get; set; }
        public string ORTADRES { get; set; }
        public string ORTVERGIDAINO { get; set; }
        public string ORTBASLAMATARIHI { get; set; }
        public string ORTHISSEORANI { get; set; }
        public string ORTTICSICILNO { get; set; }
        public string ORTTELEFON1 { get; set; }
        public string ORTTELEFON2 { get; set; }
        public string ORTBABAADI { get; set; }
        public string ORTDOGUMTARIHI { get; set; }
        public string ORTDOGUMYERI { get; set; }
        public string ORTNUFUSSERISIRANO { get; set; }
        public string ORTARACPLAKA { get; set; }
        public string ORTNUFUSKAYIT { get; set; }
        public string ORTDIGERSICILNO { get; set; }
        public string OR2UNVANI { get; set; }
        public string OR2ADSOYAD { get; set; }
        public string OR2ADRES { get; set; }
        public string OR2VERGIDAINO { get; set; }
        public string OR2BASLAMATARIHI { get; set; }
        public string OR2HISSEORANI { get; set; }
        public string OR2TICSICILNO { get; set; }
        public string OR2TELEFON1 { get; set; }
        public string OR2TELEFON2 { get; set; }
        public string OR2BABAADI { get; set; }
        public string OR2DOGUMTARIHI { get; set; }
        public string OR2DOGUMYERI { get; set; }
        public string OR2NUFUSSERISIRANO { get; set; }
        public string OR2ARACPLAKA { get; set; }
        public string OR2NUFUSKAYIT { get; set; }
        public string OR2DIGERSICILNO { get; set; }
        public string MUHUNVANI { get; set; }
        public string MUHADSOYAD { get; set; }
        public string MUHADRES { get; set; }
        public string MUHVERGIDAINO { get; set; }
        public string MUHBASLAMATARIHI { get; set; }
        public string MUHHISSEORANI { get; set; }
        public string MUHTICSICILNO { get; set; }
        public string MUHTELEFON1 { get; set; }
        public string MUHTELEFON2 { get; set; }
        public string MUHBABAADI { get; set; }
        public string MUHDOGUMTARIHI { get; set; }
        public string MUHDOGUMYERI { get; set; }
        public string MUHNUFUSSERISIRANO { get; set; }
        public string MUHARACPLAKA { get; set; }
        public string MUHNUFUSKAYIT { get; set; }
        public string MUHDIGERSICILNO { get; set; }
        public string MU2UNVANI { get; set; }
        public string MU2ADSOYAD { get; set; }
        public string MU2ADRES { get; set; }
        public string MU2VERGIDAINO { get; set; }
        public string MU2BASLAMATARIHI { get; set; }
        public string MU2HISSEORANI { get; set; }
        public string MU2TICSICILNO { get; set; }
        public string MU2TELEFON1 { get; set; }
        public string MU2TELEFON2 { get; set; }
        public string MU2BABAADI { get; set; }
        public string MU2DOGUMTARIHI { get; set; }
        public string MU2DOGUMYERI { get; set; }
        public string MU2NUFUSSERISIRANO { get; set; }
        public string MU2ARACPLAKA { get; set; }
        public string MU2NUFUSKAYIT { get; set; }
        public string MU2DIGERSICILNO { get; set; }
        public string ISVTCKIMLIKNO { get; set; }
        public string ISV2TCKIMLIKNO { get; set; }
        public Nullable<bool> ISVUYRUK { get; set; }
        public Nullable<bool> ISV2UYRUK { get; set; }
        public Nullable<bool> ISVCINSIYET { get; set; }
        public Nullable<bool> ISV2CINSIYET { get; set; }
        public string ISVANNEADI { get; set; }
        public string ISV2ANNEADI { get; set; }
        public string ORTTCKIMLIKNO { get; set; }
        public string ORT2TCKIMLIKNO { get; set; }
        public Nullable<bool> ORTUYRUK { get; set; }
        public Nullable<bool> ORT2UYRUK { get; set; }
        public Nullable<bool> ORTCINSIYET { get; set; }
        public Nullable<bool> ORT2CINSIYET { get; set; }
        public string ORTANNEADI { get; set; }
        public string ORT2ANNEADI { get; set; }
        public string MUHTCKIMLIKNO { get; set; }
        public string MU2TCKIMLIKNO { get; set; }
        public Nullable<bool> MUHUYRUK { get; set; }
        public Nullable<bool> MU2UYRUK { get; set; }
        public Nullable<bool> MUHCINSIYET { get; set; }
        public Nullable<bool> MU2CINSIYET { get; set; }
        public string MUHANNEADI { get; set; }
        public string MU2ANNEADI { get; set; }
    }
}
