//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0111D0008TBLOTOISCILIKHAREKET
    {
        public int IND { get; set; }
        public Nullable<int> KAYITNO { get; set; }
        public Nullable<int> BELGENO { get; set; }
        public Nullable<int> BELGESATNO { get; set; }
        public Nullable<int> IZAHAT { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public Nullable<int> STOKTIPI { get; set; }
        public Nullable<int> BIRIMEX { get; set; }
        public Nullable<int> DEPO { get; set; }
        public Nullable<System.DateTime> BELGETARIH { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<bool> KLEIM { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<decimal> BFIYAT { get; set; }
        public Nullable<decimal> BIRIMMIKTAR { get; set; }
        public Nullable<decimal> ISK1 { get; set; }
        public Nullable<decimal> ISK2 { get; set; }
        public Nullable<decimal> KUR { get; set; }
        public Nullable<decimal> KDV { get; set; }
        public string STOKKODU { get; set; }
        public string MALINCINSI { get; set; }
        public string PARABIRIMI { get; set; }
        public string BIRIMADI { get; set; }
    }
}
