//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0111TBLITSOKUTULANKAREKODLISTESI
    {
        public int IND { get; set; }
        public Nullable<int> STOKIND { get; set; }
        public Nullable<int> BASLIKIND { get; set; }
        public Nullable<int> HAREKETIND { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<bool> ITSBILDIRIMI { get; set; }
        public string KAREKOD { get; set; }
        public string ITSKAREKOD { get; set; }
        public string WEBMESAJ { get; set; }
        public string PAKETKOD { get; set; }
    }
}
