//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0111D0013TBLTOPLUCARIBORDROHAREKET
    {
        public int IND { get; set; }
        public Nullable<int> EVRAKNO { get; set; }
        public Nullable<int> FIRMANO { get; set; }
        public Nullable<int> PORTFOYIND { get; set; }
        public Nullable<int> DURUM { get; set; }
        public Nullable<int> BELGELINK { get; set; }
        public Nullable<int> OLUSANBORDROBELGETIPI { get; set; }
        public Nullable<int> OLUSANBORDROBASLIKIND { get; set; }
        public Nullable<int> OLUSANBORDROHAREKETIND { get; set; }
        public Nullable<int> SEHIR { get; set; }
        public Nullable<int> BANKANO { get; set; }
        public Nullable<System.DateTime> VADE { get; set; }
        public Nullable<System.DateTime> KESIDETARIHI { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<decimal> BAKIYE { get; set; }
        public Nullable<decimal> ISTENENBAKIYE { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<decimal> KUR { get; set; }
        public string MUHHESAPKODU { get; set; }
        public string VERGIDAIRESI { get; set; }
        public string VERGINUMARASI { get; set; }
        public string TAKIPNO { get; set; }
        public string BANKAHESAPNO { get; set; }
        public string BELGENO { get; set; }
        public string KESIDEEDEN { get; set; }
        public string KESIDEYERI { get; set; }
        public string PARABIRIMI { get; set; }
        public string BANKANINSUBESI { get; set; }
    }
}
