//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0114TBLBEYKURUMVER
    {
        public int IND { get; set; }
        public string YILI { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<bool> SEC { get; set; }
        public Nullable<bool> YAZDIR { get; set; }
        public byte[] DATA { get; set; }
        public string BANKAAKTIFDIPNOT { get; set; }
        public string BANKAPASIFDIPNOT { get; set; }
        public string BANKANAZIMDIPNOT { get; set; }
        public string BANKAGELIRDIPNOT { get; set; }
        public string SIGORTAAKTIFDIPNOT { get; set; }
        public string SIGORTAPASIFDIPNOT { get; set; }
        public string SIGORTASOLODIPNOT { get; set; }
        public string TDHPAKTIFDIPNOT { get; set; }
        public string TDHPPASIFDIPNOT { get; set; }
        public string TDHPGELIRDIPNOT { get; set; }
        public string OFKAKTIFDIPNOT { get; set; }
        public string OFKPASIFDIPNOT { get; set; }
        public string OFKNAZIMDIPNOT { get; set; }
        public string OFKGELIRDIPNOT { get; set; }
        public string YATIRIMBILANCODIPNOT { get; set; }
        public string YATIRIMGELIRDIPNOT { get; set; }
        public string BANKAAKTIF { get; set; }
        public string BANKAPASIF { get; set; }
        public string BANKANAZIM { get; set; }
        public string BANKAGELIR { get; set; }
        public string SIGORTAAKTIF { get; set; }
        public string SIGORTAPASIF { get; set; }
        public string SIGORTASOLO { get; set; }
        public string TDHPAKTIF { get; set; }
        public string TDHPPASIF { get; set; }
        public string TDHPGELIR { get; set; }
        public string OFKAKTIF { get; set; }
        public string OFKPASIF { get; set; }
        public string OFKNAZIM { get; set; }
        public string OFKGELIR { get; set; }
        public string YATIRIMBILANCO { get; set; }
        public string YATIRIMGELIR { get; set; }
        public string DARMUKELLEF { get; set; }
        public string KESINTIYOLUYLA { get; set; }
        public string ISLETME { get; set; }
        public string YABANCIULKE { get; set; }
        public string DARMUKELLEFORTAKLAR { get; set; }
        public string KARDAGITIM { get; set; }
        public string YABANCIPARA { get; set; }
        public string KURUMORTAKLARI { get; set; }
        public string KURUMTRASNFERYURTDISI { get; set; }
        public string ORTULUSERMAYE { get; set; }
        public string TRANSFERFIYATLANDIRMASI { get; set; }
        public string TRANSFERILISKILIKISILER { get; set; }
        public string TRASNFERKISILERILISKINBILGILER { get; set; }
        public string TRANSFERMALIISLER { get; set; }
        public string KURUMTRANSFERYURTDISI { get; set; }
        public string TRANSFERKISILERILISKINBILGILER { get; set; }
        public string FINANSALAKTIF { get; set; }
        public string FINANSALAKTIFDIPNOT { get; set; }
        public string FINANSALPASIF { get; set; }
        public string FINANSALPASIFDIPNOT { get; set; }
        public string FINANSALNAZIM { get; set; }
        public string FINANSALNAZIMDIPNOT { get; set; }
        public string FINANSALGELIR { get; set; }
        public string FINANSALGELIRDIPNOT { get; set; }
        public string INDIRIMLIKURUMAR { get; set; }
        public string YURTDISIEGITIM { get; set; }
        public string YURTDISISAGLIK { get; set; }
        public string TEKNOLOJI { get; set; }
        public string NAKDISERMAYE { get; set; }
        public string ARGE { get; set; }
    }
}
