//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0129TBLMARKETANLASMAHAREKET
    {
        public int IND { get; set; }
        public Nullable<int> TYPE { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public Nullable<int> CRITERTYPE { get; set; }
        public Nullable<int> BASLIKIND { get; set; }
        public Nullable<int> VADE { get; set; }
        public Nullable<int> HAREKETIND { get; set; }
        public Nullable<int> CONTRACTNO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<bool> SELECTED { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<decimal> CRITER1 { get; set; }
        public Nullable<decimal> CRITER2 { get; set; }
        public Nullable<decimal> FIYATI { get; set; }
        public Nullable<decimal> MASRAF { get; set; }
        public Nullable<decimal> INDIRIM { get; set; }
        public Nullable<decimal> GERCEKTOPLAM { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
        public Nullable<decimal> KDVORANI { get; set; }
        public Nullable<decimal> KarMarji { get; set; }
        public Nullable<decimal> KDVDAHILNETFIYAT { get; set; }
        public Nullable<decimal> NETFIYAT { get; set; }
        public Nullable<decimal> CRITER3 { get; set; }
        public Nullable<decimal> CRITER4 { get; set; }
        public Nullable<decimal> RESULT1 { get; set; }
        public Nullable<decimal> RESULT2 { get; set; }
        public Nullable<decimal> RESULT3 { get; set; }
        public Nullable<decimal> RESULT4 { get; set; }
        public string BELGENO { get; set; }
        public string OZELKOD1 { get; set; }
        public string OZELKOD2 { get; set; }
        public string OZELKOD3 { get; set; }
        public string OZELKOD4 { get; set; }
    }
}
