//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0129TBLKEFILMUSCUZDAN
    {
        public int IND { get; set; }
        public Nullable<int> MUSTERINO { get; set; }
        public Nullable<int> KIMLIKTIPI { get; set; }
        public Nullable<System.DateTime> VERILISTARIHI { get; set; }
        public Nullable<System.DateTime> DOGUMTARIHI { get; set; }
        public string SERI { get; set; }
        public string TCKIMLIKNO { get; set; }
        public string NO { get; set; }
        public string BABAADI { get; set; }
        public string VERILISNEDENI { get; set; }
        public string KAYITNO { get; set; }
        public string ILCE { get; set; }
        public string MAHALLE { get; set; }
        public string CILTNO { get; set; }
        public string AILESIRANO { get; set; }
        public string SIRANO { get; set; }
        public string VERILDIGIYER { get; set; }
        public string ANAADI { get; set; }
        public string DOGUMYERI { get; set; }
        public string MEDENIHALI { get; set; }
        public string DINI { get; set; }
        public string IL { get; set; }
    }
}
