//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0129D0001TBLHESAP
    {
        public Nullable<short> SEVIYE { get; set; }
        public Nullable<decimal> BORC { get; set; }
        public Nullable<decimal> DBORC { get; set; }
        public Nullable<decimal> ALACAK { get; set; }
        public Nullable<decimal> GMIKTAR { get; set; }
        public Nullable<decimal> CMIKTAR { get; set; }
        public Nullable<decimal> DALACAK { get; set; }
        public string HESAPKODU { get; set; }
        public string ANAHESAP { get; set; }
        public string HESAPADI { get; set; }
        public string KOD5 { get; set; }
        public string KOD6 { get; set; }
        public string BIRIM { get; set; }
        public string PARABIRIMI { get; set; }
        public string KOD1 { get; set; }
        public string KOD2 { get; set; }
        public string KOD3 { get; set; }
        public string KOD4 { get; set; }
    }
}
