//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0127D0002TBLBELGELEMELINKS
    {
        public int IND { get; set; }
        public Nullable<int> KAYNAKBELGEIND { get; set; }
        public Nullable<int> KAYNAKBELGESATIRIND { get; set; }
        public Nullable<int> KAYNAKBELGETIPI { get; set; }
        public Nullable<int> HEDEFBELGEIND { get; set; }
        public Nullable<int> HEDEFBELGESATIRIND { get; set; }
        public Nullable<int> HEDEFBELGETIPI { get; set; }
        public Nullable<decimal> GIDEN { get; set; }
    }
}
