//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0127TBLUREMALIYETUNSURLARI
    {
        public int IND { get; set; }
        public Nullable<int> BIRIMNO { get; set; }
        public Nullable<int> TUR { get; set; }
        public Nullable<bool> ORANSAL { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public string KOD { get; set; }
        public string AD { get; set; }
        public string GIRISMUHKOD { get; set; }
        public string CIKISMUHKOD { get; set; }
    }
}
