//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0129D0001TBLMUHSTOKHESAPKODLARI
    {
        public int IND { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public string GIRIS { get; set; }
        public string CIKIS { get; set; }
        public string GIRISIADE { get; set; }
        public string CIKISIADE { get; set; }
        public string ALISKALEMISKONTOSU { get; set; }
        public string URETIMGIRIS { get; set; }
        public string URETIMCIKIS { get; set; }
        public string URETIMCIKISBORCLU { get; set; }
        public string SATISKALEMISKONTOSU { get; set; }
        public string ALISALTISKONTOSU { get; set; }
        public string SATISALTISKONTOSU { get; set; }
        public string SATILANMALMALIYETI { get; set; }
        public string MASRAF { get; set; }
        public string YURTDISI { get; set; }
        public string GIDERCESITKODU { get; set; }
    }
}
