//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0128D0003TBLRPTSATIR
    {
        public int IND { get; set; }
        public Nullable<int> RIND { get; set; }
        public Nullable<int> SIRANO { get; set; }
        public Nullable<int> YAZDIRILACAK { get; set; }
        public Nullable<bool> BOLD { get; set; }
        public Nullable<decimal> DEGER { get; set; }
        public Nullable<decimal> DEGER8 { get; set; }
        public Nullable<decimal> DEGER9 { get; set; }
        public Nullable<decimal> DEGER5 { get; set; }
        public Nullable<decimal> DEGER6 { get; set; }
        public Nullable<decimal> DEGER7 { get; set; }
        public Nullable<decimal> DEGER2 { get; set; }
        public Nullable<decimal> DEGER3 { get; set; }
        public Nullable<decimal> DEGER4 { get; set; }
        public string DEGERADI { get; set; }
        public string FORMUL { get; set; }
        public string FORMUL8 { get; set; }
        public string FORMUL9 { get; set; }
        public string FORMUL5 { get; set; }
        public string FORMUL6 { get; set; }
        public string FORMUL7 { get; set; }
        public string FORMUL2 { get; set; }
        public string FORMUL3 { get; set; }
        public string FORMUL4 { get; set; }
    }
}
