//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0127TBLPERDIZI1
    {
        public int IND { get; set; }
        public Nullable<int> SUBEIND { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string ACIKLAMA { get; set; }
        public string KISAAD { get; set; }
        public string AD1 { get; set; }
        public string AD2 { get; set; }
        public string SUBEAD { get; set; }
        public string ADRES { get; set; }
        public string SSKSICILNO { get; set; }
        public string ISVAD { get; set; }
        public string ISVSOYAD { get; set; }
    }
}
