//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0127D0002TBLMARKETETKILENENEVRAK
    {
        public int IND { get; set; }
        public Nullable<int> CONTRACTNO { get; set; }
        public Nullable<int> IZAHAT { get; set; }
        public Nullable<int> BELGEIND { get; set; }
        public Nullable<int> KESILENEVRAKIND { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<bool> MALIYETLENDIRME { get; set; }
        public string BELGENO { get; set; }
    }
}
