//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0129TBLOPTSTOK
    {
        public int IND { get; set; }
        public Nullable<int> STOKIND { get; set; }
        public Nullable<int> PARENTIND { get; set; }
        public Nullable<int> ORGTIP { get; set; }
        public Nullable<int> CAMTIP { get; set; }
        public Nullable<decimal> SPH { get; set; }
        public Nullable<decimal> CLY { get; set; }
        public Nullable<decimal> INCELIK { get; set; }
        public Nullable<decimal> AKS { get; set; }
        public Nullable<decimal> PUPILA { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<decimal> CAP { get; set; }
        public string ACIKLAMA { get; set; }
        public string MARKA { get; set; }
    }
}
