//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0127TBLMKTKARKASTANIM
    {
        public int IND { get; set; }
        public Nullable<int> KARKASSTOKNO { get; set; }
        public Nullable<int> FIRESTOKNO { get; set; }
        public Nullable<int> KEMIKSTOKNO { get; set; }
        public Nullable<int> DEPONO { get; set; }
        public Nullable<System.DateTime> SONMALIYETTARIHI { get; set; }
        public Nullable<decimal> KEMIKORANI { get; set; }
        public string CAPTION { get; set; }
        public string DEPOKODU { get; set; }
        public Nullable<int> KARKASBIRIMIND { get; set; }
        public Nullable<int> FIREBIRIMIND { get; set; }
        public Nullable<int> KEMIKBIRIMIND { get; set; }
    }
}
