//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0129TBLOZGIDER2
    {
        public int IND { get; set; }
        public Nullable<int> OZGIDERIND { get; set; }
        public Nullable<int> PERSONELIND { get; set; }
        public Nullable<decimal> KUMMAT { get; set; }
        public Nullable<decimal> HAZIRAN { get; set; }
        public Nullable<decimal> TEMMUZ { get; set; }
        public Nullable<decimal> AGUSTOS { get; set; }
        public Nullable<decimal> DAMGAVERGISI { get; set; }
        public Nullable<decimal> GELVER { get; set; }
        public Nullable<decimal> IADEGELIR { get; set; }
        public Nullable<decimal> SUBAT { get; set; }
        public Nullable<decimal> MART { get; set; }
        public Nullable<decimal> NISAN { get; set; }
        public Nullable<decimal> MAYIS { get; set; }
        public Nullable<decimal> KUMGV { get; set; }
        public Nullable<decimal> FISTOPLAM { get; set; }
        public Nullable<decimal> OGESASTUTAR { get; set; }
        public Nullable<decimal> OGYAPKISIM { get; set; }
        public Nullable<decimal> OGTUTAR { get; set; }
        public Nullable<decimal> OGKALAN { get; set; }
        public string SSKSICILNO { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
    }
}
