//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0129D0001TBLRESADISYON
    {
        public int IND { get; set; }
        public Nullable<int> KISISAYI { get; set; }
        public Nullable<int> FATURALASTI { get; set; }
        public Nullable<int> DEPO { get; set; }
        public Nullable<int> CIKTISAYISI { get; set; }
        public Nullable<int> MUTFAKCIKTISAYISI { get; set; }
        public Nullable<int> MASAKAYNAKKISI { get; set; }
        public Nullable<int> CARIIND { get; set; }
        public Nullable<int> MASAIND { get; set; }
        public Nullable<int> GARSONIND { get; set; }
        public Nullable<int> ANOTUIND { get; set; }
        public Nullable<int> BIRLESTI { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<System.DateTime> GELSAAT { get; set; }
        public Nullable<System.DateTime> GIDSAAT { get; set; }
        public Nullable<bool> IKRAM { get; set; }
        public Nullable<decimal> ISKONTO { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<decimal> ODENEN { get; set; }
        public string FISNO { get; set; }
        public string MASAKAYNAKNO { get; set; }
        public string FISNOTU { get; set; }
        public string MUSTERIAD { get; set; }
    }
}
