//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0129TBLTRMBAYIBILGI
    {
        public int IND { get; set; }
        public Nullable<System.DateTime> IZINTARIH { get; set; }
        public string ADISOYADI { get; set; }
        public string ADRESI { get; set; }
        public string IZINNO { get; set; }
        public string VERGIDAIRESI { get; set; }
        public string VERGINO { get; set; }
        public string TELEFON { get; set; }
        public string BOLGE { get; set; }
    }
}
