//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0127D0002TBLYANSIT
    {
        public int IND { get; set; }
        public Nullable<bool> SELECTED { get; set; }
        public Nullable<decimal> ORAN { get; set; }
        public string HESAPKODU { get; set; }
        public string HESAPADI { get; set; }
        public string YHESAPKODU { get; set; }
        public string YHESAPADI { get; set; }
        public string KHESAPKODU { get; set; }
        public string KHESAPADI { get; set; }
    }
}
