//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0128D0001TBLAVKAVUKATTAHSILATLARI
    {
        public int IND { get; set; }
        public Nullable<int> MUSTERINO { get; set; }
        public Nullable<int> AVUKATNO { get; set; }
        public Nullable<int> BORDROHAREKETIND { get; set; }
        public Nullable<int> BORDROIND { get; set; }
        public Nullable<int> BORDROIZAHAT { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<System.DateTime> SIRALAMATARIHI { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public string ACIKLAMA { get; set; }
        public string TAKIPNO { get; set; }
    }
}
