//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0127TBLCRMGORUSMEBASLIK
    {
        public int IND { get; set; }
        public Nullable<int> ALTKARTNO { get; set; }
        public Nullable<int> KONSOLIDE { get; set; }
        public Nullable<int> PERSONELREF { get; set; }
        public Nullable<int> GORUSMESEKLIREF { get; set; }
        public Nullable<int> GORUSMESONUCUREF { get; set; }
        public Nullable<int> CRMMUSTERIKARTIREF { get; set; }
        public Nullable<int> GORUSMEBELGETIPI { get; set; }
        public Nullable<System.DateTime> GORUSMETARIHI { get; set; }
        public Nullable<System.DateTime> GORUSMEBITISTARIHI { get; set; }
        public string SINIRSIZ3 { get; set; }
        public string SINIRSIZ4 { get; set; }
        public string SINIRSIZ5 { get; set; }
        public string SINIRSIZ1 { get; set; }
        public string SINIRSIZ2 { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<bool> IPTAL { get; set; }
        public Nullable<bool> ETIKET17 { get; set; }
        public Nullable<bool> ETIKET18 { get; set; }
        public Nullable<bool> ETIKET19 { get; set; }
        public Nullable<bool> ETIKET20 { get; set; }
        public Nullable<bool> ETIKET16 { get; set; }
        public Nullable<bool> ETIKET6 { get; set; }
        public Nullable<bool> ETIKET7 { get; set; }
        public Nullable<bool> ETIKET8 { get; set; }
        public Nullable<bool> ETIKET9 { get; set; }
        public Nullable<bool> ETIKET10 { get; set; }
        public string ETIKET1 { get; set; }
        public string ETIKET2 { get; set; }
        public string ETIKET3 { get; set; }
        public string ETIKET4 { get; set; }
        public string ETIKET5 { get; set; }
        public string PB { get; set; }
        public string ETIKET23 { get; set; }
        public string ETIKET24 { get; set; }
        public string ETIKET25 { get; set; }
        public string ETIKET21 { get; set; }
        public string ETIKET22 { get; set; }
        public string ETIKET11 { get; set; }
        public string ETIKET12 { get; set; }
        public string ETIKET13 { get; set; }
        public string ETIKET14 { get; set; }
        public string ETIKET15 { get; set; }
        public string BELGENO { get; set; }
        public string UID { get; set; }
    }
}
