//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0128TBLCBBILDIRGE
    {
        public int IND { get; set; }
        public Nullable<int> YIL { get; set; }
        public Nullable<int> AY { get; set; }
        public Nullable<int> SUBEIND { get; set; }
        public Nullable<int> PERSAYYABANCIKADIN { get; set; }
        public Nullable<int> PERSAYGENC { get; set; }
        public Nullable<int> PERSAYCIRAK { get; set; }
        public Nullable<int> PERSAYSTAJER { get; set; }
        public Nullable<int> PERSAYYABANCIERKEK { get; set; }
        public Nullable<int> VEKILNUFUSIL { get; set; }
        public Nullable<int> VEKILIL { get; set; }
        public Nullable<int> ISVNUFUSIL { get; set; }
        public Nullable<int> ISVIL { get; set; }
        public Nullable<int> PERSAYTOPLAM { get; set; }
        public Nullable<int> PERSAYERKEK { get; set; }
        public Nullable<int> PERSAYKADIN { get; set; }
        public Nullable<int> PERSAYCOCUK { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<System.DateTime> VEKILDOGUMTARIHI { get; set; }
        public Nullable<System.DateTime> ISVDOGUMTARIHI { get; set; }
        public Nullable<System.DateTime> BASLAMATARIHI { get; set; }
        public Nullable<System.DateTime> BITISTARIHI { get; set; }
        public Nullable<System.DateTime> ISCICALISTIRMATARIHI { get; set; }
        public Nullable<bool> SECIM { get; set; }
        public Nullable<bool> YAZDIRILDI { get; set; }
        public string ACIKLAMA { get; set; }
        public string VEKILVERGINO { get; set; }
        public string ISKURNO { get; set; }
        public string VEKILNUFSAYFANO { get; set; }
        public string ISVUYRUGU { get; set; }
        public string ISVVERGIDAIRESI { get; set; }
        public string ISVVERGINO { get; set; }
        public string VEKILUYRUGU { get; set; }
        public string VEKILVERGIDAIRESI { get; set; }
        public string VEKILARACPLAKA { get; set; }
        public string VEKILNUFUSILCE { get; set; }
        public string VEKILNUFUSMAHKOY { get; set; }
        public string VEKILNUFSIRANO { get; set; }
        public string VEKILNUFAILESIRANO { get; set; }
        public string VEKILFAX { get; set; }
        public string VEKILBABAADI { get; set; }
        public string VEKILANAADI { get; set; }
        public string VEKILDOGUMYERI { get; set; }
        public string VEKILNUFUSSERINO { get; set; }
        public string VEKILPOSTAKOD { get; set; }
        public string VEKILALANKODU1 { get; set; }
        public string VEKILTELEFON1 { get; set; }
        public string VEKILALANKODU2 { get; set; }
        public string VEKILTELEFON2 { get; set; }
        public string VEKILALANKODU3 { get; set; }
        public string ISVNUFSAYFANO { get; set; }
        public string VEKILAD { get; set; }
        public string VEKILSOYAD { get; set; }
        public string VEKILADRES { get; set; }
        public string VEKILILCE { get; set; }
        public string ISVARACPLAKA { get; set; }
        public string ISVNUFUSILCE { get; set; }
        public string ISVNUFUSMAHKOY { get; set; }
        public string ISVNUFSIRANO { get; set; }
        public string ISVNUFAILESIRANO { get; set; }
        public string ISVFAX { get; set; }
        public string ISVBABAADI { get; set; }
        public string ISVANAADI { get; set; }
        public string ISVDOGUMYERI { get; set; }
        public string ISVNUFUSSERINO { get; set; }
        public string ISVPOSTAKOD { get; set; }
        public string ISVALANKODU1 { get; set; }
        public string ISVTELEFON1 { get; set; }
        public string ISVALANKODU2 { get; set; }
        public string ISVTELEFON2 { get; set; }
        public string ISVALANKODU3 { get; set; }
        public string IHALEADRES { get; set; }
        public string ISVAD { get; set; }
        public string ISVSOYAD { get; set; }
        public string ISVADRES { get; set; }
        public string ISVILCE { get; set; }
        public string VERGINO { get; set; }
        public string ORTAKSAYISI { get; set; }
        public string TSVKAYITNO { get; set; }
        public string ENAZHADDI { get; set; }
        public string ENÇOKHADDI { get; set; }
        public string IHALEUNVAN { get; set; }
        public string TABIOLDUGUSEKTOR { get; set; }
        public string TSOKAYITNO { get; set; }
        public string VERGIDAIRESI { get; set; }
        public string TELEFON2 { get; set; }
        public string ALANKODU3 { get; set; }
        public string FAX { get; set; }
        public string CALISMAKONUSU { get; set; }
        public string SSKSICILNO { get; set; }
        public string ISINFALIYETSURESI { get; set; }
        public string IL { get; set; }
        public string ILCE { get; set; }
        public string POSTAKOD { get; set; }
        public string ALANKODU1 { get; set; }
        public string TELEFON1 { get; set; }
        public string ALANKODU2 { get; set; }
        public string CBSICILNO1 { get; set; }
        public string CBSICILNO2 { get; set; }
        public string CBSICILNO3 { get; set; }
        public string CBSICILNO4 { get; set; }
        public string ADRES { get; set; }
        public string AD1 { get; set; }
        public string AD2 { get; set; }
    }
}
