//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0127D0002TBLVISAGIRIS
    {
        public int IND { get; set; }
        public Nullable<int> LN { get; set; }
        public Nullable<int> BANKA { get; set; }
        public Nullable<int> PORTFOYNO { get; set; }
        public Nullable<int> FIRMANO { get; set; }
        public Nullable<int> EVRAKNO { get; set; }
        public Nullable<System.DateTime> ISLEMTARIHI { get; set; }
        public Nullable<System.DateTime> KRESONKULTAR { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<decimal> TAKSITSAYISI { get; set; }
        public string BELGENO { get; set; }
        public string KARTADI { get; set; }
        public string BANKAADI { get; set; }
        public string KREKARTNO { get; set; }
        public string ONAYKODU { get; set; }
    }
}
