//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0127D0002TBLTUISEMRIBASLIK
    {
        public int IND { get; set; }
        public Nullable<int> RECETENO { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public Nullable<int> STOKTIPI { get; set; }
        public Nullable<int> SIPARISFIRMANO { get; set; }
        public Nullable<System.DateTime> SIPARISTARIHI { get; set; }
        public Nullable<System.DateTime> TERMINTARIHI { get; set; }
        public Nullable<System.DateTime> OLUSTURMATARIHI { get; set; }
        public string ACIKLAMA2 { get; set; }
        public string STOKKODU { get; set; }
        public string MALINCINSI { get; set; }
        public string KOD1 { get; set; }
        public string SIPARISBELGENO { get; set; }
        public string SIPARISFIRMAADI { get; set; }
        public string OZELKOD1 { get; set; }
        public string OZELKOD2 { get; set; }
        public string OZELKOD3 { get; set; }
        public string ACIKLAMA { get; set; }
        public string EVRAKNO { get; set; }
        public string SIPARISFIRMAKODU { get; set; }
        public Nullable<bool> URETIMTAMAMLANDI { get; set; }
    }
}
