//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0129TBLKRDTADILATFISLERI
    {
        public int IND { get; set; }
        public Nullable<int> ISLEMGRUBUIND { get; set; }
        public Nullable<int> PERSONELNO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<System.DateTime> TESLIMTARIHI { get; set; }
        public Nullable<bool> TESLIMEDILDI { get; set; }
        public Nullable<bool> TADILATTANDONDU { get; set; }
        public Nullable<decimal> FIYATI { get; set; }
        public string BELGENO { get; set; }
        public string MUSTERIADISOYADI { get; set; }
        public string ISLEMIYAPANKISI { get; set; }
        public string TELEFON { get; set; }
        public string ISLEMGRUBUACIKLAMA { get; set; }
        public string MALINCINSI { get; set; }
        public string GSM { get; set; }
        public string ISLEMTIPI { get; set; }
        public string ACIKLAMA { get; set; }
        public string SUBEADI { get; set; }
        public string KASAADI { get; set; }
        public string YAPILACAKISLEM { get; set; }
        public string STOKKODU { get; set; }
    }
}
