//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0127D0002TBLITSMIADLISTESI
    {
        public int IND { get; set; }
        public Nullable<int> STOKIND { get; set; }
        public Nullable<int> BIRIMEX { get; set; }
        public Nullable<int> BASLIKIND { get; set; }
        public Nullable<int> HAREKETIND { get; set; }
        public Nullable<System.DateTime> SONKULLANMATARIHI_ { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
    }
}
