//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0129TBLPERISGUCUCIZELGE
    {
        public int IND { get; set; }
        public Nullable<int> SUBEIND { get; set; }
        public Nullable<int> BORDROIND { get; set; }
        public Nullable<int> YIL { get; set; }
        public Nullable<int> AY { get; set; }
        public Nullable<int> ISEALTERERKEK { get; set; }
        public Nullable<int> ISEALTERKADIN { get; set; }
        public Nullable<int> ISTENAYTERERKEK { get; set; }
        public Nullable<int> ISTENAYTERKADIN { get; set; }
        public Nullable<int> AYSONUTERERKEK { get; set; }
        public Nullable<int> AYSONUTERKADIN { get; set; }
        public Nullable<int> ISTENAYHUKERKEK { get; set; }
        public Nullable<int> ISTENAYHUKKADIN { get; set; }
        public Nullable<int> AYSONUHUKERKEK { get; set; }
        public Nullable<int> AYSONUHUKKADIN { get; set; }
        public Nullable<int> GATERERKEK { get; set; }
        public Nullable<int> GATERKADIN { get; set; }
        public Nullable<int> AYSONUOZERKEK { get; set; }
        public Nullable<int> AYSONUOZKADIN { get; set; }
        public Nullable<int> GAHUKERKEK { get; set; }
        public Nullable<int> GAHUKKADIN { get; set; }
        public Nullable<int> ISEALHUKERKEK { get; set; }
        public Nullable<int> ISEALHUKKADIN { get; set; }
        public Nullable<int> GAOZERKEK { get; set; }
        public Nullable<int> GAOZKADIN { get; set; }
        public Nullable<int> ISEALOZERKEK { get; set; }
        public Nullable<int> ISEALOZKADIN { get; set; }
        public Nullable<int> ISTENAYOZERKEK { get; set; }
        public Nullable<int> ISTENAYOZKADIN { get; set; }
        public Nullable<int> ISTENAYGECICIERKEK { get; set; }
        public Nullable<int> ISTENAYGECICIKADIN { get; set; }
        public Nullable<int> AYSONUDAIMIERKEK { get; set; }
        public Nullable<int> AYSONUDAIMIKADIN { get; set; }
        public Nullable<int> AYSONUGECICIERKEK { get; set; }
        public Nullable<int> AYSONUGECICIKADIN { get; set; }
        public Nullable<int> ISEALDAIMIERKEK { get; set; }
        public Nullable<int> ISEALDAIMIKADIN { get; set; }
        public Nullable<int> ISEALGECICIERKEK { get; set; }
        public Nullable<int> ISEALGECICIKADIN { get; set; }
        public Nullable<int> ISTENAYDAIMIERKEK { get; set; }
        public Nullable<int> ISTENAYDAIMIKADIN { get; set; }
        public Nullable<int> GACALDAIMIERKEK { get; set; }
        public Nullable<int> GACALDAIMIKADIN { get; set; }
        public Nullable<int> GACALGECICIERKEK { get; set; }
        public Nullable<int> GACALGECICIKADIN { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<bool> SECIM { get; set; }
        public Nullable<bool> EGITIMAL { get; set; }
        public Nullable<bool> CIRAKLAZIM { get; set; }
        public Nullable<bool> ORTAKKURS { get; set; }
        public Nullable<bool> YAZDIRILDI { get; set; }
        public string ACIKLAMA { get; set; }
        public string ISGUCUDEGISIM { get; set; }
        public string GUCMESLEK1 { get; set; }
        public string GUCMESLEK2 { get; set; }
        public string GUCMESLEK3 { get; set; }
        public string GUCMESLEK4 { get; set; }
        public string GUCMESLEK5 { get; set; }
    }
}
