//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0129D0001TBLTUISEMRIGIRDI
    {
        public int IND { get; set; }
        public Nullable<int> BASLIKIND { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public Nullable<int> RECETEGIRDIIND { get; set; }
        public Nullable<decimal> RECETEBIRIMMIKTAR { get; set; }
        public Nullable<decimal> BIRIMFIYAT { get; set; }
        public Nullable<decimal> EKMIKTAR { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public string STOKKODU { get; set; }
        public string MALINCINSI { get; set; }
        public string MALZEMEKONUMU { get; set; }
        public string RENKKODU { get; set; }
        public string BEDENKODU { get; set; }
        public string MALZEMETIPI { get; set; }
    }
}
