//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0127D0002TBLCARIGENELHAREKET
    {
        public int IND { get; set; }
        public Nullable<int> FIRMANO { get; set; }
        public Nullable<int> BELGEIND { get; set; }
        public Nullable<int> ISLEMIND { get; set; }
        public Nullable<int> BELGEIZAHAT { get; set; }
        public Nullable<int> TAHSILLINK { get; set; }
        public Nullable<int> ISLEMIZAHAT { get; set; }
        public Nullable<int> BELGELINK { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<System.DateTime> VADE { get; set; }
        public Nullable<System.DateTime> SIRALAMATARIHI { get; set; }
        public Nullable<bool> CONVERTED { get; set; }
        public Nullable<bool> IPTAL { get; set; }
        public Nullable<bool> GECIKMEHESAPLA { get; set; }
        public Nullable<decimal> KUR { get; set; }
        public Nullable<decimal> BASLIKKURU { get; set; }
        public Nullable<decimal> SIRALAMATARIHIEX { get; set; }
        public Nullable<decimal> BORC { get; set; }
        public Nullable<decimal> ALACAK { get; set; }
        public Nullable<decimal> AYLIKVADE { get; set; }
        public string PARABIRIMI { get; set; }
        public string BASLIKPARABIRIMI { get; set; }
        public string ACIKLAMA { get; set; }
        public string ISLEMNO { get; set; }
        public string BELGENO { get; set; }
    }
}
