//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0128TBLORDERMANENVANTERDETAYI
    {
        public int IND { get; set; }
        public Nullable<int> DEPOIND { get; set; }
        public Nullable<int> STOKIND { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<decimal> MALFAZLASI { get; set; }
        public string DEPOKODU { get; set; }
        public string QUID { get; set; }
    }
}
