//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0129TBLUCRBORDRO
    {
        public int IND { get; set; }
        public Nullable<int> PERSONELGUN { get; set; }
        public Nullable<int> AILEGUN { get; set; }
        public Nullable<int> IHBARSURE3 { get; set; }
        public Nullable<int> IHBARORAN3 { get; set; }
        public Nullable<int> IHBARORAN4 { get; set; }
        public Nullable<int> MUHASEBEIND { get; set; }
        public Nullable<int> IHBARSURE1 { get; set; }
        public Nullable<int> IHBARORAN1 { get; set; }
        public Nullable<int> IHBARSURE2 { get; set; }
        public Nullable<int> IHBARORAN2 { get; set; }
        public Nullable<int> AY { get; set; }
        public Nullable<int> YIL { get; set; }
        public Nullable<int> SUBEIND { get; set; }
        public Nullable<int> PARAMETREIND { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<bool> YAZDIRILDI { get; set; }
        public Nullable<bool> SECIM { get; set; }
        public Nullable<bool> ISLETMEENTEGRATED { get; set; }
        public Nullable<decimal> OZELSIGORTAORANI2 { get; set; }
        public Nullable<decimal> OZELSIGORTAORANI { get; set; }
        public Nullable<decimal> ASGARIGECIMMATRAHI { get; set; }
        public Nullable<decimal> ASGARIGECIMCOCUK3 { get; set; }
        public Nullable<decimal> ONALTIYASSIGORTATABANI { get; set; }
        public Nullable<decimal> ASGARIGECIMPERSONEL { get; set; }
        public Nullable<decimal> ASGARIGECIMES { get; set; }
        public Nullable<decimal> ASGARIGECIMCOCUK1 { get; set; }
        public Nullable<decimal> ASGARIGECIMCOCUK2 { get; set; }
        public Nullable<decimal> OGORAN2 { get; set; }
        public Nullable<decimal> OGORAN3 { get; set; }
        public Nullable<decimal> OGDAMGAORAN { get; set; }
        public Nullable<decimal> IADEDAMGAORAN { get; set; }
        public Nullable<decimal> OGDILIM1B { get; set; }
        public Nullable<decimal> OGDILIM2A { get; set; }
        public Nullable<decimal> OGDILIM2B { get; set; }
        public Nullable<decimal> OGDILIM3A { get; set; }
        public Nullable<decimal> OGDILIM3B { get; set; }
        public Nullable<decimal> OGORAN1 { get; set; }
        public Nullable<decimal> SSKTABANFARKI { get; set; }
        public Nullable<decimal> OGDILIM1A { get; set; }
        public Nullable<decimal> FAZLACALHT { get; set; }
        public Nullable<decimal> FAZLACALFC { get; set; }
        public Nullable<decimal> FAZLACALGT { get; set; }
        public Nullable<decimal> KIDEMTAVAN { get; set; }
        public Nullable<decimal> MALULLUKISCI { get; set; }
        public Nullable<decimal> MALULLUKISVEREN { get; set; }
        public Nullable<decimal> DESTEKSISCI { get; set; }
        public Nullable<decimal> DESTEKSISVEREN { get; set; }
        public Nullable<decimal> SIGORTATABANI { get; set; }
        public Nullable<decimal> SIGORTATAVANI { get; set; }
        public Nullable<decimal> GELIRVARTIS5 { get; set; }
        public Nullable<decimal> GELIRVARTIS6 { get; set; }
        public Nullable<decimal> HASTALIKISCI { get; set; }
        public Nullable<decimal> HASTALIKISVEREN { get; set; }
        public Nullable<decimal> CIRAKHASISCI { get; set; }
        public Nullable<decimal> CIRAKHASISVEREN { get; set; }
        public Nullable<decimal> MALUL3 { get; set; }
        public Nullable<decimal> GELIRVARTIS1 { get; set; }
        public Nullable<decimal> GELIRVARTIS2 { get; set; }
        public Nullable<decimal> GELIRVARTIS3 { get; set; }
        public Nullable<decimal> GELIRVARTIS4 { get; set; }
        public Nullable<decimal> AVANS { get; set; }
        public Nullable<decimal> MALUL1 { get; set; }
        public Nullable<decimal> MALUL2 { get; set; }
        public Nullable<decimal> CALISILMAYANRESMITATIL { get; set; }
        public Nullable<decimal> CALISILANRESMITATIL { get; set; }
        public Nullable<decimal> OZELINDIRIM { get; set; }
        public Nullable<decimal> YEMEKINDIRIMI { get; set; }
        public Nullable<decimal> ISKAZALARIPRIMIORANI { get; set; }
        public Nullable<decimal> YEVMIYE { get; set; }
        public Nullable<decimal> ISVERENSPRIMYUZDE { get; set; }
        public Nullable<decimal> DAMGAVBINDE { get; set; }
        public Nullable<decimal> VERGIIADEYUZDE { get; set; }
        public Nullable<decimal> CALISILANGUN { get; set; }
        public Nullable<decimal> CALISILMAYANHAFTATATILI { get; set; }
        public Nullable<decimal> CALISILANHAFTATATILI { get; set; }
        public Nullable<decimal> HAFTALIKSYUZDE { get; set; }
        public Nullable<decimal> CIRAKSYUZDE { get; set; }
        public Nullable<decimal> MALULSYUZDE { get; set; }
        public Nullable<decimal> ISSIZLIKISCIYUZDE { get; set; }
        public Nullable<decimal> ISSIZLIKISVERENYUZDE { get; set; }
        public Nullable<decimal> ISCISPRIMYUZDE { get; set; }
        public Nullable<decimal> GELIRVYUZDE5 { get; set; }
        public Nullable<decimal> GELIRVDILIM6 { get; set; }
        public Nullable<decimal> GELIRVYUZDE6 { get; set; }
        public Nullable<decimal> GUNLUKSIGORTATABANI { get; set; }
        public Nullable<decimal> GUNLUKSIGORTATAVANI { get; set; }
        public Nullable<decimal> ANALIKSYUZDE { get; set; }
        public Nullable<decimal> GELIRVYUZDE2 { get; set; }
        public Nullable<decimal> GELIRVDILIM3 { get; set; }
        public Nullable<decimal> GELIRVYUZDE3 { get; set; }
        public Nullable<decimal> GELIRVDILIM4 { get; set; }
        public Nullable<decimal> GELIRVYUZDE4 { get; set; }
        public Nullable<decimal> GELIRVDILIM5 { get; set; }
        public Nullable<decimal> GELIRVDILIM1 { get; set; }
        public Nullable<decimal> GELIRVYUZDE1 { get; set; }
        public Nullable<decimal> GELIRVDILIM2 { get; set; }
        public string SUBEAD { get; set; }
        public string ADRES { get; set; }
        public string TEHLIKEDERECESI { get; set; }
        public string IL { get; set; }
        public string PKODUARTIRMA { get; set; }
        public string OGPERIYOD { get; set; }
        public string CALSEKLI { get; set; }
        public string YILAY { get; set; }
        public string BORDROTIP { get; set; }
        public string ACIKLAMA { get; set; }
        public string ILCE { get; set; }
        public string POSTAKOD { get; set; }
        public string VERGIDAIRESI { get; set; }
        public string VERGINO { get; set; }
        public string SSKSICILNO { get; set; }
        public string KISAAD { get; set; }
    }
}
