//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0127TBLPDONEM
    {
        public int IND { get; set; }
        public Nullable<int> YIL { get; set; }
        public Nullable<int> AY { get; set; }
        public Nullable<int> SUBEIND { get; set; }
        public string ISCICIKIS { get; set; }
        public string ISCIGIRIS { get; set; }
        public string DORTAYSGBLD { get; set; }
        public string AYSGBLD { get; set; }
        public string BORDRO { get; set; }
        public string PUANTAJ { get; set; }
    }
}
