//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0127TBLUREANLIKISEMRIBASLIK
    {
        public int IND { get; set; }
        public Nullable<int> MAMULDEPOIND { get; set; }
        public Nullable<int> HAMMADDEDEPOIND { get; set; }
        public Nullable<int> USERIND { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<System.DateTime> ISLEMTARIHI { get; set; }
        public Nullable<bool> IPTAL { get; set; }
        public string RECETENO { get; set; }
        public string RECETEADI { get; set; }
        public string OZELKOD1 { get; set; }
        public string OZELKOD2 { get; set; }
        public string OZELKOD3 { get; set; }
        public string OZELKOD4 { get; set; }
        public string OZELKOD5 { get; set; }
        public string OZELKOD6 { get; set; }
        public string OZELKOD7 { get; set; }
        public string OZELKOD8 { get; set; }
        public string OZELKOD9 { get; set; }
    }
}
