//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0129D0001TBLTRMCIKBASLIK
    {
        public int IND { get; set; }
        public Nullable<int> CARIREF { get; set; }
        public Nullable<int> CONVERTEDTIP { get; set; }
        public Nullable<int> CONVERTEDNO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<bool> DEVIRFISI { get; set; }
        public string KABULNO { get; set; }
        public string KOD1 { get; set; }
        public string KOD2 { get; set; }
        public string KOD3 { get; set; }
        public string YETISTIRDIGIURUN { get; set; }
        public string ARAZIDURUMU { get; set; }
    }
}
