//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0129D0001TBLRESPUSULA
    {
        public int IND { get; set; }
        public Nullable<int> PUSULADURUM { get; set; }
        public Nullable<int> FATURABELGENO { get; set; }
        public Nullable<int> BORDROBELGENO { get; set; }
        public Nullable<int> EXADISYONNO { get; set; }
        public Nullable<int> LINKPUSULANO { get; set; }
        public Nullable<int> CARINO { get; set; }
        public Nullable<int> ADISYONNO { get; set; }
        public Nullable<bool> ENTEGRE { get; set; }
        public Nullable<decimal> FATURATUTAR { get; set; }
        public Nullable<decimal> FATURAODENEN { get; set; }
        public string PKODU { get; set; }
        public string MUSTERIAD { get; set; }
        public string EXPKODU { get; set; }
    }
}
