//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0127D0002TBLRESMUTFAKSIPARIS
    {
        public int IND { get; set; }
        public Nullable<int> YIND { get; set; }
        public Nullable<int> HAREKETIND { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public Nullable<int> ADISYONTIPI { get; set; }
        public Nullable<System.DateTime> GELISTARIHI { get; set; }
        public Nullable<System.DateTime> TAMAMLANMATARIHI { get; set; }
        public Nullable<bool> TAMAMLANDI { get; set; }
        public Nullable<bool> IPTAL { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public string LINE1 { get; set; }
        public string LINE2 { get; set; }
        public string YAZICIPORT { get; set; }
    }
}
