//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0127D0002TBLCARIKARTGIDERCESITKODLARI
    {
        public int IND { get; set; }
        public Nullable<int> FIRMANO { get; set; }
        public string CESITKODU { get; set; }
        public string ACIKLAMA { get; set; }
    }
}
