//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0128TBLPERKIBRISISEGIRIS
    {
        public int IND { get; set; }
        public Nullable<int> PERSONELIND { get; set; }
        public Nullable<int> SUBEIND { get; set; }
        public Nullable<int> AY { get; set; }
        public Nullable<int> YIL { get; set; }
        public Nullable<System.DateTime> ISEGIRISTARIHI { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<System.DateTime> DOGUMTARIHI { get; set; }
        public string ACIKLAMA { get; set; }
        public string IHTIYATSANDIKNO { get; set; }
        public string KIMLIKNO { get; set; }
        public string TCKIMLIKNO { get; set; }
        public string ISYERIUNVAN { get; set; }
        public string ISYERIMESLEK { get; set; }
        public string ISYERIADRES { get; set; }
        public string ISYERITELEFON { get; set; }
        public string ADRES { get; set; }
        public string TELEFONNO { get; set; }
        public string MESLEGI { get; set; }
        public string ISYERISICILNO { get; set; }
        public string DOGUMYERI { get; set; }
        public string ESKIMLIKNO { get; set; }
        public string ESADI { get; set; }
        public string BABAADI { get; set; }
        public string ANNEADI { get; set; }
        public string PASAPORTNO { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string CINSIYET { get; set; }
        public string MEDENIHAL { get; set; }
        public string UYRUGU { get; set; }
    }
}
