//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0127D0002VFATURAOZELKODLARI
    {
        public int IND { get; set; }
        public Nullable<short> BELGETIPI { get; set; }
        public Nullable<int> FIRMANO { get; set; }
        public string IL { get; set; }
        public string OZELKOD4 { get; set; }
        public string OZELKOD3 { get; set; }
    }
}
