//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0127D0002TBLMOBSIPARISBASLIK
    {
        public int IND { get; set; }
        public Nullable<int> FIRMANO { get; set; }
        public Nullable<int> TASIYICIMIKTAR { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<bool> EDT { get; set; }
        public Nullable<decimal> HACIMKATSAYI { get; set; }
        public Nullable<decimal> HACIM { get; set; }
        public Nullable<decimal> GUC { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<decimal> DETAYMIKTAR { get; set; }
        public string FIRMAKODU { get; set; }
        public string FIRMAADI { get; set; }
        public string OZELKOD { get; set; }
        public string ACIKLAMA { get; set; }
        public string BASLIKNO { get; set; }
        public string OZELKOD1 { get; set; }
        public string NOT1 { get; set; }
        public string NOT2 { get; set; }
        public string SIPARISNO { get; set; }
        public string TASIYICIADI { get; set; }
    }
}
