//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0128D0001TBLMASRAFFATURALARI
    {
        public int IND { get; set; }
        public Nullable<int> FATURANO { get; set; }
        public Nullable<int> FATURATIPI { get; set; }
        public Nullable<int> BELGEIND { get; set; }
        public Nullable<int> BELGETIPI { get; set; }
        public Nullable<int> ALISANLASMASINO { get; set; }
        public Nullable<int> ETKILENENFATURASAYISI { get; set; }
        public Nullable<bool> GIRIS { get; set; }
        public Nullable<decimal> INDIRIMTUTARI { get; set; }
        public Nullable<decimal> YANSIYACAKTUTAR { get; set; }
        public Nullable<int> HAREKETIND { get; set; }
        public Nullable<int> FATURAHAREKETIND { get; set; }
    }
}
