//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAKSISEMRISAATLIKKALITEKONTROL
    {
        public int IND { get; set; }
        public Nullable<int> BASLIKNO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<decimal> IHRACAT { get; set; }
        public Nullable<decimal> ISKARTA { get; set; }
        public Nullable<decimal> KUCUKURUN { get; set; }
        public Nullable<decimal> BUYUKURUN { get; set; }
        public byte[] KONTROLLISTESI { get; set; }
        public string GENELSONUC { get; set; }
    }
}
