//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAKSISEMRIBASLIK
    {
        public int IND { get; set; }
        public Nullable<int> MUSTERINO { get; set; }
        public string MUSTERIKODU { get; set; }
        public string SIPARISNO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string MUSTERISIPARISNO { get; set; }
        public string SETDERECESI { get; set; }
        public Nullable<int> PERSONELNO { get; set; }
        public string PERSONELKODU { get; set; }
        public string ISEMRINO { get; set; }
        public Nullable<int> OZELSARTLAR { get; set; }
        public Nullable<bool> SAATLIKKABUL { get; set; }
        public Nullable<bool> SAATLIKRED { get; set; }
        public Nullable<bool> SAATLIKONAY { get; set; }
    }
}
