//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAKSSATINALMABASLIK
    {
        public int IND { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string ANLASMANO { get; set; }
        public Nullable<int> ANLASMAMUSTERINO { get; set; }
        public Nullable<System.DateTime> ANLASMATARIH { get; set; }
        public Nullable<int> ANLASMASATICINO { get; set; }
        public Nullable<int> ANLASMAALICINO { get; set; }
        public string ANLASMAISKARTAKIMEAIT { get; set; }
        public string ANLASMANAKLIYEKIMEAIT { get; set; }
        public string ANLASMAODEMESEKLI { get; set; }
        public string ANLASMAILACBILGISI { get; set; }
        public string ANLASMATESLIMATYERI { get; set; }
        public Nullable<System.DateTime> ANLASMATESLIMATTARIHI { get; set; }
        public string ANLASMAOZELSARTLAR { get; set; }
        public string SATICITELEFON { get; set; }
        public string SATICIGSM { get; set; }
        public string SATICIADRES { get; set; }
        public string ALICITELEFON { get; set; }
        public string ALICIGSM { get; set; }
        public string ALICIADRES { get; set; }
        public string ANLASMAMUSTERIADI { get; set; }
        public string SATICIFIRMAKODU { get; set; }
        public string ALICIFIRMAKODU { get; set; }
    }
}
