//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAKSISEMRIURETIMHAREKET
    {
        public int IND { get; set; }
        public Nullable<int> BASLIKNO { get; set; }
        public string URUN { get; set; }
        public string KALIBRAJ { get; set; }
        public Nullable<decimal> GRAMAJBAS { get; set; }
        public Nullable<decimal> GRAMAJBIT { get; set; }
        public Nullable<int> SNO { get; set; }
        public Nullable<decimal> KG { get; set; }
        public Nullable<decimal> ADET { get; set; }
        public Nullable<decimal> AMBALAJ { get; set; }
        public Nullable<int> URUNNO { get; set; }
        public Nullable<int> TIP { get; set; }
        public string ACIKLAMA { get; set; }
        public byte[] KULLANILANANLASMALAR { get; set; }
    }
}
