//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAVMBELGENUMBER
    {
        public Nullable<int> BELGEIND { get; set; }
        public string BELGENO { get; set; }
        public Nullable<int> BIZAHAT { get; set; }
        public int IND { get; set; }
    }
}
