//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAVMKIRAPLAN
    {
        public int IND { get; set; }
        public Nullable<int> TANIMIND { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public string STOKKODU { get; set; }
        public string STOKADI { get; set; }
        public Nullable<int> FIRMANO { get; set; }
        public string FIRMAKODU { get; set; }
        public string FIRMAADI { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<bool> FATURALASTI { get; set; }
        public Nullable<System.DateTime> FTARIH { get; set; }
        public string FBELGENO { get; set; }
        public Nullable<int> DONEM { get; set; }
        public Nullable<int> AY { get; set; }
        public Nullable<decimal> ALAN { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<decimal> BFIYAT { get; set; }
        public string PB { get; set; }
        public Nullable<System.DateTime> KIRABASTAR { get; set; }
        public Nullable<System.DateTime> KIRABITTAR { get; set; }
        public Nullable<System.DateTime> KIRADEGTAR { get; set; }
        public Nullable<int> FBELGEIND { get; set; }
        public Nullable<bool> FIPTAL { get; set; }
    }
}
