//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAVMODEMEPLANI
    {
        public int IND { get; set; }
        public string SIRANO { get; set; }
        public string FIRMAKODU { get; set; }
        public string FIRMAADI { get; set; }
        public Nullable<System.DateTime> KIRABASTAR { get; set; }
        public Nullable<System.DateTime> KIRABITTAR { get; set; }
        public Nullable<System.DateTime> KIRADEGTAR { get; set; }
        public Nullable<decimal> M2 { get; set; }
        public Nullable<decimal> BFIYAT { get; set; }
        public Nullable<bool> M2CHECK { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
        public Nullable<int> AY { get; set; }
        public Nullable<bool> CIROCHECK { get; set; }
        public Nullable<decimal> F0 { get; set; }
        public Nullable<decimal> F1 { get; set; }
        public Nullable<decimal> F2 { get; set; }
        public Nullable<decimal> F3 { get; set; }
        public Nullable<decimal> F4 { get; set; }
        public Nullable<decimal> F5 { get; set; }
        public Nullable<decimal> F6 { get; set; }
        public Nullable<decimal> F7 { get; set; }
        public Nullable<decimal> F8 { get; set; }
        public Nullable<decimal> F9 { get; set; }
        public Nullable<decimal> CIRO { get; set; }
        public string PB { get; set; }
        public Nullable<int> DONEM { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public Nullable<int> FIRMANO { get; set; }
        public string STOKKODU { get; set; }
        public string STOKADI { get; set; }
        public Nullable<int> TANIMIND { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
    }
}
