//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBEYGECFAALIYETKAZANCDAGILIMI
    {
        public int IND { get; set; }
        public Nullable<int> GECIND { get; set; }
        public string FKODU { get; set; }
        public Nullable<decimal> SATISTUTARI { get; set; }
    }
}
