//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBEYGECFATURALAR
    {
        public int IND { get; set; }
        public Nullable<int> GECIND { get; set; }
        public string MERKEZSUBE { get; set; }
        public string MNVERKIMNO { get; set; }
        public Nullable<System.DateTime> FATURATARIHI { get; set; }
        public string FATURANO { get; set; }
        public string ALICIVERKIMNO { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public string MATBANOTERTCKNO { get; set; }
        public string ALICITCKIMLIKNO { get; set; }
        public string FATURACESIDI { get; set; }
    }
}
