//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBEYOTV1ACETVEL
    {
        public int IND { get; set; }
        public Nullable<int> OTVIND { get; set; }
        public string GTIP { get; set; }
        public Nullable<decimal> ITHALEDILENMIKTAR { get; set; }
        public Nullable<decimal> TESLIMEDILENMIKTAR { get; set; }
        public string OLCUBIRIMI { get; set; }
        public Nullable<System.DateTime> TESLIMTARIHI { get; set; }
        public Nullable<decimal> MAKTUTUTAR { get; set; }
        public Nullable<decimal> HESAPLANAN { get; set; }
        public Nullable<decimal> TESLIMBEDELI { get; set; }
        public string ACIKLAMA { get; set; }
    }
}
