//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBEYOTV1EKGCBBILGI
    {
        public int IND { get; set; }
        public Nullable<int> OTVIND { get; set; }
        public string GBTESCILNO { get; set; }
        public Nullable<System.DateTime> FATURATARIHI { get; set; }
        public string FATURANO { get; set; }
        public string ALICI { get; set; }
        public string ULKEKODU { get; set; }
        public string CINS { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
    }
}
