//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBELGEODEMEPLANIHAREKET
    {
        public int IND { get; set; }
        public Nullable<int> BASLIKIND { get; set; }
        public Nullable<int> BELGEIND { get; set; }
        public Nullable<int> BELGETIPI { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<System.DateTime> VADE { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public string PB { get; set; }
        public Nullable<System.DateTime> ISLEMTARIHI { get; set; }
        public Nullable<bool> YOKSAY { get; set; }
        public Nullable<int> CARIIND { get; set; }
        public Nullable<int> CARIBELGETIPI { get; set; }
        public Nullable<int> CARIBELGEIND { get; set; }
        public Nullable<int> CARIBELGESATIRIND { get; set; }
    }
}
