//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCARIBANKAKARTLARI
    {
        public int IND { get; set; }
        public Nullable<int> CARIIND { get; set; }
        public Nullable<int> BANKAIND { get; set; }
        public string BANKASUBEADI { get; set; }
        public string BANKAHESAPNO { get; set; }
        public string IBANNO { get; set; }
    }
}
