//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLDEMIRBAS
    {
        public string IND { get; set; }
        public string PARENTFIELD { get; set; }
        public string ISIM { get; set; }
        public Nullable<int> TIP { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<int> CINSI { get; set; }
        public Nullable<int> DEPARTMAN { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string MUHASEBE { get; set; }
        public string MUHAMOR { get; set; }
        public string MUHYEND { get; set; }
        public string MUHAGD { get; set; }
        public Nullable<int> SISTEM { get; set; }
        public Nullable<bool> AMORSECIM { get; set; }
        public Nullable<bool> YENDEGSECIM { get; set; }
        public string OZELLIKAD1 { get; set; }
        public string OZELLIK1 { get; set; }
        public string OZELLIKAD2 { get; set; }
        public string OZELLIK2 { get; set; }
        public string OZELLIKAD3 { get; set; }
        public string OZELLIK3 { get; set; }
        public string OZELLIKAD4 { get; set; }
        public string OZELLIK4 { get; set; }
        public string OZELLIKAD5 { get; set; }
        public string OZELLIK5 { get; set; }
        public Nullable<System.DateTime> BELGETARIHI { get; set; }
        public string BELGENO { get; set; }
        public string BELGEACIKLAMA { get; set; }
        public Nullable<decimal> AMRORAN { get; set; }
        public string KDVDURUM { get; set; }
        public Nullable<System.DateTime> CIKISTARIHI { get; set; }
        public Nullable<bool> AYLIK { get; set; }
        public string BAGLILIK { get; set; }
        public Nullable<int> AMORTIP { get; set; }
        public Nullable<decimal> BIRIKMISAMORTISMAN { get; set; }
        public Nullable<decimal> KDVTUTARI { get; set; }
        public Nullable<decimal> OMUR { get; set; }
        public Nullable<int> FOMURIND { get; set; }
        public Nullable<System.DateTime> SATISTARIHI { get; set; }
        public Nullable<decimal> SATISTUTARI { get; set; }
        public Nullable<decimal> SATISKDVTUTARI { get; set; }
        public Nullable<bool> SATILDI { get; set; }
        public Nullable<bool> ALIS { get; set; }
    }
}
