//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLEKLENTI
    {
        public int IND { get; set; }
        public Nullable<bool> SECIM { get; set; }
        public string TIP { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public string ISIM { get; set; }
        public Nullable<bool> DAMGAM { get; set; }
        public Nullable<bool> GELIRVM { get; set; }
        public Nullable<bool> SSKM { get; set; }
        public string GUNAY { get; set; }
        public string HESAPLAMA { get; set; }
        public string CALISMASEKLI { get; set; }
        public Nullable<decimal> ORAN { get; set; }
        public Nullable<decimal> MUAFIYET { get; set; }
        public Nullable<decimal> NETEKLENTI { get; set; }
        public Nullable<bool> KIDEMDAHIL { get; set; }
    }
}
