//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLEFATCONFIG
    {
        public int IND { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string DB { get; set; }
        public string Firma { get; set; }
        public string Donem { get; set; }
        public Nullable<int> FirmaId { get; set; }
        public Nullable<int> DonemId { get; set; }
        public string SAVEPATH { get; set; }
        public string CARDPASS { get; set; }
        public string LastInvoiceNumber { get; set; }
        public string CONFIGNAME { get; set; }
        public Nullable<int> SELECTEDADDRESS { get; set; }
        public Nullable<int> SELECTEDADRESS { get; set; }
        public Nullable<int> SELECTEDMALINCINSI { get; set; }
        public string SELECTEDPLUGIN { get; set; }
        public string CUSTOMPRINTFIELDS { get; set; }
        public Nullable<bool> GONDERILENEVRAKNUMARALARIOTOMATIKGUNCELLENSIN { get; set; }
    }
}
