//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFIELDDESCRIPTIONS
    {
        public int IND { get; set; }
        public Nullable<int> TIND { get; set; }
        public string FIELDNAME { get; set; }
        public Nullable<int> FIELDTYPE { get; set; }
        public Nullable<int> FIELDSIZE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> DURUM { get; set; }
        public Nullable<int> REFTABLE { get; set; }
        public Nullable<int> REFFIELD { get; set; }
    }
}
