//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFASTERDOVIZLER
    {
        public int IND { get; set; }
        public string DOVIZCINSI { get; set; }
        public string DOVIZSEMBOLU { get; set; }
        public string ULKE { get; set; }
        public Nullable<decimal> SATISFIYATI { get; set; }
        public Nullable<int> SUBEIND { get; set; }
        public string SUBEADI { get; set; }
    }
}
