//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFIRMAASILSATICIBILGILERI
    {
        public int IND { get; set; }
        public Nullable<int> FIRMAIND { get; set; }
        public string VERGIKIMLIKNO { get; set; }
        public string TCKIMLIKNO { get; set; }
        public string VERGIDAIRESI { get; set; }
        public string UNVAN { get; set; }
        public string YETKILIADI { get; set; }
        public string YETKILISOYADI { get; set; }
        public string ADRES { get; set; }
        public string ULKE { get; set; }
    }
}
