//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFASTERBELGENO
    {
        public int IND { get; set; }
        public string BELGENO { get; set; }
        public string IADEBELGENO { get; set; }
        public string DEPOKABULBELGENO { get; set; }
        public string DEPOGONDERIMBELGENO { get; set; }
        public string ICTALEPBELGENO { get; set; }
        public string LISTEBELGENO { get; set; }
    }
}
