//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLHALICMALFATURABASLIK
    {
        public int IND { get; set; }
        public Nullable<int> FIRMANO { get; set; }
        public Nullable<int> DEPONO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string BELGENO { get; set; }
        public string KASAADI { get; set; }
        public string SUBEADI { get; set; }
        public string KOD3 { get; set; }
        public string KOD4 { get; set; }
    }
}
