//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLHALICMALFATURAHAREKET
    {
        public int IND { get; set; }
        public Nullable<int> BASLIKIND { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public Nullable<int> BIRIMNO { get; set; }
        public Nullable<int> HARIND { get; set; }
        public Nullable<System.DateTime> BELGETARIHI { get; set; }
        public string BIRIMADI { get; set; }
        public string BELGENO { get; set; }
        public Nullable<decimal> AMBALAJMIKTARI { get; set; }
        public Nullable<int> AMBALAJSTKIND { get; set; }
        public Nullable<int> AMBALAJBRMIND { get; set; }
        public string STOKKODU { get; set; }
        public string MALINCINSI { get; set; }
        public string AMBALAJKODU { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<decimal> BIRIMFIYAT { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<decimal> KDV { get; set; }
        public Nullable<decimal> KDVTUTARI { get; set; }
    }
}
