//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLISSURECYUKLEMETALIMATBASLIK
    {
        public int IND { get; set; }
        public string BELGENO { get; set; }
        public Nullable<int> CARIIND { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string ARACPLAKA { get; set; }
        public Nullable<int> YUKLEYENPERSONEL { get; set; }
        public Nullable<int> SEVKIYATPERSONEL { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<bool> IPTAL { get; set; }
        public Nullable<System.DateTime> SEVKTARIHI { get; set; }
        public Nullable<int> SEVKEMRIIND { get; set; }
        public Nullable<int> SEVKDURUMU { get; set; }
    }
}
