//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLISBLD2
    {
        public int IND { get; set; }
        public Nullable<int> ISBLDIND { get; set; }
        public string SSKSICILNO { get; set; }
        public Nullable<System.DateTime> ISEGIRISTARIHI { get; set; }
        public string GOREVI { get; set; }
        public string CINSIYET { get; set; }
        public string MEDENIHAL { get; set; }
        public Nullable<short> COCUKSAY { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string BABAADI { get; set; }
        public Nullable<System.DateTime> DOGUMTARIHI { get; set; }
        public string DOGUMYERI { get; set; }
        public string SICILNO { get; set; }
        public Nullable<int> SOSGUVKURKOD { get; set; }
        public Nullable<int> GOREVKODU { get; set; }
        public string MESLEGI { get; set; }
        public Nullable<int> PERSONELIND { get; set; }
    }
}
