//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLITSHAZIRLANANSIPARIS
    {
        public int IND { get; set; }
        public Nullable<int> SIPIND { get; set; }
        public Nullable<int> USERNO { get; set; }
        public string USERNAME { get; set; }
    }
}
