//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKASAONAYISLEM
    {
        public int IND { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<int> ISLEM { get; set; }
        public Nullable<bool> KDVDAHIL { get; set; }
        public string PB { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<int> USERNO { get; set; }
        public string SUBEADI { get; set; }
        public string KASAADI { get; set; }
        public Nullable<System.DateTime> ISLEMTARIHI { get; set; }
        public Nullable<int> FIRMANO { get; set; }
        public string FIRMAKODU { get; set; }
        public string FIRMAADI { get; set; }
        public string OZELKOD { get; set; }
        public Nullable<bool> AKTARILDI { get; set; }
        public Nullable<decimal> GELIR { get; set; }
        public Nullable<decimal> GIDER { get; set; }
        public Nullable<decimal> KUR { get; set; }
    }
}
