//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKARTTANIM
    {
        public int IND { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<int> TAKSITSAYISI { get; set; }
        public Nullable<int> GECIKMEOPS { get; set; }
        public Nullable<int> TAKSITBASLAMAOPS { get; set; }
        public Nullable<decimal> YUZDEPESINAT { get; set; }
        public Nullable<decimal> ISKONTO { get; set; }
        public Nullable<int> BANKA { get; set; }
        public Nullable<decimal> YUZLUK { get; set; }
    }
}
