//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKASA2
    {
        public int IND { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<System.DateTime> SAAT { get; set; }
        public Nullable<int> ISLEM { get; set; }
        public Nullable<decimal> GELIR { get; set; }
        public Nullable<decimal> GIDER { get; set; }
        public Nullable<int> PARABIRIMI { get; set; }
        public Nullable<int> KASAMUHASEBEKODU { get; set; }
        public Nullable<int> HEDEFMUHASEBEKODU { get; set; }
        public Nullable<int> BORDRONO { get; set; }
        public Nullable<bool> TRANSFER { get; set; }
        public Nullable<bool> SELECTED { get; set; }
    }
}
