//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKOSULHAREKET
    {
        public int IND { get; set; }
        public Nullable<int> LN { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<decimal> ISK1 { get; set; }
        public Nullable<decimal> ISK2 { get; set; }
        public Nullable<decimal> ISK3 { get; set; }
        public Nullable<decimal> ISK4 { get; set; }
        public Nullable<int> PRMSTOK { get; set; }
        public Nullable<decimal> PRMMIKTAR { get; set; }
        public Nullable<int> FIYAT { get; set; }
        public Nullable<int> PARABIRIMI { get; set; }
        public Nullable<int> OPSIYON { get; set; }
    }
}
