//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLLOJBOLGELER
    {
        public int Ind { get; set; }
        public Nullable<int> SiraNo { get; set; }
        public string BolgeKodu { get; set; }
        public string UstBolgeKodu { get; set; }
        public string BolgeAdi { get; set; }
        public Nullable<decimal> Km { get; set; }
    }
}
