//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLLOJSOZLESMEBASLIK
    {
        public int Ind { get; set; }
        public Nullable<int> SiraNo { get; set; }
        public Nullable<int> SaticiFirmaInd { get; set; }
        public string SaticiAdiSoyadi { get; set; }
        public string SaticiAdresi { get; set; }
        public string SaticiVergiDairesi { get; set; }
        public string SaticiTel { get; set; }
        public string SaticiSevkAdresi { get; set; }
        public string SaticiSevkAdresKodu { get; set; }
        public string SaticiSevkAdresTel { get; set; }
        public Nullable<int> AliciFirmaInd { get; set; }
        public string AliciAdiSoyadi { get; set; }
        public string AliciAdresi { get; set; }
        public string AliciVergiDairesi { get; set; }
        public string AliciTel { get; set; }
        public string AliciSevkAdresi { get; set; }
        public string AliciSevkAdresKodu { get; set; }
        public string AliciSevkAdresTel { get; set; }
        public Nullable<int> AracInd { get; set; }
        public Nullable<int> AracSahibiInd { get; set; }
        public string AracPlakaNo { get; set; }
        public string AracRuhsatNo { get; set; }
        public string AracSahibi { get; set; }
        public string AracDorseNo { get; set; }
        public Nullable<int> SoforInd { get; set; }
        public string SoforAdSoyad { get; set; }
        public string SoforEhliyetNo { get; set; }
        public string SoforVerYer { get; set; }
        public string SoforCepTel { get; set; }
        public string SoforKanGrubu { get; set; }
        public string SoforTCNo { get; set; }
        public string IrsaliyeNo { get; set; }
        public string IrsaliyeFatNo { get; set; }
        public string NakliyeNo { get; set; }
        public Nullable<System.DateTime> SevkTarihi { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<bool> FaturaAliciyaKesilsin { get; set; }
        public string BolgeKodu { get; set; }
        public string Yon { get; set; }
        public string YonKodu { get; set; }
        public string AracTipKodu { get; set; }
        public Nullable<int> HedefBelgeInd { get; set; }
        public Nullable<int> HedefBelgeIzahat { get; set; }
        public Nullable<int> HedefBordroCikisInd { get; set; }
        public Nullable<int> HedefBordroCikisIzahat { get; set; }
        public Nullable<int> HedefBordroGirisInd { get; set; }
        public Nullable<int> HedefBordroGirisIzahat { get; set; }
        public string SiparisZT { get; set; }
        public Nullable<bool> Iptal { get; set; }
        public string SubeAdi { get; set; }
        public string KasaAdi { get; set; }
    }
}
