//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLLOJARACKARTI
    {
        public int Ind { get; set; }
        public Nullable<int> AracSahibiInd { get; set; }
        public string AracTipKodu { get; set; }
        public Nullable<bool> Aitlik { get; set; }
        public string PlakaNo { get; set; }
        public string RuhsatNo { get; set; }
        public string DorseNo { get; set; }
        public string SoforAdiSoyadi { get; set; }
        public string SoforCepTel { get; set; }
        public string SoforEhliyetNo { get; set; }
        public string SoforKanGrubu { get; set; }
        public string SoforTCNo { get; set; }
        public string SoforVerildigiYer { get; set; }
        public string SoforSinifi { get; set; }
        public Nullable<decimal> Tonaj { get; set; }
        public Nullable<bool> AracBosta { get; set; }
        public string Sehir { get; set; }
        public Nullable<System.DateTime> TrafikMuayeneTarihi { get; set; }
        public Nullable<System.DateTime> TrafikSigortaTarihi { get; set; }
    }
}
