//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPLUGHKSMASRAFBILGILERI
    {
        public int IND { get; set; }
        public Nullable<int> BELGEIND { get; set; }
        public Nullable<int> BELGEIZAHAT { get; set; }
        public Nullable<decimal> KOMISYONORAN { get; set; }
        public Nullable<decimal> NAVLUNORAN { get; set; }
        public Nullable<decimal> HAMMALIYEORAN { get; set; }
        public Nullable<decimal> NAKLIYEORAN { get; set; }
        public Nullable<decimal> GELIRVORAN { get; set; }
        public Nullable<decimal> BAGKURTEVKIFATORAN { get; set; }
        public Nullable<decimal> HALRUSUMUORAN { get; set; }
        public Nullable<decimal> TICBORSASIORAN { get; set; }
        public Nullable<decimal> MILLISFONUORAN { get; set; }
        public Nullable<decimal> DIGERORAN { get; set; }
        public Nullable<decimal> KOMISYON { get; set; }
        public Nullable<decimal> NAVLUN { get; set; }
        public Nullable<decimal> HAMMALIYE { get; set; }
        public Nullable<decimal> NAKLIYE { get; set; }
        public Nullable<decimal> GELIRV { get; set; }
        public Nullable<decimal> BAGKURTEVKIFATI { get; set; }
        public Nullable<decimal> HALRUSUMU { get; set; }
        public Nullable<decimal> TICBORSASI { get; set; }
        public Nullable<decimal> MILLISFONU { get; set; }
        public Nullable<decimal> DIGER { get; set; }
        public Nullable<decimal> KOMISYONKDV { get; set; }
        public Nullable<decimal> NAVLUNKDV { get; set; }
        public Nullable<decimal> HAMMALIYEKDV { get; set; }
        public Nullable<decimal> NAKLIYEKDV { get; set; }
        public Nullable<decimal> HALRUSUMUKDV { get; set; }
        public Nullable<decimal> TICBORSASIKDV { get; set; }
        public Nullable<decimal> MILLISFONUKDV { get; set; }
        public Nullable<decimal> DIGERKDV { get; set; }
    }
}
