//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPOSZRPBASLIK
    {
        public int IND { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string KASANO { get; set; }
        public string SUBE { get; set; }
        public Nullable<decimal> TOPLAM { get; set; }
        public Nullable<decimal> NAKIT { get; set; }
        public Nullable<decimal> VISA { get; set; }
        public string BELGENO { get; set; }
        public Nullable<int> ENTEGRE { get; set; }
        public string FISNO { get; set; }
        public string CIHAZSERINO { get; set; }
        public string EKUNO { get; set; }
        public Nullable<decimal> KRD1TEK { get; set; }
        public Nullable<decimal> KRD1TKS { get; set; }
        public Nullable<decimal> KRD2TEK { get; set; }
        public Nullable<decimal> KRD2TKS { get; set; }
        public Nullable<decimal> KRD3TEK { get; set; }
        public Nullable<decimal> KRD3TKS { get; set; }
        public Nullable<decimal> KRD4TEK { get; set; }
        public Nullable<decimal> KRD4TKS { get; set; }
        public Nullable<decimal> KRD5TEK { get; set; }
        public Nullable<decimal> KRD5TKS { get; set; }
        public Nullable<decimal> KRD6TEK { get; set; }
        public Nullable<decimal> KRD6TKS { get; set; }
        public Nullable<decimal> KRD7TEK { get; set; }
        public Nullable<decimal> KRD7TKS { get; set; }
        public Nullable<decimal> KRD8TEK { get; set; }
        public Nullable<decimal> KRD8TKS { get; set; }
        public Nullable<decimal> KRD9TEK { get; set; }
        public Nullable<decimal> KRD9TKS { get; set; }
        public Nullable<decimal> KRD10TEK { get; set; }
        public Nullable<decimal> KRD10TKS { get; set; }
        public Nullable<decimal> KRD11TEK { get; set; }
        public Nullable<decimal> KRD11TKS { get; set; }
        public Nullable<decimal> KRD12TEK { get; set; }
        public Nullable<decimal> KRD12TKS { get; set; }
        public Nullable<decimal> KRD13TEK { get; set; }
        public Nullable<decimal> KRD13TKS { get; set; }
        public Nullable<decimal> KRD14TEK { get; set; }
        public Nullable<decimal> KRD14TKS { get; set; }
        public Nullable<decimal> KRD15TEK { get; set; }
        public Nullable<decimal> KRD15TKS { get; set; }
        public Nullable<decimal> KRD16TEK { get; set; }
        public Nullable<decimal> KRD16TKS { get; set; }
        public Nullable<decimal> KRD17TEK { get; set; }
        public Nullable<decimal> KRD17TKS { get; set; }
        public Nullable<decimal> KRD18TEK { get; set; }
        public Nullable<decimal> KRD18TKS { get; set; }
        public Nullable<decimal> KRD19TEK { get; set; }
        public Nullable<decimal> KRD19TKS { get; set; }
        public Nullable<decimal> KRD20TEK { get; set; }
        public Nullable<decimal> KRD20TKS { get; set; }
        public Nullable<decimal> IADE { get; set; }
        public Nullable<decimal> IADEKDVTUTAR { get; set; }
        public Nullable<decimal> IADENET { get; set; }
        public Nullable<decimal> IADEODENAKIT { get; set; }
        public Nullable<decimal> IADEODEKREDI { get; set; }
    }
}
