//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPLUGMETRETULFORMULLER
    {
        public int IND { get; set; }
        public string FORMUL { get; set; }
        public string FORMULBASLIK { get; set; }
        public Nullable<decimal> S1 { get; set; }
        public Nullable<decimal> S2 { get; set; }
        public Nullable<decimal> S3 { get; set; }
        public Nullable<decimal> A { get; set; }
        public Nullable<decimal> B { get; set; }
        public Nullable<decimal> C { get; set; }
        public decimal D { get; set; }
        public Nullable<decimal> E { get; set; }
        public Nullable<decimal> ADET { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public string ACIKLAMA { get; set; }
        public string GUIDNO { get; set; }
        public string BELGEIND { get; set; }
        public string BELGEIZAHAT { get; set; }
    }
}
