//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLRESSIPARIS
    {
        public int IND { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<decimal> BIRIMFIYAT { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<int> SIPARISTUR { get; set; }
        public string SIPARISNOTU { get; set; }
        public Nullable<bool> IKRAM { get; set; }
        public Nullable<bool> FATURALASTI { get; set; }
        public Nullable<int> YAZICICIKTI { get; set; }
        public Nullable<System.DateTime> SAAT { get; set; }
        public Nullable<System.DateTime> PISMESURE { get; set; }
        public Nullable<int> ADISYONNO { get; set; }
        public Nullable<int> PUSULANO { get; set; }
        public Nullable<int> PAKETNO { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public Nullable<int> STOKDETAYNO { get; set; }
        public Nullable<int> SNOTUNO { get; set; }
        public Nullable<int> BIRIMIND { get; set; }
        public Nullable<decimal> GERCEKTOPLAM { get; set; }
        public Nullable<decimal> ISK { get; set; }
        public Nullable<bool> IPTAL { get; set; }
        public Nullable<int> DEPO { get; set; }
        public Nullable<int> PERSONEL { get; set; }
    }
}
