//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSEVKKOSULLARI
    {
        public int IND { get; set; }
        public Nullable<int> BELGEIND { get; set; }
        public Nullable<int> BELGEIZAHAT { get; set; }
        public Nullable<System.DateTime> SEVKTARIHI { get; set; }
        public string SEVKSEKLI { get; set; }
        public string SEVKVASITASI { get; set; }
        public string VASITANUMARASI { get; set; }
    }
}
