//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLTUPLANMAMULLER
    {
        public int IND { get; set; }
        public Nullable<int> BASLIKIND { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public string STOKKODU { get; set; }
        public string MALINCINSI { get; set; }
        public Nullable<decimal> SIPARISMIKTARI { get; set; }
        public Nullable<decimal> EKMIKTAR { get; set; }
        public Nullable<System.DateTime> URETIMEBASLAMATARIHI { get; set; }
        public Nullable<System.DateTime> URETIMITAMAMLAMATARIHI { get; set; }
        public Nullable<bool> ONAY { get; set; }
        public Nullable<int> ISEMRIIND { get; set; }
        public Nullable<int> RECETEIND { get; set; }
        public Nullable<int> STOKTIPI { get; set; }
        public Nullable<int> ANASTOKNO { get; set; }
        public Nullable<System.DateTime> SIPARISTARIHI { get; set; }
        public Nullable<System.DateTime> TERMINTARIHI { get; set; }
        public string SIPARISBELGENO { get; set; }
        public Nullable<int> SIPARISFIRMANO { get; set; }
        public string SIPARISFIRMAKODU { get; set; }
        public string SIPARISFIRMAADI { get; set; }
        public Nullable<int> SIPARISNO { get; set; }
        public Nullable<int> HAREKETNO { get; set; }
        public string SIPARISOZELKODNO1 { get; set; }
    }
}
