//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLTXBOYUTITEMS
    {
        public int IND { get; set; }
        public Nullable<int> BOYUT { get; set; }
        public string KOD { get; set; }
        public string DEGER { get; set; }
        public string BARKOD { get; set; }
        public string KATEGORI { get; set; }
    }
}
