//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLTAXFREEFATURA
    {
        public int IND { get; set; }
        public Nullable<bool> FATURAISLENDIMI { get; set; }
        public Nullable<System.DateTime> ISLEMTARIHI { get; set; }
        public Nullable<int> FIRMAIND { get; set; }
        public Nullable<int> DONEMIND { get; set; }
        public Nullable<int> FATURAIND { get; set; }
        public string FATURAJSON { get; set; }
    }
}
