//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLVADFATBASLIK
    {
        public int IND { get; set; }
        public string FIRMAADI { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public string BELGENO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string KDV { get; set; }
        public string AK { get; set; }
        public Nullable<bool> ENVANTERUPDATE { get; set; }
        public Nullable<System.DateTime> ODEMETARIHI { get; set; }
        public Nullable<bool> ODMODIFIED { get; set; }
        public string ALTBELGENO { get; set; }
        public Nullable<System.DateTime> ALTBELGETARIHI { get; set; }
        public Nullable<decimal> ALT1 { get; set; }
        public Nullable<decimal> ALT2 { get; set; }
        public Nullable<decimal> ALT3 { get; set; }
        public Nullable<decimal> ALT4 { get; set; }
        public Nullable<decimal> YUVARLAMA { get; set; }
        public Nullable<int> DEPO { get; set; }
        public string SUCCESS { get; set; }
        public string ALTNOT { get; set; }
        public Nullable<int> OZELKOD { get; set; }
        public string OZELKOD1 { get; set; }
        public string OZELKOD2 { get; set; }
        public Nullable<decimal> KALEM1 { get; set; }
        public Nullable<decimal> KALEM2 { get; set; }
        public Nullable<decimal> KALEM3 { get; set; }
        public Nullable<decimal> KALEM4 { get; set; }
        public Nullable<bool> IADE { get; set; }
        public Nullable<bool> IPTAL { get; set; }
        public Nullable<bool> CONVERTED { get; set; }
        public Nullable<System.DateTime> CREDATE { get; set; }
        public Nullable<System.DateTime> LADATE { get; set; }
        public Nullable<int> FIRMANO { get; set; }
        public string PARABIRIMI { get; set; }
        public Nullable<decimal> KUR { get; set; }
        public Nullable<decimal> ODENEN { get; set; }
        public Nullable<bool> SELECTED { get; set; }
        public Nullable<int> ENTEGRE { get; set; }
        public Nullable<int> USERNO { get; set; }
        public Nullable<decimal> KDVISK { get; set; }
        public Nullable<int> SATISSEKLI { get; set; }
        public Nullable<decimal> ARATOPLAM { get; set; }
        public Nullable<int> KONSOLIDE { get; set; }
        public Nullable<int> ODEMEOPSIYONU { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<bool> YURTDISI { get; set; }
        public Nullable<bool> MUHASEBELESMEYECEK { get; set; }
        public string OZELKOD3 { get; set; }
        public string OZELKOD4 { get; set; }
    }
}
