//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class U0111TBLAJNEVENT
    {
        public int IND { get; set; }
        public Nullable<int> EVENTIND { get; set; }
        public Nullable<int> INTERVALL { get; set; }
        public Nullable<int> GROUPIND { get; set; }
        public Nullable<System.DateTime> EVENTDATE { get; set; }
        public Nullable<bool> VISIBLE { get; set; }
        public Nullable<bool> HERYIL { get; set; }
        public string EVENTTYPE { get; set; }
        public string INTTYPE { get; set; }
    }
}
