//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOZELRAPOR_9848473D_D84B_492E_BA0D_FB84AD312545_
    {
        public int IND { get; set; }
        public string USERNAME { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string SIFRE { get; set; }
        public Nullable<int> FIRMA { get; set; }
        public Nullable<int> DONEM { get; set; }
        public Nullable<int> STATUS { get; set; }
    }
}
