//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_AlinanCekler
    {
        public string FIRMAADI { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public int IND { get; set; }
        public Nullable<System.DateTime> VADE { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
    }
}
