//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_CariDetay1
    {
        public Nullable<System.DateTime> TARIH { get; set; }
        public string BELGENO { get; set; }
        public string ISLEMIZAHAT { get; set; }
        public string BELGEIZAHAT { get; set; }
        public Nullable<decimal> ALACAK { get; set; }
        public Nullable<decimal> BORC { get; set; }
        public int CARIIND { get; set; }
        public string UNVAN { get; set; }
    }
}
