//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_ECSCari
    {
        public decimal TUTAR { get; set; }
        public string FIRMAADI { get; set; }
        public string FIRMAKODU { get; set; }
        public string KOD5 { get; set; }
        public string UNVAN { get; set; }
        public Nullable<int> PERSONELNO { get; set; }
    }
}
