//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_caridetay
    {
        public string TARIH { get; set; }
        public string BELGENO { get; set; }
        public string FIRMAKODU { get; set; }
        public string FIRMAADI { get; set; }
        public string IND { get; set; }
        public string ISLEMIZAHAT { get; set; }
        public string BELGEIZAHAT { get; set; }
        public string MIKTAR { get; set; }
        public string ALACAK { get; set; }
        public string BORC { get; set; }
        public string CARIIND { get; set; }
        public string KOD5 { get; set; }
        public string AB { get; set; }
        public string UNVAN { get; set; }
        public string GTARIH { get; set; }
    
        public virtual data_carilist data_carilist { get; set; }
    }
}
