//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_StokDeger
    {
        public string IND { get; set; }
        public string MALINCINSI { get; set; }
        public string STATUS { get; set; }
        public string BIRIMADI { get; set; }
        public string ALISFIYATI { get; set; }
        public string MALIYET { get; set; }
        public string ALISFIYATITUTARI { get; set; }
        public string ALISFIYATITUTARIKDVLI { get; set; }
        public string SATISFIYATITUTAR1 { get; set; }
        public string S1KDV { get; set; }
        public string SATISFIYATITUTAR2 { get; set; }
        public string SATISFIYATI1 { get; set; }
        public string SATISFIYATI2 { get; set; }
        public string KDVDAHIL { get; set; }
        public string MALIYETTUTAR { get; set; }
        public string PB1 { get; set; }
        public string KALAN { get; set; }
        public string KOD1 { get; set; }
        public string KOD5 { get; set; }
        public string KDV { get; set; }
        public string GTARIH { get; set; }
    }
}
