//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_SonGelenler
    {
        public string IND { get; set; }
        public string STOKKODU { get; set; }
        public string MALINCINSI { get; set; }
        public string KOD5 { get; set; }
        public string MALIYET { get; set; }
        public string KDVGRUBU { get; set; }
        public string ENVANTER { get; set; }
        public string STATUS { get; set; }
        public string SATISFIYATI1 { get; set; }
        public string BARCODE { get; set; }
        public string BIRIMADI { get; set; }
        public string KARTINACILMATARIHI { get; set; }
        public string KOD1 { get; set; }
        public string GTARIH { get; set; }
    }
}
