//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_Firma
    {
        public int ID { get; set; }
        public string FIRMAIND { get; set; }
        public string DONEMIND { get; set; }
        public string FIRMAADI { get; set; }
        public string DONEM { get; set; }
        public string LOGO { get; set; }
    }
}
