//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_GecList
    {
        public string IND { get; set; }
        public string TARIH { get; set; }
        public string FIRMANO { get; set; }
        public string STOKKODU { get; set; }
        public string MALINCINSI { get; set; }
        public string FIRMAKODU { get; set; }
        public string FIRMAADI { get; set; }
        public string EVRAKCINSI { get; set; }
        public string SATISFIYATI1 { get; set; }
        public string SBIRIMADI { get; set; }
        public string SMIKTAR { get; set; }
        public string BIRIMADI { get; set; }
        public string KDVDAHIL { get; set; }
        public string BARCODE { get; set; }
        public string EVRAKNO { get; set; }
        public string KDV { get; set; }
        public string CIKAN { get; set; }
        public string MIKTAR { get; set; }
        public string BIRIMMALIYET { get; set; }
        public string BIRIMFIYAT { get; set; }
        public string TOPLAMKDV { get; set; }
        public string ARATOPLAM { get; set; }
        public string GENELTOPLAM { get; set; }
        public string GTARIH { get; set; }
    }
}
