//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_Duyurular
    {
        public string KONU { get; set; }
        public string ICERIK { get; set; }
        public string GONDEREN { get; set; }
        public string ALICI { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public int ID { get; set; }
    }
}
