//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_Users
    {
        public int ID { get; set; }
        public string FOTO_URL { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string PERSONELNO { get; set; }
        public string GSM { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> STATUS { get; set; }
    }
}
