//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Data_AlinanCekler> Data_AlinanCekler { get; set; }
        public virtual DbSet<Data_CariBilgi> Data_CariBilgi { get; set; }
        public virtual DbSet<Data_ECSCari> Data_ECSCari { get; set; }
        public virtual DbSet<Data_ECSTutar> Data_ECSTutar { get; set; }
        public virtual DbSet<Data_ECSUrunler> Data_ECSUrunler { get; set; }
        public virtual DbSet<Data_Faaliyet> Data_Faaliyet { get; set; }
        public virtual DbSet<Data_FiyatDegisen> Data_FiyatDegisen { get; set; }
        public virtual DbSet<Data_GecList> Data_GecList { get; set; }
        public virtual DbSet<Data_GecSipList> Data_GecSipList { get; set; }
        public virtual DbSet<Data_GecTahsilat> Data_GecTahsilat { get; set; }
        public virtual DbSet<Data_HareketsizUrun> Data_HareketsizUrun { get; set; }
        public virtual DbSet<Data_PlasTop> Data_PlasTop { get; set; }
        public virtual DbSet<Data_SatFat> Data_SatFat { get; set; }
        public virtual DbSet<Data_SatFatDet> Data_SatFatDet { get; set; }
        public virtual DbSet<Data_SonGelenler> Data_SonGelenler { get; set; }
        public virtual DbSet<Data_StokDeger> Data_StokDeger { get; set; }
        public virtual DbSet<Data_StokList> Data_StokList { get; set; }
        public virtual DbSet<Data_TahsDet> Data_TahsDet { get; set; }
        public virtual DbSet<Data_Tahsilat> Data_Tahsilat { get; set; }
        public virtual DbSet<Data_VerilenCekler> Data_VerilenCekler { get; set; }
        public virtual DbSet<Data_CariDetay> Data_CariDetay { get; set; }
        public virtual DbSet<Data_CariList> Data_CariList { get; set; }
    }
}
