//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbDatabase : DbContext
    {
        public DbDatabase()
            : base("name=DbDatabase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<data_caribilgi> data_caribilgi { get; set; }
        public virtual DbSet<data_caridetay> data_caridetay { get; set; }
        public virtual DbSet<data_carilist> data_carilist { get; set; }
        public virtual DbSet<data_geclist> data_geclist { get; set; }
        public virtual DbSet<data_gectahsilat> data_gectahsilat { get; set; }
        public virtual DbSet<data_getsiplist> data_getsiplist { get; set; }
        public virtual DbSet<data_satfat> data_satfat { get; set; }
        public virtual DbSet<data_satfatdet> data_satfatdet { get; set; }
        public virtual DbSet<data_tahsdet> data_tahsdet { get; set; }
        public virtual DbSet<data_tahsilat> data_tahsilat { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<data_alinancekler> data_alinancekler { get; set; }
        public virtual DbSet<data_ecscari> data_ecscari { get; set; }
        public virtual DbSet<data_ecstutar> data_ecstutar { get; set; }
        public virtual DbSet<data_ecsurunler> data_ecsurunler { get; set; }
        public virtual DbSet<data_faaliyet> data_faaliyet { get; set; }
        public virtual DbSet<data_fiyatdegisen> data_fiyatdegisen { get; set; }
        public virtual DbSet<data_hareketsizurun> data_hareketsizurun { get; set; }
        public virtual DbSet<data_plastop> data_plastop { get; set; }
        public virtual DbSet<data_songelenler> data_songelenler { get; set; }
        public virtual DbSet<data_stokdeger> data_stokdeger { get; set; }
        public virtual DbSet<data_stoklist> data_stoklist { get; set; }
        public virtual DbSet<data_verilencekler> data_verilencekler { get; set; }
    }
}
