//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0112D0015TBLREZERVHAREKETLERI
    {
        public int IND { get; set; }
        public Nullable<int> KDV { get; set; }
        public Nullable<int> SERINO { get; set; }
        public Nullable<int> PERSONEL { get; set; }
        public Nullable<int> OPSIYON { get; set; }
        public Nullable<int> FIRMANO { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public Nullable<int> BELGENO { get; set; }
        public Nullable<int> LN { get; set; }
        public Nullable<int> DEPO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<System.DateTime> SIRALAMATARIHI { get; set; }
        public Nullable<bool> IADE { get; set; }
        public Nullable<decimal> GIREN { get; set; }
        public Nullable<decimal> CIKAN { get; set; }
        public Nullable<decimal> KALAN { get; set; }
        public Nullable<decimal> BIRIMMALIYET { get; set; }
        public Nullable<decimal> KUR { get; set; }
        public Nullable<decimal> SIRALAMATARIHIEX { get; set; }
        public Nullable<decimal> BIRIMFIYAT { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public string EVRAKNO { get; set; }
        public string IZAHAT { get; set; }
        public string PARABIRIMI { get; set; }
    }
}
