//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0114TBLBEYKGECDARMUKELLEF
    {
        public int IND { get; set; }
        public Nullable<decimal> KGECICIIND { get; set; }
        public Nullable<decimal> TOPLAMHASILAT { get; set; }
        public Nullable<decimal> ORTAKEMSALNISBETI { get; set; }
        public Nullable<decimal> KURUMKAZANCI { get; set; }
        public string ULASTIRMATURU { get; set; }
    }
}
