//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0112D0003TBLEFAINBOX
    {
        public int IND { get; set; }
        public string Evrakno { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string FirmaAdi { get; set; }
        public string VKN { get; set; }
        public string Senaryo { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public string TutarStr { get; set; }
        public string PB { get; set; }
        public Nullable<bool> eFatura { get; set; }
        public string IzahatStr { get; set; }
        public string UUID { get; set; }
        public byte[] RAWINVOICE { get; set; }
        public Nullable<int> RESPONSESTATUS { get; set; }
        public string RESPONSEMESSAGE { get; set; }
        public Nullable<int> IMPORTSTATUS { get; set; }
        public string RESPONSECODE { get; set; }
        public string RESPONSEUIID { get; set; }
        public string URN { get; set; }
        public string SourceURN { get; set; }
        public Nullable<System.DateTime> KabulTarihi { get; set; }
        public string RESPONSEUUID { get; set; }
        public Nullable<bool> ARSIVLENDI { get; set; }
        public string SUBEADI { get; set; }
        public Nullable<bool> OKUNDU { get; set; }
    }
}
