//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0112TBLMARKETANLASMABASLIK
    {
        public int IND { get; set; }
        public Nullable<int> FIRMANO { get; set; }
        public Nullable<int> DEPONO { get; set; }
        public Nullable<int> TYPE { get; set; }
        public Nullable<int> CHOSENCONTRACTTYPE { get; set; }
        public Nullable<System.DateTime> CONTRACTDATE { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> EXPIREDATE { get; set; }
        public Nullable<bool> GRUP { get; set; }
        public Nullable<decimal> KDVVALUE { get; set; }
        public Nullable<decimal> ANLASMATUTARI { get; set; }
        public Nullable<decimal> ANLASMAORANI { get; set; }
        public Nullable<decimal> CRITER3 { get; set; }
        public Nullable<decimal> CRITER4 { get; set; }
        public Nullable<decimal> RESULT1 { get; set; }
        public Nullable<decimal> RESULT2 { get; set; }
        public Nullable<decimal> RESULT3 { get; set; }
        public Nullable<decimal> RESULT4 { get; set; }
        public Nullable<decimal> CRITER1 { get; set; }
        public Nullable<decimal> CRITER2 { get; set; }
        public string EXPLAINING { get; set; }
        public string KOD3 { get; set; }
        public string KOD4 { get; set; }
        public string KOD5 { get; set; }
        public string KOD6 { get; set; }
        public string CONTRACTNO { get; set; }
        public string KOD1 { get; set; }
        public string KOD2 { get; set; }
    }
}
