//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0112D0015TBLKUPUR
    {
        public int IND { get; set; }
        public Nullable<int> BIND { get; set; }
        public Nullable<int> MIKTAR { get; set; }
        public string HESAPKODU { get; set; }
    }
}
