//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0114D0011TBLMUSCARIBILGI
    {
        public int IND { get; set; }
        public Nullable<int> BELGENO { get; set; }
        public Nullable<System.DateTime> DOGUMTARIHI { get; set; }
        public Nullable<System.DateTime> BAGKURISTISNABASTARIH { get; set; }
        public Nullable<System.DateTime> BAGKURISTISNABITTARIH { get; set; }
        public string ADRES { get; set; }
        public string SATICIADI { get; set; }
        public string BABAADI { get; set; }
        public string DOGUMYERI { get; set; }
        public string SGUVENLIKNO { get; set; }
    }
}
