//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0111D0013TBLPESININFO
    {
        public int IND { get; set; }
        public Nullable<int> FATURANO { get; set; }
        public Nullable<int> FATURABELGETIPI { get; set; }
        public string FIRMAADI { get; set; }
        public string ADRES { get; set; }
        public string VERGIDAIRESI { get; set; }
        public string VERGINO { get; set; }
        public string EMAIL { get; set; }
    }
}
