//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0114D0011VSTOKHAREKETLERI4
    {
        public int IND { get; set; }
        public Nullable<int> FIRMANO { get; set; }
        public string EVRAKNO { get; set; }
        public string IZAHAT { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public Nullable<int> BELGENO { get; set; }
        public Nullable<int> LN { get; set; }
        public Nullable<int> DEPO { get; set; }
        public Nullable<int> DETAY { get; set; }
        public Nullable<bool> KDV { get; set; }
        public string OZELKOD1 { get; set; }
        public string OZELKOD2 { get; set; }
    }
}
