//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0111D0013TBLOTOISEMRISATIR
    {
        public int IND { get; set; }
        public Nullable<int> ISEMRINO { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public Nullable<int> STOKTIPI { get; set; }
        public Nullable<int> ISLEMSURESI { get; set; }
        public Nullable<int> DETAY { get; set; }
        public Nullable<int> GARANTISURESI { get; set; }
        public Nullable<int> PERSONELNO { get; set; }
        public Nullable<int> OTOISEMIRLERIEXDETAYREF { get; set; }
        public Nullable<int> TKLEIMBELGENO { get; set; }
        public Nullable<int> KLEIMIZAHAT { get; set; }
        public Nullable<int> KLEIMBELGENO { get; set; }
        public Nullable<int> DEPO { get; set; }
        public Nullable<int> IZAHAT { get; set; }
        public Nullable<int> BELGENO { get; set; }
        public Nullable<int> BELGESATNO { get; set; }
        public Nullable<int> BIRIMEX { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<System.DateTime> GARANTIBITISTARIHI { get; set; }
        public Nullable<System.DateTime> GARANTIBASLANGICTARIHI { get; set; }
        public Nullable<System.DateTime> GARANTITARIHI { get; set; }
        public Nullable<System.DateTime> BELGETARIH { get; set; }
        public Nullable<System.DateTime> KLEIMBELGETARIH { get; set; }
        public string DOSYA { get; set; }
        public Nullable<bool> IADE { get; set; }
        public Nullable<bool> KISMIBELGELEME { get; set; }
        public Nullable<bool> KLEIMBELGE { get; set; }
        public Nullable<bool> KLEIM { get; set; }
        public Nullable<decimal> KUR { get; set; }
        public Nullable<decimal> BIRIMMIKTAR { get; set; }
        public Nullable<decimal> GERCEKTOPLAM { get; set; }
        public Nullable<decimal> GRUPMIKTAR { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<decimal> BFIYAT { get; set; }
        public Nullable<decimal> KDV { get; set; }
        public Nullable<decimal> ISK1 { get; set; }
        public Nullable<decimal> ISK2 { get; set; }
        public string STOKKODU { get; set; }
        public string MALINCINSI { get; set; }
        public string DOSYADI { get; set; }
        public string GARANTIONAYKODU { get; set; }
        public string ARIZAKODU { get; set; }
        public string DETAYACIKLAMA { get; set; }
        public string KARSISTOKODU { get; set; }
        public string BARKOD { get; set; }
        public string ACIKLAMA { get; set; }
        public string PARABIRIMI { get; set; }
        public string KLEIMBELGEADI { get; set; }
        public string BIRIMADI { get; set; }
    }
}
