//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0111D0013TBLYEVMIYELOCK
    {
        public int IND { get; set; }
        public Nullable<int> YEVNO1 { get; set; }
        public Nullable<int> YEVNO2 { get; set; }
        public Nullable<System.DateTime> TARIH1 { get; set; }
        public Nullable<System.DateTime> TARIH2 { get; set; }
        public Nullable<bool> ONAY { get; set; }
    }
}
