//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0112D0003TBLMUSORANLARI
    {
        public int IND { get; set; }
        public Nullable<decimal> BORSA { get; set; }
        public Nullable<decimal> BAGKUR { get; set; }
        public Nullable<decimal> STOPAJ { get; set; }
        public Nullable<decimal> SSDF { get; set; }
        public Nullable<decimal> KOMISYON { get; set; }
        public Nullable<decimal> KDV { get; set; }
        public Nullable<decimal> EKORAN1 { get; set; }
        public Nullable<decimal> EKORAN2 { get; set; }
        public Nullable<int> BELGENO { get; set; }
        public Nullable<decimal> MASRAFBFIYAT { get; set; }
        public Nullable<bool> BAGKURORANSAL { get; set; }
        public Nullable<bool> STOPAJORANSAL { get; set; }
        public Nullable<bool> BORSAORANSAL { get; set; }
    }
}
