//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0114TBLWSBNKKARTANLASMALARI
    {
        public int IND { get; set; }
        public Nullable<int> BANKAIND { get; set; }
        public Nullable<int> USERNO { get; set; }
        public Nullable<int> MINTAKSITSAYISI { get; set; }
        public Nullable<int> MAXTAKSITSAYISI { get; set; }
        public Nullable<bool> AKTIF { get; set; }
        public string BANKAKARTADI { get; set; }
        public string PUANKARTADI { get; set; }
        public string DIGERKARTADI { get; set; }
        public string BANKAMATIKKARTADI { get; set; }
    }
}
