//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0114D0011TBLIHRACATDETAY
    {
        public int IND { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public Nullable<int> BELGEIND { get; set; }
        public Nullable<int> BELGEIZAHAT { get; set; }
        public Nullable<int> HAREKETIND { get; set; }
        public string GTIP { get; set; }
        public string TESLIMSARTI { get; set; }
        public string PAKETCINSI { get; set; }
        public string PAKETNUMARASI { get; set; }
        public string PAKETMARKASI { get; set; }
        public string TESLIMADRESI { get; set; }
        public string GUMRUKTAKIPNO { get; set; }
        public string ODEMEYAPILACAKHESAPNO { get; set; }
        public string ODEMESEKLI { get; set; }
        public string ODEMEKANALI { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public string TASIMASEKLI { get; set; }
        public Nullable<decimal> PAKETMIKTARI { get; set; }
        public string ODEMEULKE { get; set; }
        public string ODEMESEHIR { get; set; }
        public string ODEMEILCE { get; set; }
        public string ODEMEKOY { get; set; }
        public string ODEMECADDE { get; set; }
        public string ODEMEPOSTAKODU { get; set; }
        public string ODEMEBINAADI { get; set; }
        public string ODEMEBINANO { get; set; }
        public string ODEMEKAPINO { get; set; }
    }
}
