//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0114TBLPERAILE
    {
        public int IND { get; set; }
        public Nullable<int> PERSONELIND { get; set; }
        public string KANGRUBU { get; set; }
        public string MESLEGI { get; set; }
        public string TAHSILI { get; set; }
        public string CINSIYET { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string ADRES { get; set; }
        public Nullable<int> IL { get; set; }
        public string ILCE { get; set; }
        public string POSTAKOD { get; set; }
        public string ALANKODU1 { get; set; }
        public string ALANKODU2 { get; set; }
        public string TELEFON1 { get; set; }
        public string TELEFON2 { get; set; }
        public string BABAADI { get; set; }
        public string ANAADI { get; set; }
        public Nullable<System.DateTime> DOGUMTARIHI { get; set; }
        public string DOGUMYERI { get; set; }
        public string YAKINLIK { get; set; }
        public string MERNISNO { get; set; }
        public string UYRUGU { get; set; }
        public Nullable<System.DateTime> OKULKAYITTARIHI { get; set; }
        public string OKULADI { get; set; }
        public string OKULSINIFI { get; set; }
        public string VELAYETSEKLI { get; set; }
    }
}
