//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0114TBLOTSGRSMEMUSTERILISTESI
    {
        public int IND { get; set; }
        public Nullable<int> KODU { get; set; }
        public Nullable<int> PROFORMABELGEREF { get; set; }
        public Nullable<int> CALISANSAYISI { get; set; }
        public Nullable<int> TBLCARIREF { get; set; }
        public Nullable<int> PERSONELREF { get; set; }
        public Nullable<int> TBLOTSSEKTORLERLISTESIREF { get; set; }
        public Nullable<int> TBLOTSGELIRARALIGILISTESIREF { get; set; }
        public Nullable<int> TBLOTSEGITIMDERECESILISTESIREF { get; set; }
        public Nullable<int> TBLOTSMESLEKLERLISTESIREF { get; set; }
        public Nullable<System.DateTime> GORUSMETARIHI { get; set; }
        public string ACIKLAMA { get; set; }
        public string ADRES { get; set; }
        public Nullable<bool> ETIKET6 { get; set; }
        public Nullable<bool> ETIKET7 { get; set; }
        public Nullable<bool> ETIKET8 { get; set; }
        public Nullable<bool> ETIKET9 { get; set; }
        public Nullable<bool> ETIKET10 { get; set; }
        public string ADI { get; set; }
        public string SOYADI { get; set; }
        public string TELEFON { get; set; }
        public string FAKS { get; set; }
        public string EPOSTA { get; set; }
        public string ISLETMETIPI { get; set; }
        public string GORUSMESONUCU { get; set; }
        public string CINSIYETI { get; set; }
        public string FIRMAADI { get; set; }
        public string ETIKET1 { get; set; }
        public string ETIKET2 { get; set; }
        public string ETIKET3 { get; set; }
        public string ETIKET4 { get; set; }
        public string ETIKET5 { get; set; }
    }
}
