//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0111TBLUREVARDIYATAKVIMI
    {
        public int IND { get; set; }
        public Nullable<int> VIND { get; set; }
        public Nullable<int> TIP { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
    }
}
