//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0111D0013TBLPLUGYOLCUBERABERDETAY
    {
        public int IND { get; set; }
        public Nullable<int> BELGEIND { get; set; }
        public Nullable<int> BELGEIZAHAT { get; set; }
        public Nullable<System.DateTime> PASAPORTTARIHI { get; set; }
        public string PASAPORTNO { get; set; }
        public string ARACIKURUMETIKET { get; set; }
        public string ARACIKURUMVKN { get; set; }
        public string ARACIKURUMADI { get; set; }
        public string ADI { get; set; }
        public string SOYADI { get; set; }
        public string ULKE { get; set; }
    }
}
