//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0112D0003TBLOPTKURUMINDIRIM
    {
        public int IND { get; set; }
        public Nullable<int> KURUMIND { get; set; }
        public Nullable<int> CLYNUM { get; set; }
        public Nullable<int> NITELIK { get; set; }
        public Nullable<decimal> CAP { get; set; }
        public Nullable<decimal> CLYMIN { get; set; }
        public Nullable<decimal> CLYMAX { get; set; }
        public Nullable<decimal> INDIRIM { get; set; }
    }
}
