//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0114TBLTXTAKIMITEMS
    {
        public int IND { get; set; }
        public Nullable<int> TAKIMNO { get; set; }
        public Nullable<int> UNITENO { get; set; }
        public Nullable<int> MODELNO { get; set; }
        public Nullable<int> MIKTAR { get; set; }
    }
}
