//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0112D0003TBLTXTAKIMHAREKET
    {
        public int IND { get; set; }
        public Nullable<int> TAKIMNO { get; set; }
        public Nullable<int> HAREKETNO { get; set; }
        public Nullable<int> BELGETIPI { get; set; }
        public Nullable<int> HAREKETTIPI { get; set; }
        public Nullable<decimal> TAKIMCRC { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
    }
}
