//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0111TBLCRMURUNOZELLIKLERI
    {
        public int IND { get; set; }
        public Nullable<int> CRMGORUSMEBASLIKREF { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public Nullable<int> GSATIRNO { get; set; }
        public string OZELLIK { get; set; }
        public Nullable<bool> OZELALAN1 { get; set; }
        public string URUN { get; set; }
        public string OZELLIKADI { get; set; }
        public string ACIKLAMA2 { get; set; }
    }
}
