//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0111D0015TBLMOBISEMRISUREC
    {
        public int IND { get; set; }
        public Nullable<int> BASLIKIND { get; set; }
        public Nullable<int> FISIZAHAT { get; set; }
        public Nullable<int> FISIND { get; set; }
        public Nullable<System.DateTime> ISLEMTARIHI { get; set; }
        public Nullable<decimal> GONDERILENMIKTAR { get; set; }
        public Nullable<decimal> GELENMIKTAR { get; set; }
        public Nullable<decimal> KALANMIKTAR { get; set; }
        public string SUREC { get; set; }
        public string AYRILMIS4 { get; set; }
        public string AYRILMIS5 { get; set; }
        public string AYRILMIS6 { get; set; }
        public string AYRILMIS7 { get; set; }
        public string AYRILMIS8 { get; set; }
        public string AYRILMIS9 { get; set; }
        public string AYRILMIS { get; set; }
        public string AYRILMIS1 { get; set; }
        public string AYRILMIS2 { get; set; }
        public string AYRILMIS3 { get; set; }
    }
}
