//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0111D0013TBLMOBSIPARISHAREKET
    {
        public int IND { get; set; }
        public Nullable<int> BASLIKNO { get; set; }
        public Nullable<int> RECETEIND { get; set; }
        public Nullable<int> BASLIKIND { get; set; }
        public Nullable<int> STOKSABLONNO { get; set; }
        public Nullable<bool> KATALOG { get; set; }
        public Nullable<decimal> HACIMKATSAYI { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<decimal> HACIM { get; set; }
        public Nullable<decimal> GUC { get; set; }
        public Nullable<decimal> DETAYMIKTAR { get; set; }
        public string RECETENO { get; set; }
        public string MAMULKODU { get; set; }
        public string MAMULADI { get; set; }
        public string ACIKLAMA { get; set; }
        public string NOT1 { get; set; }
        public string NOT2 { get; set; }
        public string STOKSABLONADI { get; set; }
    }
}
