//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0111TBLPERKIBRISDIZI2
    {
        public int IND { get; set; }
        public Nullable<int> BELGEIND { get; set; }
        public Nullable<int> SIRANO { get; set; }
        public Nullable<System.DateTime> ISEGIRISTARIHI { get; set; }
        public string ADI { get; set; }
        public string SOYADI { get; set; }
        public string CINSIYETI { get; set; }
        public string KIMLIKNO { get; set; }
        public string IHTIYATSANDIKNO { get; set; }
    }
}
