//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0114TBLIZIN
    {
        public int IND { get; set; }
        public Nullable<int> PERSONELIND { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<System.DateTime> BASLANGICTARIHI { get; set; }
        public Nullable<System.DateTime> BITISTARIHI { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<int> GUNSAYISI { get; set; }
        public Nullable<bool> UCRETSIZ { get; set; }
        public Nullable<System.DateTime> BSLSAAT { get; set; }
        public Nullable<System.DateTime> BTSSAAT { get; set; }
        public Nullable<decimal> IZINLISAAT { get; set; }
        public Nullable<bool> YILLIK { get; set; }
        public Nullable<int> RESMITATIL { get; set; }
        public Nullable<bool> PAZARDAHIL { get; set; }
    }
}
