//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0111TBLBEYMUHBILG
    {
        public int IND { get; set; }
        public string MUHSMADSOYAD { get; set; }
        public string MUHSMVERKIMNO { get; set; }
        public string MUHSMVD { get; set; }
        public string MUHSMBAGODA { get; set; }
        public string MUHSMSICILNO { get; set; }
        public string MUHYMADSOYAD { get; set; }
        public string MUHYMVERKIMNO { get; set; }
        public string MUHYMVD { get; set; }
        public string MUHYMBAGODA { get; set; }
        public string MUHYMSICILNO { get; set; }
        public string MUHYMMUHURNO { get; set; }
        public string MUHSMTCKIMLIKNO { get; set; }
        public string MUHSMEPOSTA { get; set; }
        public string MUHYMTCKIMLIKNO { get; set; }
        public string MUHYMEPOSTA { get; set; }
        public string MUHSMAD { get; set; }
        public string MUHSMSOYAD { get; set; }
        public string MUHSMTICSICILNO { get; set; }
        public string MUHSMTELALAN { get; set; }
        public string MUHSMTELEFON { get; set; }
        public string MUHYMAD { get; set; }
        public string MUHYMSOYAD { get; set; }
        public string MUHYMTICSICILNO { get; set; }
        public string MUHYMTELALAN { get; set; }
        public string MUHYMTELEFON { get; set; }
    }
}
