//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0114TBLSTOKLAR
    {
        public int IND { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public string MALINCINSI { get; set; }
        public string STOKKODU { get; set; }
        public Nullable<int> ANABIRIM { get; set; }
        public Nullable<int> BIRIMEX { get; set; }
        public Nullable<int> ALTSEVIYE { get; set; }
        public Nullable<int> KRITIKSEVIYE { get; set; }
        public Nullable<int> USTSEVIYE { get; set; }
        public Nullable<bool> DEPOSEVIYESI { get; set; }
        public string URETICI { get; set; }
        public Nullable<decimal> AYLIKVADE { get; set; }
        public Nullable<int> SERINO { get; set; }
        public Nullable<int> DEPO { get; set; }
        public Nullable<int> STOKGRUBU { get; set; }
        public Nullable<short> GARANTI { get; set; }
        public Nullable<decimal> PRIM { get; set; }
        public Nullable<bool> IPTAL { get; set; }
        public Nullable<int> STOKTIPI { get; set; }
        public Nullable<int> STOKTAKIP { get; set; }
        public Nullable<int> TEMINYERI { get; set; }
        public Nullable<int> RAFOMRU { get; set; }
        public byte[] RESIM { get; set; }
        public Nullable<decimal> KALAN { get; set; }
        public Nullable<decimal> REZERV { get; set; }
        public Nullable<int> SATISKOSULU { get; set; }
        public string KOD1 { get; set; }
        public string KOD2 { get; set; }
        public string KOD3 { get; set; }
        public string KOD4 { get; set; }
        public string KOD5 { get; set; }
        public string KOD6 { get; set; }
        public string KOD7 { get; set; }
        public string KOD8 { get; set; }
        public string KOD9 { get; set; }
        public string KOD10 { get; set; }
        public Nullable<int> TAKSITSAYISI { get; set; }
        public string ISTIHBARAT { get; set; }
        public Nullable<bool> FIYATYOK { get; set; }
        public Nullable<bool> DELETED { get; set; }
        public Nullable<decimal> ALISFIYATI { get; set; }
        public Nullable<System.DateTime> ALISFIYATIDEGISMETARIHI { get; set; }
        public Nullable<decimal> ESKIALISFIYATI { get; set; }
        public Nullable<System.DateTime> SONALISTARIHI { get; set; }
        public Nullable<System.DateTime> SONSATISTARIHI { get; set; }
        public Nullable<System.DateTime> KARTINACILMATARIHI { get; set; }
        public Nullable<int> DEVIRIND { get; set; }
        public Nullable<decimal> MALIYET { get; set; }
        public Nullable<int> KDVGRUBU { get; set; }
        public Nullable<bool> AKTIF { get; set; }
        public Nullable<int> ISCILIKIND { get; set; }
        public Nullable<int> ISCILIKBIRIMIND { get; set; }
        public string ISCILIKACIKLAMA { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<decimal> DALISFIYATI { get; set; }
        public string APB { get; set; }
        public Nullable<decimal> OIV { get; set; }
        public Nullable<decimal> KARORANI { get; set; }
        public Nullable<decimal> OTV { get; set; }
        public Nullable<decimal> ISK { get; set; }
        public string STOKGRUPTANIMI { get; set; }
        public Nullable<decimal> ISKSATISFIYATI2 { get; set; }
        public Nullable<decimal> ISKSATISFIYATI3 { get; set; }
        public Nullable<int> ALISKDVORANI { get; set; }
        public Nullable<decimal> ALISISKORANI { get; set; }
        public Nullable<bool> SIPARISALINMASIN { get; set; }
        public Nullable<bool> SIPARISVERILMESIN { get; set; }
        public string P1 { get; set; }
        public string P2 { get; set; }
        public string P3 { get; set; }
        public Nullable<decimal> DEFAULTALISFIYATI { get; set; }
        public Nullable<System.DateTime> DEFAULTALISFIYATIDEGISMESTARIHI { get; set; }
        public Nullable<int> KDVGRUBUT { get; set; }
        public Nullable<decimal> HEDEFSATISFIAYTI { get; set; }
        public Nullable<decimal> KURUMISKONTOSU { get; set; }
        public Nullable<decimal> TICARIISKONTO { get; set; }
        public Nullable<bool> ITSBILDIRIMI { get; set; }
        public Nullable<bool> ACILSEVK { get; set; }
        public Nullable<bool> SOGUKSEVK { get; set; }
        public string ICMIKTAR { get; set; }
        public string TICARISEKIL { get; set; }
        public Nullable<decimal> MAXISKORANI { get; set; }
        public Nullable<decimal> IMALATCISATISFIYATI { get; set; }
        public Nullable<decimal> DKUR { get; set; }
        public Nullable<decimal> MAXISKTUTAR { get; set; }
        public Nullable<decimal> TAXE { get; set; }
        public string KOD11 { get; set; }
        public string DAPB { get; set; }
        public Nullable<bool> IKINCIEL { get; set; }
        public Nullable<bool> ETICARET { get; set; }
        public Nullable<int> STOKNEVI { get; set; }
        public Nullable<bool> OTVORANSAL { get; set; }
        public string PLAKA { get; set; }
        public Nullable<decimal> KM { get; set; }
        public string POZ { get; set; }
        public Nullable<bool> YAZARKASA { get; set; }
        public string KOD12 { get; set; }
        public string KOD13 { get; set; }
        public string KOD14 { get; set; }
        public string KOD15 { get; set; }
        public string KOD16 { get; set; }
        public string KOD17 { get; set; }
        public string KOD18 { get; set; }
        public string KOD19 { get; set; }
        public string KOD20 { get; set; }
        public string KOD21 { get; set; }
        public string UID { get; set; }
        public Nullable<int> UTSBILDIRIMI { get; set; }
        public Nullable<int> MENSEIIND { get; set; }
        public string CPAREV { get; set; }
        public Nullable<System.DateTime> GUNCELLEMETARIHI { get; set; }
        public Nullable<decimal> ISKSATISFIYATI4 { get; set; }
        public Nullable<decimal> ISKSATISFIYATI5 { get; set; }
        public Nullable<decimal> ISKSATISFIYATI6 { get; set; }
    }
}
