//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0114D0011VTBLNAKITAKISRAPORU
    {
        public Nullable<System.Guid> TEKIL { get; set; }
        public string SINIF { get; set; }
        public int IND { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<int> ISLEM { get; set; }
        public Nullable<int> ISLEMTIPI { get; set; }
        public string BASLIKOZELKOD1 { get; set; }
        public string BASLIKOZELKOD2 { get; set; }
        public string BASLIKOZELKOD3 { get; set; }
        public string BASLIKOZELKOD4 { get; set; }
        public string BASLIKOZELKOD5 { get; set; }
        public string BASLIKOZELKOD6 { get; set; }
        public string BASLIKOZELKOD7 { get; set; }
        public string BASLIKOZELKOD8 { get; set; }
        public string BASLIKOZELKOD9 { get; set; }
        public Nullable<decimal> TLGELIR { get; set; }
        public Nullable<decimal> TLGIDER { get; set; }
        public Nullable<decimal> DOVIZGELIR { get; set; }
        public Nullable<decimal> DOVIZGIDER { get; set; }
        public Nullable<decimal> DEVREDENTOPLAM { get; set; }
        public string FIRMAKODU { get; set; }
        public string FIRMAADI { get; set; }
        public string BANKAKODU { get; set; }
        public string BANKAADI { get; set; }
        public string BELGENO { get; set; }
        public string ACIKLAMA { get; set; }
        public string PARABIRIMI { get; set; }
        public Nullable<decimal> KUR { get; set; }
        public Nullable<System.DateTime> ISLEMTARIHI { get; set; }
        public string USERNAME { get; set; }
    }
}
