//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0128D0001VDEPOGIRISCIKISFISLERI
    {
        public Nullable<System.Guid> TEKIL { get; set; }
        public int IND { get; set; }
        public string BELGENO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string STOKKODU { get; set; }
        public string MALINCINSI { get; set; }
        public Nullable<int> STOKTIPI { get; set; }
        public Nullable<decimal> GIREN { get; set; }
        public Nullable<decimal> CIKAN { get; set; }
        public string GIRDIGIDEPO { get; set; }
        public string CIKTIGIDEPO { get; set; }
        public Nullable<int> CIKISDEPONO { get; set; }
        public Nullable<int> GIRISDEPONO { get; set; }
        public string ACIKLAMA { get; set; }
        public string OZELKOD1 { get; set; }
        public string OZELKOD2 { get; set; }
        public string OZELKOD3 { get; set; }
        public string OZELKOD4 { get; set; }
        public string OZELKOD5 { get; set; }
        public string OZELKOD6 { get; set; }
        public string OZELKOD7 { get; set; }
        public string OZELKOD8 { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public Nullable<decimal> AFIYATI { get; set; }
        public Nullable<short> BELGETIPI { get; set; }
    }
}
