//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0127TBLKEFILIMITBILGISI
    {
        public int IND { get; set; }
        public Nullable<int> SUBEIND { get; set; }
        public Nullable<decimal> LIMIT1 { get; set; }
        public Nullable<decimal> LIMIT2 { get; set; }
        public Nullable<int> KEFILSAYISI { get; set; }
    }
}
