//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0129D0001TBLG
    {
        public int IND { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public string CESIT { get; set; }
        public string CESITKODU { get; set; }
    }
}
