//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0128D0001TBLBNKVISATAHSILHAREKET
    {
        public int IND { get; set; }
        public Nullable<int> BASLIKNO { get; set; }
        public Nullable<int> PUAN { get; set; }
        public Nullable<int> KOMISYON { get; set; }
        public Nullable<int> ANLASMAHAREKETNO { get; set; }
        public Nullable<int> KOMISYONUYGULAMATIPI { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public string PARABIRIMI { get; set; }
    }
}
