//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0127D0002TBLHESAPSABLONU
    {
        public int IND { get; set; }
        public Nullable<int> LISTEIND { get; set; }
        public Nullable<int> NUMARA { get; set; }
        public Nullable<bool> BORCALACAK { get; set; }
        public string ACIKLAMA { get; set; }
        public string HESAPKODU { get; set; }
        public string HESAPADI { get; set; }
        public string ANAHTAR { get; set; }
    }
}
