//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0127D0002TBLPLUGETGB
    {
        public int IND { get; set; }
        public Nullable<int> BELGEIND { get; set; }
        public Nullable<int> BELGEIZAHAT { get; set; }
        public Nullable<decimal> GUMRUKCIKISKURU { get; set; }
        public Nullable<System.DateTime> GUMRUKCIKISTARIHI { get; set; }
        public string BELGENO { get; set; }
    }
}
