//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0129TBLKKTESTBASLIK
    {
        public int IND { get; set; }
        public Nullable<int> KATEGORINO { get; set; }
        public string AMAC { get; set; }
        public string TESTADI { get; set; }
    }
}
