//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0128D0001TBLBELGELEME
    {
        public int IND { get; set; }
        public Nullable<int> IZAHAT { get; set; }
        public Nullable<int> BELGEIND { get; set; }
        public Nullable<int> SOURCEIND { get; set; }
        public Nullable<int> SOURCEIZAHAT { get; set; }
        public Nullable<int> KONSOLIDE { get; set; }
        public Nullable<System.DateTime> SOURCETARIH { get; set; }
        public string SOURCEBELGENO { get; set; }
    }
}
