//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0127D0002TBLALFATBASLIK
    {
        public Nullable<short> MASRAFKDV1 { get; set; }
        public Nullable<short> MASRAFKDV2 { get; set; }
        public Nullable<short> MASRAFKDV3 { get; set; }
        public Nullable<short> MASRAFKDV4 { get; set; }
        public Nullable<short> BELGETIPI { get; set; }
        public Nullable<short> EKBELGETIPI { get; set; }
        public int IND { get; set; }
        public Nullable<int> EFATURASTATE { get; set; }
        public Nullable<int> KAYNAK { get; set; }
        public Nullable<int> HAREKETDEPOSU { get; set; }
        public Nullable<int> ODEMEOPSIYONU { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> ENTEGRE { get; set; }
        public Nullable<int> USERNO { get; set; }
        public Nullable<int> SATISSEKLI { get; set; }
        public Nullable<int> KONSOLIDE { get; set; }
        public Nullable<int> FIRMANO { get; set; }
        public Nullable<int> OZELKOD { get; set; }
        public Nullable<int> DEPO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<System.DateTime> CREDATE { get; set; }
        public Nullable<System.DateTime> LADATE { get; set; }
        public Nullable<System.DateTime> ODEMETARIHI { get; set; }
        public Nullable<System.DateTime> ALTBELGETARIHI { get; set; }
        public string PESINFIRMAADI { get; set; }
        public string PESINADRES { get; set; }
        public string ALTNOT { get; set; }
        public Nullable<bool> KDV { get; set; }
        public Nullable<bool> AK { get; set; }
        public Nullable<bool> STOKHAREKETEYAZ { get; set; }
        public Nullable<bool> CARIHAREKETEYAZ { get; set; }
        public Nullable<bool> IRSALIYELIFATURA { get; set; }
        public Nullable<bool> YAZARKASAFISI { get; set; }
        public Nullable<bool> EFATURA { get; set; }
        public Nullable<bool> YURTDISI { get; set; }
        public Nullable<bool> MUHASEBELESMEYECEK { get; set; }
        public Nullable<bool> GIRIS { get; set; }
        public Nullable<bool> SELECTED { get; set; }
        public Nullable<bool> ALLOWYUVARLAMA { get; set; }
        public Nullable<bool> IADE { get; set; }
        public Nullable<bool> IPTAL { get; set; }
        public Nullable<bool> CONVERTED { get; set; }
        public Nullable<bool> SUCCESS { get; set; }
        public Nullable<bool> ENVANTERUPDATE { get; set; }
        public Nullable<bool> ODMODIFIED { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<decimal> TEVKIFATORAN { get; set; }
        public Nullable<decimal> KDVISK { get; set; }
        public Nullable<decimal> ARATOPLAM { get; set; }
        public Nullable<decimal> MASRAF3 { get; set; }
        public Nullable<decimal> MASRAF4 { get; set; }
        public Nullable<decimal> MASRAF1 { get; set; }
        public Nullable<decimal> MASRAF2 { get; set; }
        public Nullable<decimal> KUR { get; set; }
        public Nullable<decimal> YUVARLAMA { get; set; }
        public Nullable<decimal> ODENEN { get; set; }
        public Nullable<decimal> KALEM4 { get; set; }
        public Nullable<decimal> KALEM1 { get; set; }
        public Nullable<decimal> KALEM2 { get; set; }
        public Nullable<decimal> KALEM3 { get; set; }
        public Nullable<decimal> ALT2 { get; set; }
        public Nullable<decimal> ALT3 { get; set; }
        public Nullable<decimal> ALT4 { get; set; }
        public Nullable<decimal> ALT1 { get; set; }
        public string FIRMAADI { get; set; }
        public string BELGENO { get; set; }
        public string OZELKOD9 { get; set; }
        public string ALAN2 { get; set; }
        public string EFATURANO { get; set; }
        public string EFATURAUUID { get; set; }
        public string EFATURANUMBER { get; set; }
        public string OZELKOD5 { get; set; }
        public string OZELKOD6 { get; set; }
        public string OZELKOD7 { get; set; }
        public string OZELKOD8 { get; set; }
        public string ALAN1 { get; set; }
        public string OZELKOD4 { get; set; }
        public string PESINVERGIDAIRESI { get; set; }
        public string PESINVERGINO { get; set; }
        public string OZELKOD3 { get; set; }
        public string PARABIRIMI { get; set; }
        public string OZELKOD1 { get; set; }
        public string OZELKOD2 { get; set; }
        public string ALTBELGENO { get; set; }
        public string UID { get; set; }
        public Nullable<int> IntegrationFolder { get; set; }
        public Nullable<int> SENTSTATUS { get; set; }
        public string PESINMAIL { get; set; }
    }
}
