//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0128TBLOTSTALEDUROZELLIK
    {
        public int IND { get; set; }
        public Nullable<int> GORUSMEREF { get; set; }
        public Nullable<int> KAPISAYISI { get; set; }
        public Nullable<bool> SUNROOF { get; set; }
        public Nullable<bool> YOLBILGISAYARI { get; set; }
        public Nullable<bool> ALARMSISTEMI { get; set; }
        public string MARKA { get; set; }
        public string MOTORTIPI { get; set; }
        public string RENK { get; set; }
        public string VITES { get; set; }
        public string DOSEME { get; set; }
    }
}
