//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0128D0001VHSSTOKHAREKETLERI
    {
        public int IND { get; set; }
        public Nullable<int> FIRMANO { get; set; }
        public Nullable<int> EVRAKNO { get; set; }
        public Nullable<decimal> MASRAF { get; set; }
        public Nullable<decimal> INDIRIM { get; set; }
        public Nullable<decimal> HURDAINDIRIMI { get; set; }
        public Nullable<decimal> GUMRUKVERGISI { get; set; }
        public Nullable<decimal> DIGERVERGILER { get; set; }
        public Nullable<decimal> OTV { get; set; }
        public Nullable<decimal> OIV { get; set; }
        public Nullable<short> BELGETIPI { get; set; }
        public Nullable<int> SATISKOSULU { get; set; }
        public Nullable<int> DETAY { get; set; }
        public Nullable<decimal> ISK1 { get; set; }
        public Nullable<decimal> ISK2 { get; set; }
        public Nullable<decimal> ISK3 { get; set; }
        public Nullable<decimal> ISK4 { get; set; }
        public Nullable<decimal> GERCEKTOPLAM { get; set; }
        public Nullable<double> SONGERCEKTOPLAM { get; set; }
        public int BASIND { get; set; }
        public Nullable<int> BIRIMEX { get; set; }
        public Nullable<decimal> KUR { get; set; }
        public Nullable<int> STOKTIPI { get; set; }
        public Nullable<short> KDV { get; set; }
        public Nullable<decimal> BIRIMFIYAT { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public string ACIKLAMA { get; set; }
        public string PARABIRIMI { get; set; }
        public string BELGENO { get; set; }
        public Nullable<decimal> BIRIMMALIYET { get; set; }
    }
}
