//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0128TBLAYRILMABLD
    {
        public Nullable<short> COCUKSAY { get; set; }
        public int IND { get; set; }
        public Nullable<int> SUBEIND { get; set; }
        public Nullable<int> YIL { get; set; }
        public Nullable<int> AY { get; set; }
        public Nullable<int> PERSONELIND { get; set; }
        public Nullable<int> SAKATDER { get; set; }
        public Nullable<int> PRIM5 { get; set; }
        public Nullable<int> PRIM6 { get; set; }
        public Nullable<int> TOPPRIMGUN { get; set; }
        public Nullable<int> PRIM1 { get; set; }
        public Nullable<int> PRIM2 { get; set; }
        public Nullable<int> PRIM3 { get; set; }
        public Nullable<int> PRIM4 { get; set; }
        public Nullable<int> YIL5 { get; set; }
        public Nullable<int> YIL6 { get; set; }
        public Nullable<int> YIL1 { get; set; }
        public Nullable<int> YIL2 { get; set; }
        public Nullable<int> YIL3 { get; set; }
        public Nullable<int> YIL4 { get; set; }
        public Nullable<int> DEVREDENISGUNU { get; set; }
        public Nullable<int> ONISILI { get; set; }
        public Nullable<int> IL { get; set; }
        public Nullable<int> DEPARTMAN { get; set; }
        public Nullable<int> SBIL { get; set; }
        public Nullable<int> SBPARAMETREIND { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<System.DateTime> TEBLIGTARIHI { get; set; }
        public Nullable<System.DateTime> DOGUMTARIHI { get; set; }
        public Nullable<System.DateTime> ISTENCIKISTARIHI { get; set; }
        public Nullable<System.DateTime> ISEGIRISTARIHI { get; set; }
        public Nullable<System.DateTime> SBBASLAMATARIHI { get; set; }
        public Nullable<bool> SECIM { get; set; }
        public Nullable<bool> IHBARYAPILDI { get; set; }
        public Nullable<bool> YAZDIRILDI { get; set; }
        public Nullable<decimal> SONUCRET { get; set; }
        public Nullable<decimal> PTUTAR4 { get; set; }
        public Nullable<decimal> PTUTAR5 { get; set; }
        public Nullable<decimal> PTUTAR6 { get; set; }
        public Nullable<decimal> PTUTAR1 { get; set; }
        public Nullable<decimal> PTUTAR2 { get; set; }
        public Nullable<decimal> PTUTAR3 { get; set; }
        public string ACIKLAMA { get; set; }
        public string SANDIKSICIL { get; set; }
        public string ISKURADI { get; set; }
        public string NEDEN4 { get; set; }
        public string NEDEN5 { get; set; }
        public string NEDEN6 { get; set; }
        public string SANDIKAD { get; set; }
        public string NEDEN1 { get; set; }
        public string NEDEN2 { get; set; }
        public string NEDEN3 { get; set; }
        public string AY5 { get; set; }
        public string AY6 { get; set; }
        public string AY1 { get; set; }
        public string AY2 { get; set; }
        public string AY3 { get; set; }
        public string AY4 { get; set; }
        public string ONISUNVANI { get; set; }
        public string ONISADRESI { get; set; }
        public string ANAADI { get; set; }
        public string DOGUMYERI { get; set; }
        public string TELEFON1 { get; set; }
        public string ALANKODU2 { get; set; }
        public string TELEFON2 { get; set; }
        public string ALANKODU3 { get; set; }
        public string FAX { get; set; }
        public string BABAADI { get; set; }
        public string SOYAD { get; set; }
        public string ADRES { get; set; }
        public string ILCE { get; set; }
        public string POSTAKOD { get; set; }
        public string ALANKODU1 { get; set; }
        public string MEDENIHAL { get; set; }
        public string MALULLUK { get; set; }
        public string CIKISNEDENI { get; set; }
        public string AD { get; set; }
        public string ILKTEKRAR { get; set; }
        public string SIGORTABLDTIPI { get; set; }
        public string GOREVI { get; set; }
        public string SSKSICILNO { get; set; }
        public string CINSIYET { get; set; }
        public string PERTIP { get; set; }
        public string UYRUGU { get; set; }
        public string KANGRUBU { get; set; }
        public string MESLEGI { get; set; }
        public string TAHSILI { get; set; }
        public string EHLIYET { get; set; }
        public string SBTSOKAYITNO { get; set; }
        public string SBTSVKAYITNO { get; set; }
        public string SBISVAD { get; set; }
        public string SBISVSOYAD { get; set; }
        public string KIMLIKNO { get; set; }
        public string SBCBSICILNO1 { get; set; }
        public string SBCBSICILNO2 { get; set; }
        public string SBCBSICILNO3 { get; set; }
        public string SBCBSICILNO4 { get; set; }
        public string SBTABIOLDUGUSEKTOR { get; set; }
        public string SBFAX { get; set; }
        public string SBSSKISKOLU { get; set; }
        public string SBCALISMAKONUSU { get; set; }
        public string SBVERGIDAIRESI { get; set; }
        public string SBVERGINO { get; set; }
        public string SBSSKSICILNO { get; set; }
        public string SBILCE { get; set; }
        public string SBPOSTAKOD { get; set; }
        public string SBALANKODU1 { get; set; }
        public string SBTELEFON1 { get; set; }
        public string SBALANKODU3 { get; set; }
        public string AD1 { get; set; }
        public string AD2 { get; set; }
        public string SUBEAD { get; set; }
        public string SBADRES { get; set; }
    }
}
