//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0128D0001TBLKASA
    {
        public int IND { get; set; }
        public Nullable<int> ISLEM { get; set; }
        public Nullable<int> KAYNAKTRANSFERIND { get; set; }
        public Nullable<int> ENTEGRE { get; set; }
        public Nullable<int> BELGELINK { get; set; }
        public Nullable<int> BELGEIZAHAT { get; set; }
        public Nullable<int> LINELINK { get; set; }
        public Nullable<int> USERNO { get; set; }
        public Nullable<int> ISLEMTIPI { get; set; }
        public Nullable<int> KASAMUHASEBEKODU { get; set; }
        public Nullable<int> HEDEFMUHASEBEKODU { get; set; }
        public Nullable<int> BORDRONO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<System.DateTime> ISLEMTARIHI { get; set; }
        public Nullable<bool> KDVDAHIL { get; set; }
        public Nullable<bool> TRANSFER { get; set; }
        public Nullable<bool> SELECTED { get; set; }
        public Nullable<decimal> GELIR { get; set; }
        public Nullable<decimal> GIDER { get; set; }
        public Nullable<decimal> KUR { get; set; }
        public string PARABIRIMI { get; set; }
        public string KASAMUHHESAPKODU { get; set; }
        public string EVRAKNO { get; set; }
        public string SUBEADI { get; set; }
        public string KASAADI { get; set; }
        public string ISLEMMUHHESAPKODU { get; set; }
        public string KDVMUHHESAPKODU { get; set; }
        public string ACIKLAMA { get; set; }
        public string BELGENEVI { get; set; }
    }
}
