//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0128TBLOTSIKINCIEL
    {
        public int IND { get; set; }
        public Nullable<int> EL { get; set; }
        public Nullable<int> HASARDERECESI { get; set; }
        public Nullable<int> KOMISYONTIPI { get; set; }
        public Nullable<int> ARACLISTREF { get; set; }
        public Nullable<System.DateTime> MGECTARIH { get; set; }
        public Nullable<System.DateTime> MUTARIH { get; set; }
        public Nullable<System.DateTime> TESCILTARIHI { get; set; }
        public string ADRES { get; set; }
        public string HASARACIKLAMA { get; set; }
        public string DONANIM { get; set; }
        public string ARACUSTHAK { get; set; }
        public Nullable<bool> YOLCUNAKLI { get; set; }
        public Nullable<bool> YUKNAKLI { get; set; }
        public Nullable<bool> BENZINLI { get; set; }
        public Nullable<bool> DIZEL { get; set; }
        public Nullable<bool> EURO93 { get; set; }
        public Nullable<bool> RESMI { get; set; }
        public Nullable<bool> TICARI { get; set; }
        public Nullable<bool> HUSUSI { get; set; }
        public Nullable<decimal> KM { get; set; }
        public Nullable<decimal> KOMORANTUTAR { get; set; }
        public Nullable<decimal> SFIYATI { get; set; }
        public string ADISOYADI { get; set; }
        public string BABAADI { get; set; }
        public string DOGUMYERYIL { get; set; }
        public string NUFUSILILCE { get; set; }
        public string VERILENILILCE { get; set; }
        public string PB { get; set; }
        public string MHRCMAKBUZNO { get; set; }
        public string MISTASYON { get; set; }
        public string TESCILSIRANO { get; set; }
        public string IMALATI { get; set; }
        public string ROMORK { get; set; }
        public string TAKOGRAF { get; set; }
        public string TAKSIMETRE { get; set; }
    }
}
