//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0128TBLPERPRIMHIZMET2
    {
        public Nullable<short> GUNADET { get; set; }
        public Nullable<short> IZINGUN { get; set; }
        public int IND { get; set; }
        public Nullable<int> PERSONELIND { get; set; }
        public Nullable<int> PRIMIND { get; set; }
        public Nullable<int> EKSIKGUN { get; set; }
        public Nullable<System.DateTime> CIKISTARIH { get; set; }
        public Nullable<System.DateTime> GIRISTARIH { get; set; }
        public Nullable<bool> DEGISIKLIK { get; set; }
        public Nullable<decimal> IKRAMIYE { get; set; }
        public Nullable<decimal> PRIMKAZANC { get; set; }
        public Nullable<decimal> IZINUCRET { get; set; }
        public string SSKSICILNO { get; set; }
        public string TCKIMLIKNO { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string MESLEKKOD { get; set; }
        public string EKSIKGUNNEDEN { get; set; }
        public string CIKISNEDEN { get; set; }
        public string BELGETURU { get; set; }
        public string KANUNNO { get; set; }
        public string ILKAD { get; set; }
    }
}
