//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0128D0001TBLSMTALEPBASLIK
    {
        public int IND { get; set; }
        public Nullable<int> PERSONELNO { get; set; }
        public Nullable<int> POZISYONNO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<bool> IPTAL { get; set; }
        public string BELGENO { get; set; }
        public string ACIKLAMA { get; set; }
        public string GUID { get; set; }
    }
}
