//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0128D0001TBLMOBRECETEHAREKET
    {
        public int IND { get; set; }
        public Nullable<int> MALZEMETIPI { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public Nullable<int> SIRANO { get; set; }
        public Nullable<int> ILGILISUREC { get; set; }
        public Nullable<int> BIRIMEX { get; set; }
        public Nullable<int> BASLIKNO { get; set; }
        public Nullable<bool> EDT { get; set; }
        public Nullable<bool> FONT { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<decimal> BIRIMFIYAT { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public string MALZEMEKONUMU { get; set; }
        public string MALZEMEKODU { get; set; }
        public string MALZEMEADI { get; set; }
        public string BIRIMADI { get; set; }
        public string ALTERNATIFSTOKLAR { get; set; }
        public string ALTERNATIFSTOKLARKOD { get; set; }
    }
}
