//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0128TBLPHESAP
    {
        public Nullable<short> COCUKSAY { get; set; }
        public int IND { get; set; }
        public Nullable<int> SUBEIND { get; set; }
        public Nullable<int> PERSONELIND { get; set; }
        public Nullable<int> BORDROIND { get; set; }
        public Nullable<int> EKSIKGUN { get; set; }
        public Nullable<int> YILLIKIZIN { get; set; }
        public Nullable<int> UCRETSIZ { get; set; }
        public Nullable<System.DateTime> ISTENCIKISTARIHI { get; set; }
        public Nullable<System.DateTime> MAASODEMETARIHI { get; set; }
        public Nullable<System.DateTime> ISEGIRISTARIHI { get; set; }
        public Nullable<bool> SECIM { get; set; }
        public Nullable<bool> SSKKESINTI { get; set; }
        public Nullable<bool> IHBARYAPILDI { get; set; }
        public Nullable<decimal> NETKESINTI10 { get; set; }
        public Nullable<decimal> KIDEMEKLENTITOP { get; set; }
        public Nullable<decimal> NETKESINTI4 { get; set; }
        public Nullable<decimal> NETKESINTI5 { get; set; }
        public Nullable<decimal> NETKESINTI6 { get; set; }
        public Nullable<decimal> NETKESINTI7 { get; set; }
        public Nullable<decimal> NETKESINTI8 { get; set; }
        public Nullable<decimal> NETKESINTI9 { get; set; }
        public Nullable<decimal> EKSIKCALISMASAAT { get; set; }
        public Nullable<decimal> NETKESINTITOP { get; set; }
        public Nullable<decimal> NETKESINTI1 { get; set; }
        public Nullable<decimal> NETKESINTI2 { get; set; }
        public Nullable<decimal> NETKESINTI3 { get; set; }
        public Nullable<decimal> ISVERENTESVIK { get; set; }
        public Nullable<decimal> GELIRVERGISIMUAFIYETI { get; set; }
        public Nullable<decimal> DEVREDENIKRAMIYE { get; set; }
        public Nullable<decimal> TOPLAMEKSIKCALISMA { get; set; }
        public Nullable<decimal> HAYATSIGORTASI { get; set; }
        public Nullable<decimal> OZELSIGORTA2 { get; set; }
        public Nullable<decimal> BRUTEKLENTITOPLAMI { get; set; }
        public Nullable<decimal> S1AD { get; set; }
        public Nullable<decimal> S2AD { get; set; }
        public Nullable<decimal> KUMULATIFVERGIMATRAHI2 { get; set; }
        public Nullable<decimal> IZINLISAAT { get; set; }
        public Nullable<decimal> UKSAAT { get; set; }
        public Nullable<decimal> UKSAATUCRETI { get; set; }
        public Nullable<decimal> ASGARIGECIMTUTARI { get; set; }
        public Nullable<decimal> ASGARIGECIMORANI { get; set; }
        public Nullable<decimal> ASGARIGECIMMATRAHI { get; set; }
        public Nullable<decimal> SSKTABANFARKI { get; set; }
        public Nullable<decimal> TUMGELTOP { get; set; }
        public Nullable<decimal> UCRETSIZGUN { get; set; }
        public Nullable<decimal> SSKMATRAHI2 { get; set; }
        public Nullable<decimal> OZELSIGORTA { get; set; }
        public Nullable<decimal> ISTISNATOP { get; set; }
        public Nullable<decimal> EKLENTITOP { get; set; }
        public Nullable<decimal> NETEKLENTITOP { get; set; }
        public Nullable<decimal> KESINTITOP { get; set; }
        public Nullable<decimal> DAMGAVMATRAHI { get; set; }
        public Nullable<decimal> TUMKESTOP { get; set; }
        public Nullable<decimal> ISTISNA5 { get; set; }
        public Nullable<decimal> ISTISNA6 { get; set; }
        public Nullable<decimal> ISTISNA7 { get; set; }
        public Nullable<decimal> ISTISNA8 { get; set; }
        public Nullable<decimal> ISTISNA9 { get; set; }
        public Nullable<decimal> ISTISNA10 { get; set; }
        public Nullable<decimal> NETEKLENTI9 { get; set; }
        public Nullable<decimal> NETEKLENTI10 { get; set; }
        public Nullable<decimal> ISTISNA1 { get; set; }
        public Nullable<decimal> ISTISNA2 { get; set; }
        public Nullable<decimal> ISTISNA3 { get; set; }
        public Nullable<decimal> ISTISNA4 { get; set; }
        public Nullable<decimal> NETEKLENTI3 { get; set; }
        public Nullable<decimal> NETEKLENTI4 { get; set; }
        public Nullable<decimal> NETEKLENTI5 { get; set; }
        public Nullable<decimal> NETEKLENTI6 { get; set; }
        public Nullable<decimal> NETEKLENTI7 { get; set; }
        public Nullable<decimal> NETEKLENTI8 { get; set; }
        public Nullable<decimal> EKLENTI7 { get; set; }
        public Nullable<decimal> EKLENTI8 { get; set; }
        public Nullable<decimal> EKLENTI9 { get; set; }
        public Nullable<decimal> EKLENTI10 { get; set; }
        public Nullable<decimal> NETEKLENTI1 { get; set; }
        public Nullable<decimal> NETEKLENTI2 { get; set; }
        public Nullable<decimal> EKLENTI1 { get; set; }
        public Nullable<decimal> EKLENTI2 { get; set; }
        public Nullable<decimal> EKLENTI3 { get; set; }
        public Nullable<decimal> EKLENTI4 { get; set; }
        public Nullable<decimal> EKLENTI5 { get; set; }
        public Nullable<decimal> EKLENTI6 { get; set; }
        public Nullable<decimal> KESINTI5 { get; set; }
        public Nullable<decimal> KESINTI6 { get; set; }
        public Nullable<decimal> KESINTI7 { get; set; }
        public Nullable<decimal> KESINTI8 { get; set; }
        public Nullable<decimal> KESINTI9 { get; set; }
        public Nullable<decimal> KESINTI10 { get; set; }
        public Nullable<decimal> ELEGECEN { get; set; }
        public Nullable<decimal> KESINTI1 { get; set; }
        public Nullable<decimal> KESINTI2 { get; set; }
        public Nullable<decimal> KESINTI3 { get; set; }
        public Nullable<decimal> KESINTI4 { get; set; }
        public Nullable<decimal> HAFTATATILIFAZLACALISMA { get; set; }
        public Nullable<decimal> RESMITATILFAZLACALISMA { get; set; }
        public Nullable<decimal> IZINKULLANILANGUNS { get; set; }
        public Nullable<decimal> TOPLAMFAZLACALISMA { get; set; }
        public Nullable<decimal> CALISILANHAFTATATILI { get; set; }
        public Nullable<decimal> CALISILMAYANRESMITATIL { get; set; }
        public Nullable<decimal> CALISILANRESMITATIL { get; set; }
        public Nullable<decimal> FAZLACALISMA { get; set; }
        public Nullable<decimal> OZELINDIRIM { get; set; }
        public Nullable<decimal> VERGIMATRAHI { get; set; }
        public Nullable<decimal> GELIRVERGISI { get; set; }
        public Nullable<decimal> DAMGAVERGISI { get; set; }
        public Nullable<decimal> KESINTILERTOPLAMI { get; set; }
        public Nullable<decimal> NETMAAS { get; set; }
        public Nullable<decimal> SSKPRIMIISCIPAYI { get; set; }
        public Nullable<decimal> SSKPRIMIISVERENPAYI { get; set; }
        public Nullable<decimal> ISSIZLIKISCIPAYI { get; set; }
        public Nullable<decimal> ISSIZLIKISVERENPAYI { get; set; }
        public Nullable<decimal> DEVREDENVERGIMATRAHI { get; set; }
        public Nullable<decimal> DEVREDENVERGI { get; set; }
        public Nullable<decimal> BRUTMAAS { get; set; }
        public Nullable<decimal> CALISTIGIGUN { get; set; }
        public Nullable<decimal> HAFTATATILI { get; set; }
        public Nullable<decimal> TOPLAMGUN { get; set; }
        public Nullable<decimal> SSKMATRAHI { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string MESLEKKOD { get; set; }
        public string KANUNNO { get; set; }
        public string MERNISNO { get; set; }
        public string CIKISNEDENI { get; set; }
        public string TABANDURUMU { get; set; }
        public string KTIP { get; set; }
        public string SIGORTABLDTIPI { get; set; }
        public string SICILNO { get; set; }
        public string GOREVI { get; set; }
        public string SSKSICILNO { get; set; }
        public string CINSIYET { get; set; }
        public string MEDENIHAL { get; set; }
        public string UCRETNEVI { get; set; }
        public Nullable<decimal> AGIFARKI { get; set; }
        public Nullable<decimal> ZORUNLUBESTUTARI { get; set; }
        public Nullable<decimal> GVISTISNA { get; set; }
        public Nullable<decimal> DVISTISNA { get; set; }
        public Nullable<decimal> SGKISTISNA { get; set; }
        public Nullable<decimal> ISSIZLIKISTISNA { get; set; }
        public Nullable<decimal> KISACALISMABRUTUCRET { get; set; }
        public Nullable<decimal> KISACALISMAISVERENMALIYET { get; set; }
        public Nullable<short> KISACALISMAYANGUN { get; set; }
    }
}
