//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0127D0006TBLSENETGIRIS
    {
        public int IND { get; set; }
        public Nullable<int> LN { get; set; }
        public Nullable<int> SEHIR { get; set; }
        public Nullable<int> FIRMANO { get; set; }
        public Nullable<int> EVRAKNO { get; set; }
        public Nullable<System.DateTime> KESIDETARIHI { get; set; }
        public string ADRES1 { get; set; }
        public string ADRES2 { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public string KESIDEEDEN { get; set; }
        public string TAKIPNO { get; set; }
        public string VERGIDAIRESI { get; set; }
        public string VERGINO { get; set; }
        public string BELGENO { get; set; }
    }
}
