//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0128TBLOTSARACTANIM
    {
        public int IND { get; set; }
        public Nullable<int> TBLOTSMARKATANIMREF { get; set; }
        public Nullable<int> TBLSTOKLARREF { get; set; }
        public Nullable<decimal> OTV { get; set; }
        public string MODEL { get; set; }
        public string TIP { get; set; }
        public string SASIKODU { get; set; }
        public string MOTORKODU { get; set; }
        public string MODELKODU { get; set; }
        public string MARKA { get; set; }
        public string ANAHTARKODU { get; set; }
        public string MODELYILI { get; set; }
    }
}
