//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0127D0002TBLMUHONAY
    {
        public int IND { get; set; }
        public string BASLIK { get; set; }
        public string ANTED { get; set; }
        public string DIPNOT { get; set; }
        public string YEVMIYENO { get; set; }
        public string TARIH { get; set; }
        public string ADISOYADI { get; set; }
        public string UNVANI { get; set; }
        public string MESLEK { get; set; }
        public string VDAIRE { get; set; }
        public string VNO { get; set; }
        public string SICILNO { get; set; }
        public string ADRES { get; set; }
        public string ADRES2 { get; set; }
        public string DEFTER { get; set; }
        public string CIFT { get; set; }
        public string TEK { get; set; }
        public string DONEM { get; set; }
    }
}
