//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0129TBLBEYMUHISYERI
    {
        public int IND { get; set; }
        public Nullable<int> MUHTASARIND { get; set; }
        public Nullable<int> ISCISAYISI { get; set; }
        public string ADRES { get; set; }
        public Nullable<bool> IKIBINSEKIZONCESI { get; set; }
        public string SEHIR { get; set; }
        public string VDKODU { get; set; }
        public string SSKNO { get; set; }
        public string TEBLIGTIPI { get; set; }
        public string ISVERENTIPI { get; set; }
    }
}
