//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0128TBLSEVIYE
    {
        public int IND { get; set; }
        public Nullable<int> SEVIYE1 { get; set; }
        public Nullable<int> SEVIYE2 { get; set; }
        public Nullable<int> SEVIYE3 { get; set; }
        public Nullable<int> SEVIYE4 { get; set; }
        public Nullable<int> SEVIYE5 { get; set; }
        public Nullable<int> SEVIYESAY { get; set; }
        public string AYRAC { get; set; }
    }
}
