//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0127TBLPRIM4A
    {
        public int IND { get; set; }
        public Nullable<int> SUBEIND { get; set; }
        public Nullable<int> AY { get; set; }
        public Nullable<int> AY3IND { get; set; }
        public Nullable<int> AY4IND { get; set; }
        public Nullable<int> YIL { get; set; }
        public Nullable<int> AY1IND { get; set; }
        public Nullable<int> AY2IND { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<bool> YAZDIRILDI { get; set; }
        public Nullable<bool> SECIM { get; set; }
        public string ACIKLAMA { get; set; }
        public string AY3ISIM { get; set; }
        public string AY4ISIM { get; set; }
        public string DONEM { get; set; }
        public string ADRES { get; set; }
        public string AY1ISIM { get; set; }
        public string AY2ISIM { get; set; }
        public string KISAAD { get; set; }
        public string AD1 { get; set; }
        public string AD2 { get; set; }
        public string ISKODU { get; set; }
        public string BORDROTURU { get; set; }
        public string SSKSICILNO { get; set; }
    }
}
