//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0129TBLCARIBANKAHESAPLARI
    {
        public int IND { get; set; }
        public Nullable<int> FIRMANO { get; set; }
        public Nullable<int> BANKANO { get; set; }
        public Nullable<int> SUBENO { get; set; }
        public string HESAPNO { get; set; }
        public string HESAPUNVANI { get; set; }
        public string PARABIRIMI { get; set; }
        public string IBAN { get; set; }
        public string HESAPEKNO { get; set; }
    }
}
