//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0127TBLPERKIBRISDIZI1
    {
        public int IND { get; set; }
        public Nullable<int> AY { get; set; }
        public Nullable<int> YIL { get; set; }
        public Nullable<int> SUBEIND { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string ACIKLAMA { get; set; }
        public string SICILNO { get; set; }
        public string UNVAN { get; set; }
        public string ADRES { get; set; }
        public string TELEFON { get; set; }
    }
}
