//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0129TBLALSSTOKLAR
    {
        public int IND { get; set; }
        public Nullable<int> BASLIKNO { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public Nullable<int> BEDELNO { get; set; }
        public string STOKKODU { get; set; }
        public string MALINCINSI { get; set; }
        public string BEDELADI { get; set; }
    }
}
