//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0129TBLCRMTALEPEDILENURUNLER
    {
        public int IND { get; set; }
        public Nullable<int> ADET { get; set; }
        public Nullable<int> STOKLARREF { get; set; }
        public Nullable<int> CRMGORUSMEBASLIKREF { get; set; }
        public Nullable<int> STOKTIPI { get; set; }
        public Nullable<int> SIRANO { get; set; }
        public Nullable<bool> OZELALAN1 { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
        public string ACIKLAMA { get; set; }
        public string STOKKODU { get; set; }
        public string MALINCINSI { get; set; }
        public string ACIKLAMA2 { get; set; }
    }
}
