//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0127TBLURERECETE
    {
        public int IND { get; set; }
        public Nullable<int> DETAY { get; set; }
        public Nullable<int> EVRAKNO { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public Nullable<int> ARACLINENO { get; set; }
        public Nullable<int> MALIYETTURU { get; set; }
        public Nullable<int> MIKTARTURU { get; set; }
        public Nullable<int> POZISYONNO { get; set; }
        public Nullable<int> CIKISPOZISYONNO { get; set; }
        public Nullable<int> KULLANICI { get; set; }
        public Nullable<int> TUR { get; set; }
        public Nullable<int> DEPONO { get; set; }
        public Nullable<System.DateTime> SONERISIMTARIHI { get; set; }
        public Nullable<System.DateTime> ISLEMTARIHI { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<decimal> FIREORANI { get; set; }
        public Nullable<decimal> ORAN { get; set; }
        public Nullable<decimal> BIRIMMIKTAR { get; set; }
        public Nullable<decimal> KDV { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
        public string STOKKODU { get; set; }
        public string MALINCINSI { get; set; }
        public string KONUM { get; set; }
        public string URETIMCIKISHESAPKODU { get; set; }
        public string YANSITMAHESAPKODU { get; set; }
        public string ACIKLAMA { get; set; }
        public string BIRIM { get; set; }
        public string BARCODE { get; set; }
        public string VARSAYILANBIRIMADI { get; set; }
        public Nullable<decimal> VARSAYILANBIRIMCARPAN { get; set; }
        public Nullable<decimal> DEPOCIKISMIKTARI { get; set; }
        public Nullable<int> STOKTURU { get; set; }
        public Nullable<decimal> RANDIMAN { get; set; }
    }
}
