//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0129TBLPERISLKOD
    {
        public int IND { get; set; }
        public Nullable<int> SUBEIND { get; set; }
        public Nullable<int> DEPARTMANIND { get; set; }
        public Nullable<int> ISLID { get; set; }
        public Nullable<bool> KULLAN { get; set; }
        public string ISLACIKLAMA { get; set; }
        public string ISLKOD { get; set; }
    }
}
