//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0127D0002TBLZIMMETDETAY
    {
        public int IND { get; set; }
        public Nullable<int> FATBELGEIND { get; set; }
        public Nullable<int> FATBELGEIZAHAT { get; set; }
        public Nullable<int> FATHAREKETIND { get; set; }
        public Nullable<int> FATSTOKNO { get; set; }
        public Nullable<int> FATDEPO { get; set; }
        public Nullable<int> ZIMBELGEIND { get; set; }
        public Nullable<int> ZIMBELGEIZAHAT { get; set; }
        public Nullable<int> ZIMHAREKETIND { get; set; }
    }
}
