//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0128D0001TBLCALIS
    {
        public int IND { get; set; }
        public Nullable<int> HIND { get; set; }
        public Nullable<int> RIND { get; set; }
        public Nullable<bool> KONTROLET { get; set; }
        public Nullable<decimal> NESNE { get; set; }
        public Nullable<decimal> OZNE { get; set; }
        public Nullable<decimal> FIIL { get; set; }
        public Nullable<decimal> SABIT { get; set; }
        public string HESAPKODU { get; set; }
        public string IZIN { get; set; }
    }
}
