//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0128TBLKRDKASALAR
    {
        public int IND { get; set; }
        public Nullable<int> SUBENO { get; set; }
        public string SUBEADI { get; set; }
        public string KASAADI { get; set; }
        public string ACIKLAMA { get; set; }
        public string MUHHESAPKODU { get; set; }
        public string PARABIRIMI { get; set; }
    }
}
