//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0129TBLUREANLIKISEMRIHAREKET
    {
        public int IND { get; set; }
        public Nullable<int> BASLIKIND { get; set; }
        public Nullable<int> STOKIND { get; set; }
        public Nullable<int> BIRIMIND { get; set; }
        public Nullable<int> URUNTIPI { get; set; }
        public Nullable<bool> SELECTED { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<decimal> MALIYETORANI { get; set; }
        public Nullable<decimal> ONGORULENRANDIMAN { get; set; }
        public Nullable<decimal> BIRIMCARPANI { get; set; }
        public Nullable<decimal> ADETMIKTAR { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
        public Nullable<decimal> RANDIMAN { get; set; }
        public string STOKKODU { get; set; }
        public string STOKADI { get; set; }
        public string BIRIMADI { get; set; }
    }
}
