//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0127TBLCUBESTOKSATISLISTESI
    {
        public int IND { get; set; }
        public Nullable<int> MUSSIRANO { get; set; }
        public Nullable<int> STOKIND { get; set; }
        public Nullable<int> BIRIMIND { get; set; }
        public Nullable<int> CARIIND { get; set; }
        public Nullable<int> YCEKIIND { get; set; }
        public Nullable<int> BANKAIND { get; set; }
        public Nullable<bool> IADE { get; set; }
        public Nullable<bool> ODENDI { get; set; }
        public Nullable<bool> ODEMETIPI { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<decimal> SATISFIYATI { get; set; }
        public Nullable<decimal> ISKONTO { get; set; }
        public string BARCODE { get; set; }
    }
}
