//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0129TBLBNKKARTANLASMAHAREKET
    {
        public int IND { get; set; }
        public Nullable<int> BASLIKNO { get; set; }
        public Nullable<int> SATISSEKLI { get; set; }
        public Nullable<int> BLOKEGUN { get; set; }
        public Nullable<int> TAHSILATSEKLI { get; set; }
        public Nullable<int> BANKANO { get; set; }
        public Nullable<System.DateTime> BASLANGICTARIHI { get; set; }
        public Nullable<System.DateTime> BITISTARIHI { get; set; }
        public Nullable<bool> VALOR { get; set; }
        public Nullable<decimal> KOMISYON { get; set; }
        public Nullable<decimal> PUAN { get; set; }
        public string KARTADI { get; set; }
        public Nullable<int> TAKSITTIPI { get; set; }
        public Nullable<bool> RESMIVALOR { get; set; }
    }
}
