//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0129D0001TBLOTSBELGEOZELLIKLERI
    {
        public int IND { get; set; }
        public Nullable<int> BELGETIZAHAT { get; set; }
        public Nullable<int> BELGEREF { get; set; }
        public Nullable<bool> OTV { get; set; }
        public Nullable<bool> KDV { get; set; }
        public Nullable<bool> GUMRUKVERGISI { get; set; }
        public Nullable<bool> DIGERVERGILER { get; set; }
        public Nullable<decimal> HURDAINDIRIMI { get; set; }
    }
}
