//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0127D0002VKREDIBORCLUTARAMARAPORU
    {
        public int SIRA { get; set; }
        public Nullable<int> IND { get; set; }
        public Nullable<decimal> BAKIYE { get; set; }
        public Nullable<int> ISLEMIND { get; set; }
        public string SOYADI { get; set; }
        public string ADI { get; set; }
        public string SOYADAD { get; set; }
        public string FIRMAKODU { get; set; }
        public string FIRMAADI { get; set; }
        public Nullable<int> FIRMATIPI { get; set; }
        public Nullable<decimal> GECIKMEFAIZI { get; set; }
        public string KOD1 { get; set; }
        public string KOD2 { get; set; }
        public string KOD3 { get; set; }
        public string KOD4 { get; set; }
        public string KOD5 { get; set; }
        public string TELEFON1 { get; set; }
        public string TELEFON2 { get; set; }
        public string TELEFON3 { get; set; }
        public string GSMNO { get; set; }
        public string KEFIL1 { get; set; }
        public string KEFIL2 { get; set; }
        public Nullable<int> OPSIYON { get; set; }
        public Nullable<bool> SATISYAPILMASIN { get; set; }
        public Nullable<decimal> GECIKMEAY { get; set; }
        public string ISTIHBARAT { get; set; }
        public string ADRESPOSTA { get; set; }
        public string ADRESFATURA { get; set; }
        public string ADRESSEVK { get; set; }
        public string KEFILADRES1 { get; set; }
        public string KEFILADRES2 { get; set; }
        public Nullable<decimal> RISKLIMITI { get; set; }
        public Nullable<decimal> KREDILIMITI { get; set; }
        public Nullable<int> ISLEMIZAHAT { get; set; }
        public Nullable<int> BELGEIZAHAT { get; set; }
        public string PARABIRIMI { get; set; }
        public Nullable<System.DateTime> VADE { get; set; }
        public string OZELKOD1 { get; set; }
        public string OZELKOD2 { get; set; }
        public string OZELKOD3 { get; set; }
        public string OZELKOD4 { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<decimal> BORC { get; set; }
        public Nullable<decimal> TAHSILAT { get; set; }
        public Nullable<decimal> KALAN { get; set; }
        public Nullable<int> GUN { get; set; }
        public Nullable<double> GECIKME { get; set; }
        public Nullable<double> VADEFARKI { get; set; }
    }
}
