//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0128D0001TBLSEVTAN
    {
        public byte[] SIMGE1 { get; set; }
        public byte[] SIMGE2 { get; set; }
        public short SEVIYE { get; set; }
        public Nullable<int> FORMAT { get; set; }
        public string SEVIYEADI { get; set; }
    }
}
