//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0127D0002VSTOKHAREKETLERISTOKFAALIYET
    {
        public Nullable<System.Guid> TEKIL { get; set; }
        public Nullable<int> HAREKETIND { get; set; }
        public Nullable<decimal> ENVANTER { get; set; }
        public Nullable<decimal> BIRIMFIYAT { get; set; }
        public decimal ALISMIKTARI { get; set; }
        public decimal SATISMIKTARI { get; set; }
        public string CIKISDEPOSU { get; set; }
        public string GIRISDEPOSU { get; set; }
        public Nullable<int> IND { get; set; }
        public Nullable<short> BELGETIPI { get; set; }
        public Nullable<int> BELGEIND { get; set; }
        public Nullable<System.DateTime> SIRALAMATARIHI { get; set; }
        public Nullable<int> STOKTIPI { get; set; }
        public string FIRMAKODU { get; set; }
        public string FIRMAADI { get; set; }
        public decimal DEPOGIRISMIKTARI { get; set; }
        public decimal DEPOCIKISMIKTARI { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public string STOKKODU { get; set; }
        public Nullable<int> DEPOIND { get; set; }
        public string MALINCINSI { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string ACIKLAMA { get; set; }
        public string BIRIMADI { get; set; }
        public string KOD1 { get; set; }
        public string KOD2 { get; set; }
        public string KOD3 { get; set; }
        public string KOD4 { get; set; }
        public string KOD5 { get; set; }
        public string KOD6 { get; set; }
        public string KOD7 { get; set; }
        public string KOD8 { get; set; }
        public string KOD9 { get; set; }
        public string KOD10 { get; set; }
    }
}
