//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F1073925050TBLDEPOLAR
    {
        public int IND { get; set; }
        public string DEPOADI { get; set; }
        public string DEPOKODU { get; set; }
        public Nullable<int> DEPOSAHIBI { get; set; }
        public Nullable<int> SUBE { get; set; }
        public Nullable<decimal> KOTA { get; set; }
        public Nullable<int> PARABIRIMI { get; set; }
        public Nullable<int> GUN { get; set; }
        public Nullable<int> AY { get; set; }
        public Nullable<int> YIL { get; set; }
        public Nullable<int> BGUN { get; set; }
        public Nullable<int> BAY { get; set; }
        public Nullable<int> BYIL { get; set; }
        public string ACIKLAMA { get; set; }
        public string ADRES { get; set; }
        public string ADRES2 { get; set; }
        public string SINIF { get; set; }
        public string LOKASYON { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string DEPOALIAS { get; set; }
    }
}
