//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAKSGOREVFORMUURUNLER
    {
        public int IND { get; set; }
        public Nullable<int> GOREVFORMUNO { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<decimal> BOY { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
        public Nullable<System.DateTime> CIKISTARIHI { get; set; }
        public Nullable<System.DateTime> TAHMINIHASATTARIHI { get; set; }
        public string STOKKODU { get; set; }
        public Nullable<decimal> FIREORANI { get; set; }
        public Nullable<decimal> KALIBRAJ { get; set; }
        public Nullable<int> TIP { get; set; }
    }
}
