//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAKSGOREVFORMUBASLIK
    {
        public int IND { get; set; }
        public Nullable<int> PERSONELNO { get; set; }
        public string ARAC { get; set; }
        public Nullable<System.DateTime> CIKISSAATI { get; set; }
        public Nullable<decimal> CIKISKM { get; set; }
        public Nullable<System.DateTime> DONUSSAATI { get; set; }
        public Nullable<decimal> DONUSKM { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string GORUSMESEKLI { get; set; }
        public string GOREVKONUSU { get; set; }
        public string GIDILENYER { get; set; }
        public string HASTALIKDURUMU { get; set; }
        public Nullable<System.DateTime> GOREVSURESI { get; set; }
        public Nullable<System.DateTime> VARISSAATI { get; set; }
        public Nullable<System.DateTime> VARISKM { get; set; }
        public string GIDISAMACI { get; set; }
        public string CEVREDEYETISENURUNLER { get; set; }
        public string KULLANILANILACLARTARIHLER { get; set; }
        public string TONAJAGACSAYISIBAHCEYASI { get; set; }
        public Nullable<decimal> TOPLAMALAN { get; set; }
        public Nullable<decimal> PARSELNO { get; set; }
        public string GLOBALGAPNO { get; set; }
        public Nullable<int> TEDARIKCINO { get; set; }
        public Nullable<int> BAHCESAHIBINO { get; set; }
        public Nullable<int> ZIRAATCINO { get; set; }
        public string ORGANIKSERTIFIKANO { get; set; }
        public Nullable<bool> ONAYLIILACDEFTERIVARMI { get; set; }
        public Nullable<bool> GECICISAGLIKSERTVARMI { get; set; }
        public string ANLASMANO { get; set; }
        public Nullable<int> ANLASMAMUSTERINO { get; set; }
        public Nullable<System.DateTime> ANLASMATARIH { get; set; }
        public Nullable<int> ANLASMASATICINO { get; set; }
        public Nullable<int> ANLASMAALICINO { get; set; }
        public string ANLASMAISKARTAKIMEAIT { get; set; }
        public string ANLASMANAKLIYEKIMEAIT { get; set; }
        public string ANLASMAODEMESEKLI { get; set; }
        public string ANLASMAILACBILGISI { get; set; }
        public string ANLASMATESLIMATYERI { get; set; }
        public Nullable<System.DateTime> ANLASMATESLIMATTARIHI { get; set; }
        public string ANLASMAOZELSARTLAR { get; set; }
        public string TEDARIKCITELEFON { get; set; }
        public string TEDARIKCIGSM { get; set; }
        public string TEDARIKCIADRES { get; set; }
        public string BAHCESAHIBITELEFON { get; set; }
        public string BAHCESAHIBIGSM { get; set; }
        public string BAHCESAHIBIADRES { get; set; }
        public string ZIRAATCITELEFON { get; set; }
        public string ZIRAATCIGSM { get; set; }
        public string ZIRAATCIADRES { get; set; }
        public string SATICITELEFON { get; set; }
        public string SATICIGSM { get; set; }
        public string SATICIADRES { get; set; }
        public string ALICITELEFON { get; set; }
        public string ALICIGSM { get; set; }
        public string ALICIADRES { get; set; }
        public string GOREVNO { get; set; }
        public string TEDARIKCIKODU { get; set; }
        public string BAHCESAHIBIKODU { get; set; }
        public string ZIRAATCIKODU { get; set; }
    }
}
