//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAKSMALKABULBASLIK
    {
        public int IND { get; set; }
        public string MALKABULNO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<bool> KABUL { get; set; }
        public Nullable<bool> SARTLIKABUL { get; set; }
        public Nullable<bool> RED { get; set; }
        public string REDACIKLAMA { get; set; }
        public string DEPOGIRISNO { get; set; }
        public string SALMAANLASMANO { get; set; }
        public Nullable<decimal> URUNMIKTARI { get; set; }
        public Nullable<decimal> PALETSAYISI { get; set; }
        public Nullable<int> MALZEMEBILGILERI { get; set; }
        public string ARACPLAKA { get; set; }
        public string BIRIM { get; set; }
        public Nullable<int> ANLASMANO { get; set; }
    }
}
