//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAJNAJANDA
    {
        public int IND { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<System.DateTime> SAAT { get; set; }
        public string GORUSULMEKISTENEN { get; set; }
        public string ARAYAN { get; set; }
        public string ARAYANTELNO { get; set; }
        public Nullable<bool> GORUSULDU { get; set; }
        public string NOT { get; set; }
    }
}
