//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAKSMALZEMEKABULHAREKET
    {
        public int IND { get; set; }
        public Nullable<int> MALZEMEKONTROLNO { get; set; }
        public string KONTROLELEMANLARI { get; set; }
        public string KNO { get; set; }
        public Nullable<bool> KABUL { get; set; }
        public Nullable<bool> RED { get; set; }
        public Nullable<decimal> KG { get; set; }
        public Nullable<decimal> YUZDE { get; set; }
        public Nullable<int> TIP { get; set; }
        public Nullable<int> BASLIKNO { get; set; }
    }
}
