//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAKSKALITEKONTROLHAREKET
    {
        public int IND { get; set; }
        public Nullable<int> URUNNO { get; set; }
        public Nullable<int> BASLIKNO { get; set; }
        public string AMBALAJ { get; set; }
        public string YKOKU { get; set; }
        public Nullable<decimal> YARA { get; set; }
        public Nullable<decimal> CURUK { get; set; }
        public Nullable<decimal> LEKE { get; set; }
        public string RENK { get; set; }
        public Nullable<decimal> EZIK { get; set; }
        public Nullable<decimal> SEKILBOZUKLUGU { get; set; }
        public string URUNCINSI { get; set; }
        public string URUN { get; set; }
        public string UYGUNKALIBRAJARALIGI { get; set; }
        public Nullable<decimal> ISCILIKHATASI { get; set; }
        public string BARKOD { get; set; }
        public string ADISOYADI { get; set; }
        public string LOTNO { get; set; }
        public string PAKETCIBARKOD { get; set; }
        public string KALIBRAJ { get; set; }
        public Nullable<bool> DUZELTILDI { get; set; }
    }
}
