//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAVMHIZMETBASLIK
    {
        public int IND { get; set; }
        public Nullable<int> BELGEIND { get; set; }
        public string BELGENO { get; set; }
        public Nullable<System.DateTime> FTARIH { get; set; }
        public string BELGEKOD1 { get; set; }
        public string BELGEKOD2 { get; set; }
        public string BELGEKOD3 { get; set; }
        public string BELGEKOD4 { get; set; }
        public string BELGENOTU { get; set; }
    }
}
