//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAVMGIDER
    {
        public Nullable<byte> GIDERTIPI { get; set; }
        public int IND { get; set; }
        public Nullable<int> SIRANO { get; set; }
        public Nullable<int> NO { get; set; }
        public Nullable<int> ISYERINO { get; set; }
        public Nullable<int> DONEM { get; set; }
        public Nullable<int> AY { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<System.DateTime> FTARIH { get; set; }
        public Nullable<decimal> KUR { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<bool> FATURALASTI { get; set; }
        public string FIRMAADI { get; set; }
        public string GIDERSTOKKODU { get; set; }
        public string FIRMAKODU { get; set; }
        public string FBELGENO { get; set; }
        public Nullable<int> FBELGEIND { get; set; }
        public Nullable<bool> FIPTAL { get; set; }
    }
}
