//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBEYOTV1BCETVELTECIL
    {
        public int IND { get; set; }
        public Nullable<int> OTVIND { get; set; }
        public string GTIP { get; set; }
        public Nullable<decimal> ITHALMIKTAR { get; set; }
        public Nullable<decimal> TESLIMMIKTAR { get; set; }
        public string OLCUBIRIMI { get; set; }
        public Nullable<System.DateTime> TESLIMTARIHI { get; set; }
        public Nullable<decimal> MAKTUTUTAR { get; set; }
        public Nullable<decimal> HESAPLANANOTV { get; set; }
        public Nullable<decimal> TECILOTV { get; set; }
        public Nullable<decimal> ODENMESIGEREKENOTV { get; set; }
        public Nullable<decimal> TESLIMBEDELI { get; set; }
    }
}
