//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBTCBASLIK
    {
        public int IND { get; set; }
        public string KOD { get; set; }
        public string AD { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<int> DURUM { get; set; }
        public Nullable<int> TIP { get; set; }
        public Nullable<int> DONEM { get; set; }
        public Nullable<decimal> TAHMIN { get; set; }
        public Nullable<decimal> GERCEKLESEN { get; set; }
        public Nullable<decimal> FARK { get; set; }
        public string OZELKOD1 { get; set; }
        public string OZELKOD2 { get; set; }
        public Nullable<bool> ENTEGRE { get; set; }
        public Nullable<bool> BIRLESEN { get; set; }
    }
}
