//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBUTCE
    {
        public int IND { get; set; }
        public string BUTCEKOD { get; set; }
        public string BUTCEAD { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<int> TUR { get; set; }
        public Nullable<decimal> TAHMIN { get; set; }
        public Nullable<decimal> GERCEKLESEN { get; set; }
        public Nullable<decimal> FARK { get; set; }
        public string KOD1 { get; set; }
        public string KOD2 { get; set; }
        public string KOD3 { get; set; }
        public string KOD4 { get; set; }
        public string KOD5 { get; set; }
    }
}
