//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBUTCEAYLIKHEDEFLER
    {
        public int IND { get; set; }
        public string KOD { get; set; }
        public string OZELKOD { get; set; }
        public Nullable<decimal> OCAK { get; set; }
        public Nullable<decimal> SUBAT { get; set; }
        public Nullable<decimal> MART { get; set; }
        public Nullable<decimal> NISAN { get; set; }
        public Nullable<decimal> MAYIS { get; set; }
        public Nullable<decimal> HAZIRAN { get; set; }
        public Nullable<decimal> TEMMUZ { get; set; }
        public Nullable<decimal> AGUSTOS { get; set; }
        public Nullable<decimal> EYLUL { get; set; }
        public Nullable<decimal> EKIM { get; set; }
        public Nullable<decimal> KASIM { get; set; }
        public Nullable<decimal> ARALIK { get; set; }
        public Nullable<bool> PARASAL { get; set; }
    }
}
