//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBEYKURUMISINAIMULKIYETISTISNATABLOSU
    {
        public int IND { get; set; }
        public Nullable<int> KURUMIND { get; set; }
        public string PATENTSAHIBI { get; set; }
        public string TCKIMLIKNO { get; set; }
        public string BELGEMODELI { get; set; }
        public string BELGENO { get; set; }
        public Nullable<System.DateTime> KSSETARIHI { get; set; }
        public string ISTISNAYARARLANMA { get; set; }
        public Nullable<decimal> TAHMINIDEGER { get; set; }
        public Nullable<decimal> TESPITEDILENDEGER { get; set; }
        public Nullable<decimal> YISTISNATOPLAM { get; set; }
        public Nullable<decimal> YISTISNAMUKELLEF { get; set; }
        public Nullable<decimal> OMISTISNAMUKELLEF { get; set; }
        public Nullable<decimal> CDISTISNATUTARI { get; set; }
        public Nullable<bool> GELIRGECICI { get; set; }
        public Nullable<decimal> KAZANCTUTAR { get; set; }
        public string KAZANCTUR { get; set; }
    }
}
