//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBEYEKC
    {
        public int IND { get; set; }
        public string ACIKLAMA { get; set; }
        public string YILI { get; set; }
        public Nullable<bool> SEC { get; set; }
        public Nullable<bool> YAZDIR { get; set; }
        public byte[] DATA { get; set; }
    }
}
