//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBEYOTV1EKDAGITIM
    {
        public int IND { get; set; }
        public Nullable<int> OTVIND { get; set; }
        public string DIBVD { get; set; }
        public Nullable<System.DateTime> DIBTARIH { get; set; }
        public string DIBNO { get; set; }
        public Nullable<System.DateTime> DIBBITISTARIHI { get; set; }
    }
}
