//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCRM2GORUSMENOT
    {
        public int IND { get; set; }
        public Nullable<int> GORUSMENO { get; set; }
        public Nullable<int> BASLIK { get; set; }
        public string PNOT { get; set; }
    }
}
