//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLDEFAULTSTOK
    {
        public string BIRIM { get; set; }
        public Nullable<decimal> ALTSEVIYE { get; set; }
        public Nullable<decimal> KRITIKSEVIYE { get; set; }
        public Nullable<decimal> USTSEVIYE { get; set; }
        public Nullable<int> PARABIRIMI { get; set; }
        public Nullable<bool> KDVDAHIL { get; set; }
        public Nullable<short> KDV { get; set; }
        public int IND { get; set; }
    }
}
