//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLDEVIRITEMS
    {
        public int IND { get; set; }
        public Nullable<int> DEVIRIND { get; set; }
        public Nullable<int> DEPONO { get; set; }
        public Nullable<decimal> ENVANTER { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public Nullable<decimal> GIREN { get; set; }
        public Nullable<decimal> CIKAN { get; set; }
    }
}
