//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLDPRIM2
    {
        public int IND { get; set; }
        public Nullable<int> PERSONELIND { get; set; }
        public Nullable<int> DPRIMIND { get; set; }
        public string SSKSICILNO { get; set; }
        public Nullable<System.DateTime> ISEGIRISTARIHI { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public Nullable<System.DateTime> ISTENCIKISTARIHI { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<int> GUN { get; set; }
        public Nullable<decimal> KAZANC { get; set; }
    }
}
