//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFASTERPROTOKOL
    {
        public int IND { get; set; }
        public Nullable<int> PROIND { get; set; }
        public string ACIKLAMA { get; set; }
        public string STOKKODU { get; set; }
        public string FIRMAKODU { get; set; }
        public Nullable<int> SATISSEKLI { get; set; }
        public Nullable<System.DateTime> BSATISTARIHI { get; set; }
        public Nullable<System.DateTime> SSATISTARIHI { get; set; }
        public string SATISFIYATI { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public string BSATISSAATI { get; set; }
        public string SSATISSAATI { get; set; }
        public Nullable<decimal> SABITFIYAT { get; set; }
        public Nullable<int> FIYAT { get; set; }
        public Nullable<int> SUBEIND { get; set; }
        public string SUBEADI { get; set; }
        public Nullable<int> KATEGORI { get; set; }
        public Nullable<bool> STOKISKONTOSUKULLANILSIN { get; set; }
        public Nullable<decimal> ISK1 { get; set; }
        public Nullable<decimal> ISK2 { get; set; }
        public string BIRIMADI { get; set; }
        public string PROVADEKARTLARI { get; set; }
    }
}
