//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFASTERFIRMA
    {
        public int IND { get; set; }
        public string KOD { get; set; }
        public string KISAAD { get; set; }
        public string AD1 { get; set; }
        public string AD2 { get; set; }
        public Nullable<int> FIRMATIPI { get; set; }
        public string VDAIRESI { get; set; }
        public string VNO { get; set; }
        public Nullable<short> AKTIFDONEM { get; set; }
        public Nullable<int> EFATURASTATUS { get; set; }
        public Nullable<bool> EARSIVSTATUS { get; set; }
    }
}
