//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFASTERCARIBORDROLAR
    {
        public int IND { get; set; }
        public Nullable<int> CARIIND { get; set; }
        public Nullable<decimal> ODENEN { get; set; }
        public Nullable<int> ODEMETIPI { get; set; }
        public Nullable<int> YCEKIIND { get; set; }
        public Nullable<int> BANKAIND { get; set; }
        public Nullable<bool> IADE { get; set; }
        public Nullable<bool> AKTARILDI { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string FIRMAKODU { get; set; }
        public Nullable<int> SUBEIND { get; set; }
        public Nullable<int> USERIND { get; set; }
        public Nullable<int> KASAIND { get; set; }
        public Nullable<int> CARIBELGEIND { get; set; }
        public Nullable<bool> GIRIS { get; set; }
        public Nullable<int> VARDIYAIND { get; set; }
        public string VARDIYA { get; set; }
        public Nullable<bool> TAHSILAT { get; set; }
        public Nullable<System.DateTime> VARDIYATARIHI { get; set; }
        public Nullable<decimal> DOVIZODENEN { get; set; }
        public Nullable<decimal> KUR { get; set; }
        public string DOVIZPB { get; set; }
        public string OZELKOD5 { get; set; }
        public string OZELKOD6 { get; set; }
        public string BELGENOTU { get; set; }
        public Nullable<decimal> ORJTUTAR { get; set; }
        public Nullable<bool> YAZDIRILDI { get; set; }
        public Nullable<int> BELGETIPI { get; set; }
    }
}
