//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFASTERBANKALAR
    {
        public int IND { get; set; }
        public Nullable<int> BANKANO { get; set; }
        public string ADI { get; set; }
        public string KOD { get; set; }
        public string SUBE { get; set; }
        public string TEL { get; set; }
        public string FAX { get; set; }
        public string YETKILI { get; set; }
        public string HESAPNO { get; set; }
        public Nullable<decimal> FAIZ { get; set; }
        public string KOD1 { get; set; }
        public string KOD2 { get; set; }
        public string KOD3 { get; set; }
        public string KOD4 { get; set; }
        public string KOD5 { get; set; }
        public Nullable<decimal> KOMISYON { get; set; }
        public Nullable<int> OPSIYON { get; set; }
        public Nullable<int> SUBEIND { get; set; }
        public string SUBEADI { get; set; }
    }
}
