//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFASTERTERAPOSTERAZILIST
    {
        public int IND { get; set; }
        public Nullable<int> SUBENO { get; set; }
        public Nullable<int> KASANO { get; set; }
        public string KASAADI { get; set; }
        public Nullable<int> PORTNO { get; set; }
        public Nullable<bool> AKTIF { get; set; }
        public string DOSYAYOLU { get; set; }
    }
}
