//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFASTERBEKLEYENBASLIK
    {
        public int IND { get; set; }
        public Nullable<int> BASLIKIND { get; set; }
        public string MUSSIRANO { get; set; }
        public string BARCODE { get; set; }
        public Nullable<int> CARIIND { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<decimal> SATIRISK { get; set; }
        public Nullable<decimal> ALTISKORAN { get; set; }
        public Nullable<decimal> ALTISK { get; set; }
        public Nullable<bool> IADE { get; set; }
        public Nullable<bool> AKTARILDI { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<System.DateTime> ISLEMTARIHI { get; set; }
        public string FIRMAKODU { get; set; }
        public string FIRMAADI { get; set; }
        public Nullable<int> SUBEIND { get; set; }
        public Nullable<int> USERIND { get; set; }
        public Nullable<int> KASAIND { get; set; }
        public Nullable<int> VARDIYAIND { get; set; }
        public string BELGENO { get; set; }
        public Nullable<int> VEGABELGEIND { get; set; }
        public string PERKODU { get; set; }
        public Nullable<System.DateTime> VARDIYATARIHI { get; set; }
        public string OZELKOD5 { get; set; }
        public string OZELKOD6 { get; set; }
        public string BELGENOTU { get; set; }
        public Nullable<bool> YAZDIRILDI { get; set; }
        public Nullable<int> BELGETIPI { get; set; }
        public string VARDIYA { get; set; }
        public Nullable<bool> BEKLEYEN { get; set; }
        public Nullable<int> SIPARISIND { get; set; }
    }
}
