//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKONINDCONVERT
    {
        public int KONNO { get; set; }
        public string TABLO { get; set; }
        public int ORJIND { get; set; }
        public Nullable<int> LOKALIND { get; set; }
    }
}
