//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLLOJSOZLESMEODEME
    {
        public int Ind { get; set; }
        public Nullable<int> BaslikInd { get; set; }
        public Nullable<decimal> NakitAvansTutari { get; set; }
        public Nullable<decimal> YakitAvansTutari { get; set; }
        public Nullable<decimal> DigerAvansTutari { get; set; }
        public string DigerAvansAciklama { get; set; }
        public Nullable<decimal> HarcirahTutari { get; set; }
        public Nullable<decimal> DigerHarcirahTutari { get; set; }
        public string DigerHarcirahAciklama { get; set; }
        public Nullable<decimal> KesintiTutari { get; set; }
    }
}
