//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLLOJFORMYETKILERI
    {
        public int Ind { get; set; }
        public string FormName { get; set; }
        public string ComponentDisplayLabel { get; set; }
        public string ComponentName { get; set; }
        public Nullable<int> Yetki { get; set; }
        public Nullable<int> UserNo { get; set; }
    }
}
