//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMKTALISANLASMASIBASLIK
    {
        public int IND { get; set; }
        public string FIRMAKODU { get; set; }
        public string FIRMAADI { get; set; }
        public Nullable<System.DateTime> ANLASMATARIHI { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<System.DateTime> BASLANGICTARIHI { get; set; }
        public Nullable<System.DateTime> BITISTARIHI { get; set; }
        public Nullable<int> KAYNAKEVRAKTIP { get; set; }
        public Nullable<int> GERCEKLESMEKOSULUTIP { get; set; }
        public Nullable<decimal> GERCEKLESMEKOSULUDEGER { get; set; }
        public Nullable<int> ANLASMASONUCUTIP { get; set; }
        public Nullable<decimal> ANLASMASONUCUDEGER { get; set; }
        public Nullable<int> SONUCEVRAKTIP { get; set; }
        public Nullable<int> ODEMETARIHITIP { get; set; }
        public Nullable<int> HIZMETKDVSI { get; set; }
        public Nullable<int> FIRMAIND { get; set; }
        public Nullable<int> ODEMEARALIKLARI { get; set; }
    }
}
