//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMUSURUNALIMSOZLESMESIHAREKET
    {
        public int IND { get; set; }
        public Nullable<int> BASLIKIND { get; set; }
        public Nullable<int> STOKIND { get; set; }
        public Nullable<int> BIRIMIND { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<decimal> DALADEDI { get; set; }
        public Nullable<decimal> ALANMIKTAR { get; set; }
        public Nullable<decimal> SAPMA { get; set; }
        public string ALANADI { get; set; }
    }
}
