//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLODEMEPLANITALEPONAY
    {
        public int IND { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<int> BELGETIPI { get; set; }
        public Nullable<int> BELGEIND { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<int> USERNO { get; set; }
        public Nullable<int> PLANIND { get; set; }
        public Nullable<int> SIRANO { get; set; }
        public string UID { get; set; }
    }
}
