//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLOTSGUMRUKBILGISI
    {
        public int IND { get; set; }
        public string GMUDURLUK { get; set; }
        public string BEYANNAMENO { get; set; }
        public string PERMILISANSNO { get; set; }
        public string MAKBUZNO { get; set; }
        public Nullable<System.DateTime> BEYTARIH { get; set; }
        public Nullable<System.DateTime> PERMILISANSTARIH { get; set; }
        public Nullable<System.DateTime> MAKBUZTARIH { get; set; }
        public Nullable<int> TBLALFATBASLIKREF { get; set; }
        public Nullable<decimal> GUMRUKVERGITUTARI { get; set; }
        public Nullable<int> TBLOTSARACLISTREF { get; set; }
    }
}
