//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLOTOB2BFIRMADONEM
    {
        public int IND { get; set; }
        public string DATABASENAME { get; set; }
        public string FIRMA { get; set; }
        public string DONEM { get; set; }
        public Nullable<int> FIRMAID { get; set; }
        public Nullable<int> DONEMID { get; set; }
    }
}
