//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPLUGMUSTAHSILDEPODEGER
    {
        public int IND { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<decimal> KILO { get; set; }
        public Nullable<decimal> PROTEIN { get; set; }
        public Nullable<decimal> SUNE { get; set; }
        public Nullable<decimal> RUTUBET { get; set; }
        public Nullable<decimal> HEKTOLITRE { get; set; }
        public Nullable<int> STOKIND { get; set; }
        public Nullable<int> DEPOIND { get; set; }
        public Nullable<int> BELGEIND { get; set; }
        public Nullable<int> BELGEIZAHAT { get; set; }
        public Nullable<int> HAREKETIND { get; set; }
        public string UID { get; set; }
    }
}
