//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPOSSTKBASLIK
    {
        public int IND { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string NUMARA { get; set; }
        public Nullable<int> FISFAT { get; set; }
        public Nullable<decimal> TOPLAM { get; set; }
        public Nullable<int> KASANO { get; set; }
        public Nullable<int> KASIYERNO { get; set; }
        public Nullable<int> CARIIND { get; set; }
        public string TIP { get; set; }
        public Nullable<decimal> KRE1 { get; set; }
        public Nullable<decimal> KRE2 { get; set; }
        public Nullable<decimal> KRE3 { get; set; }
        public Nullable<decimal> KRE4 { get; set; }
        public Nullable<decimal> KRE5 { get; set; }
        public Nullable<decimal> KRE6 { get; set; }
        public Nullable<System.DateTime> VADE { get; set; }
        public Nullable<decimal> NAK { get; set; }
        public Nullable<decimal> KRE7 { get; set; }
        public Nullable<decimal> KRE8 { get; set; }
        public Nullable<decimal> KRE9 { get; set; }
        public Nullable<decimal> KRE10 { get; set; }
        public Nullable<decimal> KRE11 { get; set; }
        public Nullable<decimal> KRE12 { get; set; }
        public Nullable<decimal> KRE13 { get; set; }
        public Nullable<decimal> KRE14 { get; set; }
        public Nullable<decimal> KRE15 { get; set; }
        public Nullable<decimal> KRE16 { get; set; }
        public Nullable<decimal> KRE17 { get; set; }
        public Nullable<decimal> KRE18 { get; set; }
        public Nullable<decimal> KRE19 { get; set; }
        public Nullable<decimal> KRE20 { get; set; }
        public Nullable<decimal> TOPLAMINDIRIMI { get; set; }
    }
}
