//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPERDIZI2
    {
        public int IND { get; set; }
        public Nullable<int> DIZIREF { get; set; }
        public Nullable<int> SIRA { get; set; }
        public string SSKSICILNO { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public Nullable<System.DateTime> ISEGIRISTARIHI { get; set; }
        public string ILKTEKRAR { get; set; }
    }
}
