//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPCPOSODEMEDETAY
    {
        public int IND { get; set; }
        public Nullable<int> BELGEIND { get; set; }
        public Nullable<int> BELGETIPI { get; set; }
        public Nullable<decimal> NAKIT { get; set; }
        public Nullable<decimal> VISA { get; set; }
        public Nullable<decimal> TICKET { get; set; }
    }
}
