//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLRESMASABUFFER
    {
        public int IND { get; set; }
        public Nullable<int> GARSONIND { get; set; }
        public Nullable<int> MASAIND { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<int> HAZIR { get; set; }
        public Nullable<int> DESCCODE { get; set; }
        public Nullable<int> BIRIMIND { get; set; }
        public string REMOTEIP { get; set; }
        public Nullable<int> DEPO { get; set; }
        public Nullable<int> SATISFIYATINO { get; set; }
    }
}
