//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSTKCIKHAREKET
    {
        public int IND { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<int> DETAY { get; set; }
        public Nullable<bool> SELECTED { get; set; }
        public Nullable<int> EVRAKNO { get; set; }
        public Nullable<int> FIRMANO { get; set; }
        public Nullable<int> STOKNO { get; set; }
        public string MALINCINSI { get; set; }
        public string STOKKODU { get; set; }
        public Nullable<int> STOKTIPI { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<decimal> BIRIMMIKTAR { get; set; }
        public string BIRIM { get; set; }
        public Nullable<int> BIRIMEX { get; set; }
        public Nullable<short> KDV { get; set; }
        public Nullable<decimal> KDVTUTARI { get; set; }
        public Nullable<decimal> ISK1 { get; set; }
        public Nullable<decimal> ISK2 { get; set; }
        public Nullable<decimal> ISK3 { get; set; }
        public Nullable<decimal> ISK4 { get; set; }
        public Nullable<decimal> AFIYATI { get; set; }
        public Nullable<decimal> FIYATI { get; set; }
        public Nullable<decimal> GERCEKTOPLAM { get; set; }
        public Nullable<int> DEPO { get; set; }
        public Nullable<int> PERSONEL { get; set; }
        public Nullable<decimal> PIRIM { get; set; }
        public Nullable<int> OPSIYON { get; set; }
        public Nullable<int> PROMOSYON { get; set; }
        public Nullable<int> SATISKOSULU { get; set; }
        public Nullable<decimal> SERIMIKTAR { get; set; }
        public Nullable<decimal> ENVANTER { get; set; }
        public string KARSISTOKKODU { get; set; }
        public string KARSIBARKOD { get; set; }
        public Nullable<System.DateTime> TERMIN { get; set; }
        public Nullable<int> TAKSIT { get; set; }
        public string PARABIRIMI { get; set; }
        public Nullable<decimal> KUR { get; set; }
        public string BARKOD { get; set; }
        public Nullable<decimal> PESINAT { get; set; }
        public Nullable<decimal> MASRAF { get; set; }
        public Nullable<decimal> MASRAFKDV { get; set; }
        public string ACIKLAMA { get; set; }
        public string PACIKLAMA { get; set; }
        public Nullable<decimal> OIV { get; set; }
        public Nullable<decimal> INDIRIM { get; set; }
        public Nullable<decimal> OTV { get; set; }
        public Nullable<decimal> HURDAINDIRIMI { get; set; }
        public Nullable<decimal> GUMRUKVERGISI { get; set; }
        public Nullable<decimal> DIGERVERGILER { get; set; }
        public string MIKTARSTR { get; set; }
        public Nullable<int> GK { get; set; }
        public Nullable<decimal> GRUPMIKTAR { get; set; }
        public string KOD1 { get; set; }
        public Nullable<decimal> ISK5 { get; set; }
        public Nullable<decimal> ISK6 { get; set; }
        public string UID { get; set; }
        public Nullable<decimal> OTVMATRAHI { get; set; }
        public Nullable<decimal> KDV_EXMATRAHI { get; set; }
        public Nullable<decimal> GMIKTAR { get; set; }
        public Nullable<decimal> MF { get; set; }
        public Nullable<decimal> ORJFIYAT { get; set; }
        public Nullable<int> SATIRNO { get; set; }
    }
}
