//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSUBELER
    {
        public int IND { get; set; }
        public string SUBEAD { get; set; }
        public Nullable<bool> SECIM { get; set; }
        public Nullable<int> PARAMETREIND { get; set; }
        public string SSKISKOLU { get; set; }
        public string ADRES { get; set; }
        public Nullable<int> IL { get; set; }
        public string ILCE { get; set; }
        public string SEMT { get; set; }
        public string POSTAKOD { get; set; }
        public string ALANKODU1 { get; set; }
        public string TELEFON1 { get; set; }
        public string ALANKODU2 { get; set; }
        public string TELEFON2 { get; set; }
        public string ALANKODU3 { get; set; }
        public string FAX { get; set; }
        public string CALISMAKONUSU { get; set; }
        public Nullable<decimal> GUNDEKISAAT { get; set; }
        public string VERGIDAIRESI { get; set; }
        public string VERGINO { get; set; }
        public string SSKSICILNO { get; set; }
        public string CBSICILNO1 { get; set; }
        public string CBSICILNO2 { get; set; }
        public string CBSICILNO3 { get; set; }
        public string CBSICILNO4 { get; set; }
        public string TEHLIKEDERECESI { get; set; }
        public string TEHLIKESINIFI { get; set; }
        public string MUHASEBE { get; set; }
        public string ISINFALIYETSURESI { get; set; }
        public string TABIOLDUGUSEKTOR { get; set; }
        public Nullable<System.DateTime> BASLAMATARIHI { get; set; }
        public Nullable<System.DateTime> BITISTARIHI { get; set; }
        public Nullable<System.DateTime> ISCICALISTIRMATARIHI { get; set; }
        public string TSOKAYITNO { get; set; }
        public string TSVKAYITNO { get; set; }
        public string IHALEUNVAN { get; set; }
        public string IHALEADRES { get; set; }
        public string IHALEISKODU { get; set; }
        public string IHALESEMT { get; set; }
        public string IHALEILCE { get; set; }
        public Nullable<int> IHALEIL { get; set; }
        public string IHALEPKODU { get; set; }
        public string IHALETELEFON { get; set; }
        public string IHALEEPOSTA { get; set; }
        public string IHALEMERNISNO { get; set; }
        public string IHALEVERGINO { get; set; }
        public string ISVAD { get; set; }
        public string ISVSOYAD { get; set; }
        public string ISVADRES { get; set; }
        public Nullable<int> ISVIL { get; set; }
        public string ISVILCE { get; set; }
        public string ISVPOSTAKOD { get; set; }
        public string ISVALANKODU1 { get; set; }
        public string ISVTELEFON1 { get; set; }
        public string ISVALANKODU2 { get; set; }
        public string ISVTELEFON2 { get; set; }
        public string ISVALANKODU3 { get; set; }
        public string ISVFAX { get; set; }
        public string ISVBABAADI { get; set; }
        public string ISVANAADI { get; set; }
        public Nullable<System.DateTime> ISVDOGUMTARIHI { get; set; }
        public string ISVDOGUMYERI { get; set; }
        public string ISVNUFUSSERINO { get; set; }
        public string ISVARACPLAKA { get; set; }
        public Nullable<int> ISVNUFUSIL { get; set; }
        public string ISVNUFUSILCE { get; set; }
        public string ISVNUFUSMAHKOY { get; set; }
        public string ISVNUFSIRANO { get; set; }
        public string ISVNUFAILESIRANO { get; set; }
        public string ISVNUFSAYFANO { get; set; }
        public string MERNISNO { get; set; }
        public string VEKILAD { get; set; }
        public string VEKILSOYAD { get; set; }
        public string VEKILADRES { get; set; }
        public Nullable<int> VEKILIL { get; set; }
        public string VEKILILCE { get; set; }
        public string VEKILPOSTAKOD { get; set; }
        public string VEKILALANKODU1 { get; set; }
        public string VEKILTELEFON1 { get; set; }
        public string VEKILALANKODU2 { get; set; }
        public string VEKILTELEFON2 { get; set; }
        public string VEKILALANKODU3 { get; set; }
        public string VEKILFAX { get; set; }
        public string VEKILBABAADI { get; set; }
        public string VEKILANAADI { get; set; }
        public Nullable<System.DateTime> VEKILDOGUMTARIHI { get; set; }
        public string VEKILDOGUMYERI { get; set; }
        public string VEKILNUFUSSERINO { get; set; }
        public string VEKILARACPLAKA { get; set; }
        public Nullable<int> VEKILNUFUSIL { get; set; }
        public string VEKILNUFUSILCE { get; set; }
        public string VEKILNUFUSMAHKOY { get; set; }
        public string VEKILNUFSIRANO { get; set; }
        public string VEKILNUFAILESIRANO { get; set; }
        public string VEKILNUFSAYFANO { get; set; }
        public string MUHASEBEKOD { get; set; }
        public Nullable<short> ENTSEKLI { get; set; }
        public string RPTDIZIN { get; set; }
        public string EPOSTA { get; set; }
        public string SIRALAMAKOLON { get; set; }
        public Nullable<int> KIDEMGUN { get; set; }
        public string ULKE { get; set; }
        public string IHTIYATSANDIKNO { get; set; }
        public string ISKURNO { get; set; }
        public string BAGIMSIZTURU { get; set; }
        public string BAGIMLITURU { get; set; }
        public string MEYDAN { get; set; }
        public string SOKAK { get; set; }
        public string MAHALLE { get; set; }
        public string KUMEADI { get; set; }
        public string KOY { get; set; }
        public string BULVAR { get; set; }
        public string CADDE { get; set; }
        public string BUCAK { get; set; }
        public string DISKAPINO { get; set; }
        public string ICKAPINO { get; set; }
        public Nullable<System.DateTime> KISABASLAMATARIH { get; set; }
        public Nullable<System.DateTime> KISABITISTARIH { get; set; }
        public Nullable<decimal> KISAHAFTACALISMAYACAKSURE { get; set; }
        public string KISAEKSIKGUNNEDENI { get; set; }
        public Nullable<short> KISAUYGULANANDEVREDENAY { get; set; }
        public Nullable<short> KISAUYGULANANDEVREDENGUN { get; set; }
        public Nullable<short> KISAUYGULANANAY { get; set; }
        public Nullable<short> KISAUYGULANANAYGUN { get; set; }
    }
}
