//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSETSTOKRECETEBASLIK
    {
        public int IND { get; set; }
        public Nullable<int> STOKIND { get; set; }
        public string STOKKODU { get; set; }
        public string MALINCINSI { get; set; }
        public Nullable<int> BIRIMIND { get; set; }
        public string BIRIMADI { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public string RECETEKODU { get; set; }
        public string RECETEADI { get; set; }
        public Nullable<System.DateTime> RECETETARIHI { get; set; }
        public Nullable<decimal> MALIYET { get; set; }
        public Nullable<decimal> SATISFIYATI { get; set; }
    }
}
