//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLTTSPAKET
    {
        public int IND { get; set; }
        public string HEADERID { get; set; }
        public string SENDER { get; set; }
        public string RECEIVER { get; set; }
        public string WAYBILLDATE { get; set; }
        public string HEADERSTATE { get; set; }
        public string OPERATION { get; set; }
        public string DETAILCOUNT { get; set; }
        public string BELGENO { get; set; }
    }
}
