//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLTAKSITLER
    {
        public int IND { get; set; }
        public Nullable<int> MUSTERINO { get; set; }
        public Nullable<int> SATIS { get; set; }
        public string IZAHAT { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<decimal> ODENEN { get; set; }
        public Nullable<System.DateTime> ODEMETARIHI { get; set; }
        public Nullable<System.DateTime> TAHSILTARIHI { get; set; }
        public Nullable<bool> SELECTED { get; set; }
    }
}
