//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLTRMRAPOR
    {
        public int IND { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<int> IZAHAT { get; set; }
        public string EVRAKNO { get; set; }
        public Nullable<decimal> GIREN { get; set; }
        public Nullable<decimal> CIKAN { get; set; }
        public Nullable<decimal> BIRIMMALIYET { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<decimal> KUR { get; set; }
        public string PARABIRIMI { get; set; }
        public string STOKKODU { get; set; }
        public string MALINCINSI { get; set; }
        public string FIRMAKODU { get; set; }
        public string FIRMAADI { get; set; }
        public string KOD1 { get; set; }
        public string KOD2 { get; set; }
        public string KOD3 { get; set; }
        public string KOD4 { get; set; }
        public string KOD5 { get; set; }
        public string KOD6 { get; set; }
        public string KOD7 { get; set; }
        public string KOD8 { get; set; }
        public string KOD9 { get; set; }
        public string KOD10 { get; set; }
        public string ADRESPOSTA { get; set; }
        public string CKOD1 { get; set; }
        public string CKOD2 { get; set; }
        public string CKOD3 { get; set; }
        public string CKOD4 { get; set; }
        public string CKOD5 { get; set; }
        public string TRMKOD1 { get; set; }
        public string TRMKOD2 { get; set; }
        public string TRMKOD3 { get; set; }
        public string YETISTIRDIGIURUN { get; set; }
        public string ARAZIDURUMU { get; set; }
        public string BARKOD { get; set; }
        public Nullable<decimal> ENVANTER { get; set; }
        public string PACIKLAMA { get; set; }
        public string BASLIKACIKLAMASI { get; set; }
        public string SARJNO { get; set; }
        public Nullable<System.DateTime> IMALTARIH { get; set; }
        public Nullable<System.DateTime> SONKULLANMATARIH { get; set; }
        public string HEDEFURUN { get; set; }
        public string HEDEFZARARLI { get; set; }
        public string BAYIADISOYADI { get; set; }
        public string BAYIADRES { get; set; }
        public string BAYIIZINNO { get; set; }
        public Nullable<System.DateTime> BAYIIZINTARIH { get; set; }
        public string BAYIVERGIDAIRE { get; set; }
        public string BAYIVERGINO { get; set; }
        public string BAYITELEFON { get; set; }
        public string BAYIBOLGE { get; set; }
    }
}
