//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLTEKTALIMATBASLIK
    {
        public int IND { get; set; }
        public string TALIMATKODU { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<int> DEPARTMAN { get; set; }
        public Nullable<decimal> UCRET { get; set; }
    }
}
