//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLTEKDEPARTMANTAKVIM
    {
        public int IND { get; set; }
        public Nullable<int> DEPARTMANNO { get; set; }
        public string PAZARTESİ { get; set; }
        public string SALI { get; set; }
        public string CARSAMBA { get; set; }
        public string PERSEMBE { get; set; }
        public string CUMA { get; set; }
        public string CUMARTESI { get; set; }
        public string PAZAR { get; set; }
    }
}
