//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLVMCSCRIPT
    {
        public int IND { get; set; }
        public string CLASSNAME { get; set; }
        public string NAME { get; set; }
        public string BODY { get; set; }
        public string CODEEXP { get; set; }
        public string OPENFILES { get; set; }
    }
}
