//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLVIZITE2
    {
        public int IND { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<int> PERSONELIND { get; set; }
        public Nullable<int> SUBEIND { get; set; }
        public Nullable<int> YIL { get; set; }
        public Nullable<int> AY { get; set; }
        public string SICILNO { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public Nullable<System.DateTime> ISEGIRISTARIHI { get; set; }
        public Nullable<System.DateTime> ISTENCIKISTARIHI { get; set; }
        public string PRIMODEMEDURUM { get; set; }
        public string SUBEADRES { get; set; }
        public Nullable<int> SUBEIL { get; set; }
        public string SUBEILCE { get; set; }
        public string SUBESSKSICILNO { get; set; }
        public string YAKINLIK { get; set; }
        public string AY1 { get; set; }
        public string AY2 { get; set; }
        public string AY3 { get; set; }
        public string AY4 { get; set; }
        public string AY5 { get; set; }
        public string AY6 { get; set; }
        public string AY7 { get; set; }
        public string AY8 { get; set; }
        public string AY9 { get; set; }
        public string AY10 { get; set; }
        public string AY11 { get; set; }
        public string AY12 { get; set; }
        public string YIL1 { get; set; }
        public string YIL2 { get; set; }
        public string YIL3 { get; set; }
        public string YIL4 { get; set; }
        public string YIL5 { get; set; }
        public string YIL6 { get; set; }
        public string YIL7 { get; set; }
        public string YIL8 { get; set; }
        public string YIL9 { get; set; }
        public string YIL10 { get; set; }
        public string YIL11 { get; set; }
        public string YIL12 { get; set; }
        public Nullable<int> PRIM1 { get; set; }
        public Nullable<int> PRIM2 { get; set; }
        public Nullable<int> PRIM3 { get; set; }
        public Nullable<int> PRIM4 { get; set; }
        public Nullable<int> PRIM5 { get; set; }
        public Nullable<int> PRIM6 { get; set; }
        public Nullable<int> PRIM7 { get; set; }
        public Nullable<int> PRIM8 { get; set; }
        public Nullable<int> PRIM9 { get; set; }
        public Nullable<int> PRIM10 { get; set; }
        public Nullable<int> PRIM11 { get; set; }
        public Nullable<int> PRIM12 { get; set; }
        public string PRIMDURUMU { get; set; }
        public string KIMLIKNO { get; set; }
        public string YMERNISNO { get; set; }
        public string YADRES { get; set; }
        public string YCINSIYET { get; set; }
        public string YUYRUK { get; set; }
        public Nullable<System.DateTime> VIZITETARIHI { get; set; }
    }
}
