//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class U0105TBLAJNTEKRAR
    {
        public int IND { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<System.DateTime> STARTTIME { get; set; }
        public Nullable<System.DateTime> ENDTIME { get; set; }
        public Nullable<int> TEKRARSAYISI { get; set; }
        public Nullable<int> GTEKRARSAYISI { get; set; }
        public Nullable<int> HTEKRARSAYISI { get; set; }
        public Nullable<int> HGUN { get; set; }
        public Nullable<int> AGUN { get; set; }
        public Nullable<int> ATEKRARSAYISI { get; set; }
        public Nullable<int> YAY { get; set; }
        public Nullable<int> YTEKRARSAYISI { get; set; }
        public Nullable<int> LINK { get; set; }
        public Nullable<int> TEKRARTIPI { get; set; }
        public Nullable<int> EVENTTYPE { get; set; }
        public Nullable<int> SECILI { get; set; }
        public Nullable<bool> RB1 { get; set; }
        public Nullable<bool> RB2 { get; set; }
    }
}
