//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Faaliyet
    {
        public string BELGENO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string FIRMAADI { get; set; }
        public string KOD5 { get; set; }
        public Nullable<decimal> BAKIYE { get; set; }
        public decimal TLCIKAN { get; set; }
        public decimal TLGIREN { get; set; }
        public Nullable<decimal> TLTOPLAM { get; set; }
        public string BASLIKOZELKOD1 { get; set; }
    }
}
