//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_GecSipList
    {
        public int IND { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<int> FIRMANO { get; set; }
        public string STOKKODU { get; set; }
        public string MALINCINSI { get; set; }
        public string FIRMAKODU { get; set; }
        public string FIRMAADI { get; set; }
        public string EVRAKCINSI { get; set; }
        public Nullable<decimal> SATISFIYATI1 { get; set; }
        public string SBIRIMADI { get; set; }
        public Nullable<decimal> SMIKTAR { get; set; }
        public Nullable<bool> KDVDAHIL { get; set; }
        public string BARCODE { get; set; }
        public string EVRAKNO { get; set; }
        public Nullable<int> KDV { get; set; }
        public Nullable<decimal> CIKAN { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<decimal> BIRIMMALIYET { get; set; }
        public Nullable<decimal> TOPLAMKDV { get; set; }
        public Nullable<decimal> ARATOPLAM { get; set; }
        public Nullable<decimal> GENELTOPLAM { get; set; }
    }
}
