//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_SatFat
    {
        public int IND { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string FIRMAKODU { get; set; }
        public string FIRMAADI { get; set; }
        public string BELGENO { get; set; }
        public string KOD5 { get; set; }
        public int CARIIND { get; set; }
        public Nullable<bool> IPTAL { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public string UNVAN { get; set; }
        public Nullable<int> PERSONELNO { get; set; }
        public Nullable<int> FIRMATIPI { get; set; }
    }
}
